"""Document a repository's QA process from what its files declare -- L-0618.

Reads the same inputs as qa_audit.py (`.crew/verify.json`, `_verify/`, CI
files) plus the audit's own report, and writes:

  docs/qa/README.md                    the QA process, diagrams embedded as Mermaid
  docs/qa/qa-process.html              the same content as one HTML page
  docs/diagrams/process-qa-gates.mmd   the gate flow, crew-diagrams provenance header
  docs/diagrams/process-qa-ladder.mmd  the promotion ladder, same header

DRY RUN BY DEFAULT. Without `--write` it prints what it would write and
writes nothing. With `--write` it never overwrites a file that lacks its
GENERATED marker: a hand-written docs/qa/README.md is refused (exit 1), not
replaced. Every diagram is drawn from declared data -- an environment nobody
declared is drawn as missing, never inferred.

Usage: qa_doc.py [--root DIR] [--write]
Exit: 0 printed or written; 1 a file was refused; 2 usage.
"""
import argparse
import datetime
import html
import os
import re
import subprocess
import sys

import qa_audit
import qa_audit_env

GENERATED = "generated by crew qa_doc.py"
MD_PATH = os.path.join("docs", "qa", "README.md")
HTML_PATH = os.path.join("docs", "qa", "qa-process.html")
GATES_MMD = os.path.join("docs", "diagrams", "process-qa-gates.mmd")
LADDER_MMD = os.path.join("docs", "diagrams", "process-qa-ladder.mmd")
MERMAID_CDN = "https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js"
MAX_RULE_ROWS = 40


def _git(root, *args):
    try:
        out = subprocess.run(["git", "-C", root, *args], capture_output=True, text=True,
                             timeout=30, check=False)
    except (OSError, subprocess.SubprocessError):
        return None
    return out.stdout.strip() if out.returncode == 0 else None


def _label(text):
    """A Mermaid node label: quoted, with the characters Mermaid parses escaped."""
    return '"' + str(text).replace('"', "#quot;").replace("\n", " ")[:80] + '"'


def _node_id(name):
    return "env_" + re.sub(r"\W", "_", name)


def _cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ")


def _commands(env, key):
    return qa_audit_env.as_list(env.get(key))


def ladder_diagram(envs):
    """The promotion ladder: one node per declared environment, edges from
    `requires` (or `promotesTo`), each node naming the gates it declares."""
    lines = ["flowchart LR", '  merge(["merge to the default branch"])']
    if not envs:
        lines.append('  none["no environments declared in .crew/verify.json<br/>'
                     'merge is the last gate"]:::gap')
        lines.append("  merge --> none")
    has_parent = set()
    for name, env in envs.items():
        gates = [k for k in ("deploy", "smoke", "regression", "verify") if _commands(env, k)]
        missing = [k for k in ("smoke", "regression") if not _commands(env, k)]
        extra = []
        if env.get("soakMinutes"):
            extra.append(f"soak {env.get('soakMinutes')} min")
        if env.get("requireHuman"):
            extra.append("human approval")
        text = f"<b>{name}</b><br/>{' > '.join(gates) or 'no gates declared'}"
        if extra:
            text += "<br/>" + ", ".join(extra)
        if missing:
            text += "<br/>missing: " + ", ".join(missing)
        css = ":::gap" if missing or not gates else ""
        lines.append(f"  {_node_id(name)}[{_label(text)}]{css}")
    edges = []
    for name, env in envs.items():
        edges += [(parent, name) for parent in qa_audit_env.as_list(env.get("requires")) if parent in envs]
        child = env.get("promotesTo")
        if isinstance(child, str) and child in envs:
            edges.append((name, child))
    for parent, child in dict.fromkeys(edges):  # `requires` and `promotesTo` often say the same edge
        lines.append(f"  {_node_id(parent)} -->|promote| {_node_id(child)}")
        has_parent.add(child)
    for name in envs:
        if name not in has_parent:
            lines.append(f"  merge --> {_node_id(name)}")
    lines.append("  classDef gap stroke:#c0392b,stroke-width:2px,stroke-dasharray:4 3")
    return "\n".join(lines)


def gates_diagram(vmap_state, rules, ci_names, rows):
    """How a change is checked, from edit to merge, with the audit loop beside it."""
    gaps = sum(r["status"] == qa_audit.GAP for r in rows)
    unknown = sum(r["status"] == qa_audit.UNKNOWN for r in rows)
    stop = (f"Stop gate<br/>{len(rules)} rule(s) in .crew/verify.json" if vmap_state == "ok"
            else "Stop gate<br/>no .crew/verify.json: falls back to _verify/smoke.sh")
    ci = f"CI<br/>{len(ci_names)} workflow file(s)" if ci_names else "CI<br/>none found"
    lines = [
        "flowchart TD",
        f'  edit(["change"]) --> stop[{_label(stop)}]',
        '  stop -->|red| fix["fix and re-run"] --> stop',
        '  stop -->|green| review["review<br/>(/crew:review)"]',
        f"  review --> ci[{_label(ci)}]",
        '  ci -->|red| fix',
        '  ci -->|green| merge(["merge"])',
        '  merge --> ladder["promotion ladder<br/>(see the ladder diagram)"]',
        '  subgraph audit ["QA audit (report-only)"]',
        '    direction TB',
        '    trig["session start: qaAuditStale"] --> run["qa_audit.py --root ."]',
        f'    run --> result[{_label(f"{gaps} GAP, {unknown} UNKNOWN")}]',
        '    result --> act["fix one GAP through the gate,<br/>or record why not in .crew/STATUS.md"]',
        '    act --> stamp["qa_audit.py --stamp"]',
        "  end",
    ]
    if not ci_names:
        lines.append("  class ci gap")
    if vmap_state != "ok":
        lines.append("  class stop gap")
    lines.append("  classDef gap stroke:#c0392b,stroke-width:2px,stroke-dasharray:4 3")
    return "\n".join(lines)


def collect(root):
    state, vmap = qa_audit_env.load_map(root)
    vmap = vmap or {}
    envs = qa_audit_env.environments(vmap)
    rules = [r for r in vmap.get("rules") or [] if isinstance(r, dict)]
    ci = qa_audit.ci_files(root)
    rows = qa_audit.audit(root)
    sha = _git(root, "rev-parse", "--short=8", "HEAD") or "unknown"
    return {
        "repo": os.path.basename(os.path.abspath(root)), "sha": sha,
        "date": datetime.date.today().isoformat(), "state": state, "envs": envs,
        "rules": rules, "ci": [rel for rel, _ in ci], "rows": rows,
        "gates": gates_diagram(state, rules, [rel for rel, _ in ci], rows),
        "ladder": ladder_diagram(envs),
    }


def _sections(data):
    """(heading, markdown body, diagram or None) in page order, shared by both renderers."""
    rows = data["rows"]
    counts = {s: sum(r["status"] == s for r in rows)
              for s in (qa_audit.GAP, qa_audit.UNKNOWN, qa_audit.PASS, qa_audit.NA)}
    summary = ("| Item | Value |\n|---|---|\n"
               f"| Commit | `{data['sha']}` |\n| Generated | {data['date']} |\n"
               f"| Verify map | {data['state']} ({len(data['rules'])} rule(s)) |\n"
               f"| Environments | {', '.join(data['envs']) or 'none declared'} |\n"
               f"| CI files | {', '.join(f'`{c}`' for c in data['ci']) or 'none found'} |\n"
               f"| Audit | {counts['GAP']} GAP, {counts['UNKNOWN']} UNKNOWN, {counts['PASS']} PASS, "
               f"{counts['N/A']} N/A |\n")
    out = [("Summary", summary, None)]
    out.append(("How a change is checked",
                "Every change passes the Stop gate, review and CI before it merges. The QA audit runs "
                "beside that loop: it never blocks, it reports. Dashed red boxes are gaps.", data["gates"]))
    env_table = "| Environment | Deploy | Smoke | Regression | Verify | Rollback | Data |\n" \
                "|---|---|---|---|---|---|---|\n"
    for name, env in data["envs"].items():
        cells = [", ".join(f"`{c}`" for c in _commands(env, k)) or "**none**"
                 for k in ("deploy", "smoke", "regression", "verify")]
        rollback = env.get("rollback") or "**none declared**"
        data_from = env.get("dataProvenance") or ("production" if qa_audit_env.is_production(name, env)
                                                  else "**not declared**")
        env_table += f"| {name} | " + " | ".join(_cell(c) for c in cells) \
            + f" | {_cell(rollback)} | {_cell(data_from)} |\n"
    if not data["envs"]:
        env_table = ("No `environments` block in `.crew/verify.json`. Merging is the last gate this "
                     "repository declares; `/crew:init --phase 8` adds one.\n")
    out.append(("Promotion ladder", env_table, data["ladder"]))
    rule_table = "| # | Paths | Runs | Reach | Seconds |\n|---|---|---|---|---|\n"
    for i, rule in enumerate(data["rules"][:MAX_RULE_ROWS]):
        paths = ", ".join(f"`{p}`" for p in qa_audit_env.as_list(rule.get("paths"))[:4])
        runs = "<br/>".join(f"`{c[:70]}`" for c in _commands(rule, "run")[:3])
        rule_table += (f"| {i} | {_cell(paths)} | {_cell(runs)} | {rule.get('reach', '**missing**')} | "
                       f"{rule.get('seconds', '**missing**')} |\n")
    if len(data["rules"]) > MAX_RULE_ROWS:
        rule_table += f"\n{len(data['rules']) - MAX_RULE_ROWS} more rule(s) in `.crew/verify.json`.\n"
    if not data["rules"]:
        rule_table = "No path rules declared.\n"
    out.append(("Gate rules", rule_table, None))
    order = {qa_audit.GAP: 0, qa_audit.UNKNOWN: 1, qa_audit.PASS: 2, qa_audit.NA: 3}
    audit_table = "| Rule | Status | Check | Evidence |\n|---|---|---|---|\n" + "".join(
        f"| {r['rule']} | {r['status']} | {_cell(r['title'])} | {_cell(r['evidence'])} |\n"
        for r in sorted(rows, key=lambda r: order.get(r["status"], 9)))
    out.append(("QA audit findings", "UNKNOWN means the audit could not tell. It is not a pass.\n\n"
                + audit_table, None))
    out.append(("Keeping this page current",
                "This page is generated. Edit `.crew/verify.json`, `_verify/` or CI, then re-run:\n\n"
                "```bash\npython3 ${CLAUDE_PLUGIN_ROOT}/skills/crew-qa-standards/scripts/qa_doc.py "
                "--root . --write\n```\n\nThe diagram sources are `docs/diagrams/process-qa-gates.mmd` and "
                "`docs/diagrams/process-qa-ladder.mmd`.\n", None))
    return out


def render_markdown(data):
    parts = [f"<!-- {GENERATED}; edit the inputs, not this file -->",
             f"# QA process: {data['repo']}", ""]
    for heading, body, diagram in _sections(data):
        parts += [f"## {heading}", "", body.rstrip(), ""]
        if diagram:
            parts += ["```mermaid", diagram, "```", ""]
    return "\n".join(parts)


def _md_inline(text):
    text = html.escape(text, quote=False)
    text = re.sub(r"`([^`]+)`", r"<code>\1</code>", text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", text)
    return text.replace("&lt;br/&gt;", "<br/>").replace("\\|", "|")


def _md_block_to_html(body):
    """The small Markdown subset _sections emits: tables, paragraphs, one fenced block."""
    out, lines, i = [], body.split("\n"), 0
    while i < len(lines):
        line = lines[i]
        if line.startswith("```"):
            j = i + 1
            while j < len(lines) and not lines[j].startswith("```"):
                j += 1
            out.append("<pre><code>" + html.escape("\n".join(lines[i + 1:j])) + "</code></pre>")
            i = j + 1
        elif line.startswith("|"):
            j = i
            while j < len(lines) and lines[j].startswith("|"):
                j += 1
            cells = [re.split(r"(?<!\\)\|", r.strip()[1:-1]) for r in lines[i:j]]
            head = "".join(f"<th>{_md_inline(c.strip())}</th>" for c in cells[0])
            body_rows = "".join("<tr>" + "".join(f"<td>{_md_inline(c.strip())}</td>" for c in r) + "</tr>"
                                for r in cells[2:])
            out.append(f"<div class=\"scroll\"><table><thead><tr>{head}</tr></thead>"
                       f"<tbody>{body_rows}</tbody></table></div>")
            i = j
        elif line.strip():
            out.append(f"<p>{_md_inline(line)}</p>")
            i += 1
        else:
            i += 1
    return "\n".join(out)


def render_html(data):
    sections = []
    for heading, body, diagram in _sections(data):
        block = f"<section><h2>{html.escape(heading)}</h2>\n{_md_block_to_html(body)}"
        if diagram:
            block += f'\n<pre class="mermaid">{html.escape(diagram)}</pre>'
        sections.append(block + "</section>")
    title = f"QA process: {data['repo']}"
    return f"""<!doctype html>
<!-- {GENERATED}; edit the inputs, not this file -->
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)}</title>
<style>
:root {{ --bg:#ffffff; --fg:#1d1d1f; --muted:#5f6368; --line:#d9dce1; --head:#f3f4f6; --gap:#c0392b; }}
@media (prefers-color-scheme: dark) {{
  :root {{ --bg:#16181c; --fg:#e8eaed; --muted:#9aa0a6; --line:#3c4043; --head:#202328; --gap:#ff6b5b; }}
}}
body {{ background:var(--bg); color:var(--fg); font:15px/1.55 system-ui, sans-serif;
       max-width:1100px; margin:0 auto; padding:24px 16px; }}
h1 {{ font-size:1.6rem; margin:0 0 4px; }} h2 {{ font-size:1.2rem; margin:32px 0 8px; }}
p {{ color:var(--muted); }} code {{ font-size:.88em; }}
.scroll {{ overflow-x:auto; }}
table {{ border-collapse:collapse; width:100%; font-size:.9rem; }}
th, td {{ border:1px solid var(--line); padding:6px 8px; text-align:left; vertical-align:top; }}
th {{ background:var(--head); }}
pre {{ overflow-x:auto; }} pre.mermaid {{ background:transparent; text-align:center; }}
</style></head><body>
<h1>{html.escape(title)}</h1>
<p>Generated from <code>{html.escape(data['sha'])}</code> on {data['date']}. Diagrams need the Mermaid
script below; offline, their source text shows instead.</p>
{chr(10).join(sections)}
<script src="{MERMAID_CDN}"></script>
<script>if (window.mermaid) {{ mermaid.initialize({{ startOnLoad: true, securityLevel: "strict",
  theme: matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "default" }}); }}</script>
</body></html>
"""


def render_mmd(data, diagram, anchors):
    present = [a for a in anchors if a]
    return (f"%% anchor: {data['repo']}@{data['sha']}\n"
            f"%% Anchors: {', '.join(present) or '.crew/verify.json'}\n"
            f"%% {GENERATED} on {data['date']}. Verify before trusting.\n{diagram}\n")


def outputs(root):
    data = collect(root)
    anchors = [".crew/verify.json" if data["state"] != "absent" else ""] + data["ci"]
    return {
        MD_PATH: render_markdown(data),
        HTML_PATH: render_html(data),
        GATES_MMD: render_mmd(data, data["gates"], anchors),
        LADDER_MMD: render_mmd(data, data["ladder"], anchors[:1]),
    }


def write(root, files):
    """Write each file whose current copy is absent or carries GENERATED.
    Returns (written, refused)."""
    written, refused = [], []
    for rel, text in files.items():
        path = os.path.join(root, rel)
        current = qa_audit_env.read_text(path)
        if current is not None and GENERATED not in current:
            refused.append(rel)
            continue
        os.makedirs(os.path.dirname(path), exist_ok=True)
        tmp = path + ".tmp"
        with open(tmp, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        os.replace(tmp, path)
        written.append(rel)
    return written, refused


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", default=".")
    parser.add_argument("--write", action="store_true", help="write the files (default: dry run)")
    args = parser.parse_args(argv)
    if not os.path.isdir(args.root):
        parser.error(f"--root {args.root!r} is not a directory")
    root = os.path.abspath(args.root)
    files = outputs(root)
    if not args.write:
        for rel, text in files.items():
            print(f"would write {rel} ({len(text.splitlines())} lines)")
        print("dry run: nothing written; re-run with --write")
        return 0
    written, refused = write(root, files)
    for rel in written:
        print(f"wrote {rel}")
    for rel in refused:
        print(f"REFUSED {rel}: it exists and is not marked '{GENERATED}' -- move it aside or "
              "merge by hand", file=sys.stderr)
    return 1 if refused else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
