"""T-0045 `crew_ghdeploy.py check` mutations, in `sabotage.py`'s tuple shape.

NOT yet wired into `sabotage.py`: `scripts/check-tooling-pr.py` (owner rule,
T-0087) makes `plugin/crew/tests/sabotage*.py` harness, and a harness change
may not ride in a feature PR. L-0650, a tooling-only PR, appends
`GHDEPLOY_MUTATIONS` to `sabotage.py`'s MUTATIONS. Until then run them with
sabotage.py's own machinery:

    cd plugin/crew/tests && python3 -c "import sabotage, ghdeploy_mutations as m; \
        sabotage.MUTATIONS = m.GHDEPLOY_MUTATIONS; raise SystemExit(sabotage.main())"

One entry per refusing branch of `check` (exit 2 and exit 3), each naming the
must-block case that has to go red, then the must-allow non-vacuity entries:
an allow path broken in a way the must-allow cases have to catch.
"""
import os

CREW = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GH = os.path.join(CREW, "hooks", "scripts", "crew_ghdeploy.py")
_T = "tests/test_crew_ghdeploy.py::"
_P = _T + "test_entry_problem[{}]"
_C = _T + "test_check_applies_the_gates_union_rule[{}]"
_S = _T + "test_simulate_gate_agrees_with_the_real_gate[map{}-sh]"
_R = _T + "test_prepare_refuses[{}]"
_I = _T + "test_identify_could_not_tell[{}]"
_W = _T + "test_watch_verdict[{}]"

GHDEPLOY_MUTATIONS = (
    # --- exit 2: entry problems -------------------------------------------
    ("ghdeploy: `github` may be an empty list", GH,
     "isinstance(github, list) and github and all(",
     "isinstance(github, list) and all(",
     _P.format("github empty list")),
    ("ghdeploy: a `github` list may hold a non-object", GH,
     "and all(isinstance(e, dict) for e in github):",
     "and True:",
     _P.format("github list holding a string")),
    ("ghdeploy: a `github` string reads as an entry", GH,
     '    raise Refused("github-shape", ',
     '    return [github]\n    raise Refused("github-shape", ',
     _P.format("github a string")),
    ("ghdeploy: an unknown key is ignored", GH,
     "    if unknown:\n", "    if False:\n",
     _P.format("unknown key")),
    ("ghdeploy: a missing workflow is not named", GH,
     '    if "workflow" not in entry:\n', "    if False:\n",
     _P.format("workflow missing")),
    ("ghdeploy: a workflow display name is accepted", GH,
     "WORKFLOW.fullmatch(workflow) is None:", "False:",
     _P.format("workflow display name")),
    ("ghdeploy: a missing ref is not named", GH,
     '    if "ref" not in entry:\n', "    if False:\n",
     _P.format("ref missing")),
    ("ghdeploy: a ref starting with - is accepted", GH,
     '    if ref.startswith("-"):\n', "    if False:\n",
     _P.format("ref leading dash")),
    ("ghdeploy: a ref holding .. is accepted", GH,
     '    if ".." in ref:\n', "    if False:\n",
     _P.format("ref dotdot")),
    ("ghdeploy: a refs/ path other than refs/heads/ is accepted", GH,
     '(low.startswith("refs/") and not ref.startswith("refs/heads/"))', "False",
     _P.format("ref tag")),
    ("ghdeploy: the refs/ check is case-sensitive", GH,
     '(low.startswith("refs/")', '(ref.startswith("refs/")',
     _P.format("ref tag upper case")),
    ("ghdeploy: HEAD is accepted as a ref", GH,
     'if low == "head" or (', "if False or (",
     _P.format("ref HEAD")),
    ("ghdeploy: a ref starting with @ is accepted", GH,
     '    if ref.startswith("@"):\n', "    if False:\n",
     _P.format("ref leading @")),
    ("ghdeploy: a ref holding : is accepted", GH,
     '    if ":" in ref or ', "    if ",
     _P.format("ref colon")),
    ("ghdeploy: a ref starting with / is accepted", GH,
     ' or "" in parts or ', " or ",
     _P.format("ref leading slash")),
    ("ghdeploy: a ref ending with / is accepted", GH,
     ' or "" in parts or ', " or ",
     _P.format("ref trailing slash")),
    ("ghdeploy: a ref holding // is accepted", GH,
     ' or "" in parts or ', " or ",
     _P.format("ref double slash")),
    ("ghdeploy: a ref ending with . is accepted", GH,
     ' or ref.endswith(".")', "",
     _P.format("ref trailing dot")),
    ("ghdeploy: a ref component starting with . is accepted", GH,
     'part.startswith(".") or ', "",
     _P.format("ref component leading dot")),
    ("ghdeploy: a ref component ending .lock is accepted", GH,
     ' or part.endswith(".lock")', "",
     _P.format("ref .lock")),
    ("ghdeploy: a ref outside the value grammar is accepted", GH,
     "    if not _fits(ref):\n", "    if False:\n",
     _P.format("ref space")),
    ("ghdeploy: `inputs` that is not an object is not named", GH,
     "    if not isinstance(inputs, dict):\n", "    if False:\n",
     _P.format("inputs not object")),
    ("ghdeploy: an input name outside the grammar is accepted", GH,
     "        if NAME.fullmatch(name) is None:\n", "        if False:\n",
     _P.format("input name bad")),
    ("ghdeploy: a non-string input value is not named", GH,
     "        if not isinstance(value, str):\n", "        if False:\n",
     _P.format("input value not string")),
    ("ghdeploy: an input value with $( is accepted", GH,
     "        if not _fits(value):\n", "        if False:\n",
     _P.format("input value with $(")),
    ("ghdeploy: two input names may differ only in case", GH,
     "    if len(names) != len(inputs):\n", "    if False:\n",
     _P.format("input names equal by case")),
    ("ghdeploy: an explicit null shaInput reads as absent", GH,
     "        if key in entry and (", "        if entry.get(key) is not None and (",
     _P.format("shaInput null")),
    ("ghdeploy: shaInput collides with an input only by exact case", GH,
     "names = {name.lower() for name in inputs}", "names = set(inputs)",
     _P.format("shaInput in inputs by case")),
    ("ghdeploy: shaInput equals correlationInput only by exact case", GH,
     'corr = entry.get("correlationInput", "").lower()',
     'corr = entry.get("correlationInput", "")',
     _P.format("shaInput equals correlationInput by case")),
    ("ghdeploy: shaInput may also be a fixed input", GH,
     "    if sha and sha in names:\n", "    if False:\n",
     _P.format("shaInput also in inputs")),
    ("ghdeploy: shaInput may equal correlationInput", GH,
     "    if corr and corr == sha:\n", "    if False:\n",
     _P.format("shaInput equals correlationInput")),
    ("ghdeploy: correlationInput may also be a fixed input", GH,
     "    if corr and corr in names:\n", "    if False:\n",
     _P.format("correlationInput also in inputs")),
    ("ghdeploy: a deployJob with a control character is accepted", GH,
     "ord(c) < 32 or 127", "127",
     _P.format("deployJob control char")),
    ("ghdeploy: a deployJob with DEL or a C1 control is accepted", GH,
     "127 <= ord(c) <= 159 or ", "",
     _P.format("deployJob DEL")),
    ("ghdeploy: a deployJob with a Unicode line separator is accepted", GH,
     ' or c in "\\u2028\\u2029"', "",
     _P.format("deployJob line separator")),
    ("ghdeploy: the upper bound of a range is dropped", GH,
     "or not low <= value <= high:", "or not low <= value:",
     _P.format("watchMinutes 361")),
    ("ghdeploy: the lower bound of a range is dropped", GH,
     "or not low <= value <= high:", "or not value <= high:",
     _P.format("watchMinutes 0")),
    ("ghdeploy: a bool reads as an integer", GH,
     "if isinstance(value, bool) or not isinstance(value, int)",
     "if not isinstance(value, int)",
     _P.format("watchMinutes bool")),
    ("ghdeploy: an env name outside the grammar goes into the correlation id", GH,
     "and not _fits(env):", "and False:",
     _T + "test_correlation_needs_an_env_name_in_the_value_grammar"),
    ("ghdeploy: `deploy` may carry a string that is no entry's prefix", GH,
     "or set(declared) != wanted:", "or not wanted <= set(declared):",
     _T + "test_check_refuses_deploy_prefix_mismatch"),
    ("ghdeploy: `deploy` may miss an entry's prefix", GH,
     "or set(declared) != wanted:", "or not set(declared) <= wanted:",
     _T + "test_check_refuses_deploy_prefix_mismatch"),
    ("ghdeploy: a detail line prints the environment name raw", GH,
     'f"{env!r} github[{index}]: ', 'f"{env} github[{index}]: ',
     _T + "test_an_env_name_is_never_printed_raw"),
    # --- the gate simulation: L-1503's one rule (gate_matches, gate_problem)
    ("ghdeploy: the simulation takes the first match, not the union", GH,
     "for dep in _deploys(cfg))]", "for dep in _deploys(cfg))][:1]",
     _C.format("inputless staging before production")),
    ("ghdeploy: the simulation is case-sensitive", GH,
     '    return "".join(c.upper() if len(c.upper()) == 1 else c for c in text)',
     "    return text",
     _C.format("qa/Prod before production/prod")),
    ("ghdeploy: the simulation drops `cmd in d`", GH,
     " or fold(command) in fold(dep)", "",
     _C.format("inputless staging before production")),
    ("ghdeploy: the simulation drops `d in cmd`", GH,
     "fold(dep) in fold(command) or ", "",
     _C.format("plain deploy contained in a dispatch")),
    ("ghdeploy: the simulation keeps CRs the gates strip", GH,
     '    command = command.replace("\\r", "").rstrip("\\n")',
     '    command = command.rstrip("\\n")',
     _S.format(28)),
    ("ghdeploy: the simulation keeps trailing newlines", GH,
     '    command = command.replace("\\r", "").rstrip("\\n")',
     '    command = command.replace("\\r", "")',
     _S.format(25)),
    ("ghdeploy: a blank command still matches", GH,
     "    if _blank(command):\n        return []\n", "",
     _S.format(25)),
    ("ghdeploy: an empty deploy string matches every command", GH,
     "if any(dep and _matches(", "if any(_matches(",
     _S.format(13)),
    ("ghdeploy: keys equal or equal ignoring case are accepted", GH,
     "        if folds & seen:\n", "        if False:\n",
     _C.format("keys differing only by case")),
    ("ghdeploy: a refused map crashes check instead of refusing", GH,
     "    except _MapRefused as exc:\n        raise Refused(",
     "    except KeyError as exc:\n        raise Refused(",
     _C.format("an exact duplicate key")),
    ("ghdeploy: PowerShell-only JSON crashes the simulation", GH,
     '    except ValueError as exc:\n        raise _MapRefused(f"not JSON',
     '    except KeyError as exc:\n        raise _MapRefused(f"not JSON',
     _S.format(22)),
    ("ghdeploy: a comma in an environment name is accepted", GH,
     'if "," in name or ', "if ",
     _C.format("a comma in an environment name")),
    ("ghdeploy: a control character in an environment name is accepted", GH,
     'any(unicodedata.category(c) == "Cc" for c in name):', "False:",
     _C.format("a newline in an environment name")),
    ("ghdeploy: an environment that is not an object is accepted", GH,
     "        if not isinstance(cfg, dict):\n            return f", "        if False:\n            return f",
     _C.format("an environment that is not an object elsewhere")),
    ("ghdeploy: a list or object requireHuman is accepted", GH,
     'isinstance(_get_ci(cfg, "requireHuman", None), (list, dict))', "False",
     _C.format("a list requireHuman elsewhere")),
    ("ghdeploy: a null deploy is accepted", GH,
     "        if _deploys(cfg) is None:\n", "        if False:\n",
     _C.format("a numeric deploy elsewhere")),
    ("ghdeploy: the `deploy` key is read case-sensitively", GH,
     '    declared = _get_ci(cfg, "deploy", [])', '    declared = cfg.get("deploy", [])',
     _C.format("a Deploy key on another environment")),
    ("ghdeploy: the `environments` key is read case-sensitively", GH,
     '_get_ci(doc, "environments", None) if', 'doc.get("environments") if',
     _C.format("an upper-case DEPLOY key and Environments on the github one")),
    ("ghdeploy: check reads a map the gates refuse", GH,
     '    if problem:\n        raise Refused("gate-refuses-map", "a promote',
     '    if False:\n        raise Refused("gate-refuses-map", "a promote',
     _C.format("a comma in an environment name")),
    ("ghdeploy: `gated-as` names only this environment", GH,
     "f\"gated-as: {','.join(gate_matches(command, envs))!r}\"", 'f"gated-as: {env!r}"',
     _T + "test_check_names_the_union_and_says_it_is_one"),
    # --- re-review FIX-1 / NIT1: either gate refuses; match with the union
    ("ghdeploy: an empty key is accepted", GH,
     '        if key == "":\n', "        if False:\n",
     _C.format("an empty key inside an environment (ps1 refuses)")),
    ("ghdeploy: twin keys only under .NET's fold are accepted", GH,
     'folds = {("py", _fold(key)), ("net", _dotnet_fold(key))}',
     'folds = {("py", _fold(key))}',
     _C.format("iota-subscript twin names (ps1 refuses)")),
    ("ghdeploy: twin keys only under Python's fold are accepted", GH,
     'folds = {("py", _fold(key)), ("net", _dotnet_fold(key))}',
     'folds = {("net", _dotnet_fold(key))}',
     _C.format("dotless-i twin names (sh refuses)")),
    ("ghdeploy: the .NET-only fold table is empty", GH,
     "_DOTNET_ONLY_FOLDS = {chr(low): chr(low + 8) for low in",
     "_DOTNET_ONLY_FOLDS = {chr(low): chr(low + 8) for low in [] and",
     _T + "test_the_dotnet_only_fold_table_is_pinned"),
    ("ghdeploy: a date-time deploy string is a command", GH,
     "isinstance(d, str) and not _is_dotnet_date(d) for d in declared",
     "isinstance(d, str) for d in declared",
     _C.format("a date-time deploy elsewhere (ps1 refuses)")),
    ("ghdeploy: the ISO date port ignores the zone", GH,
     "    return pos == end\n", "    return True\n",
     _T + "test_is_dotnet_date_is_what_convertfrom_json_converts[2026-10-04T00:00:00Zx-False]"),
    ("ghdeploy: /Date()/ is not a date", GH,
     '        return (re.fullmatch(r"-?[0-9]+", ticks) is not None\n',
     "        return False and (re.fullmatch(r\"-?[0-9]+\", ticks) is not None\n",
     _C.format("a /Date()/ deploy elsewhere (ps1 refuses)")),
    ("ghdeploy: /Date()/ ticks past Int64 are a date", GH,
     "and -2 ** 63 <= int(ticks) < 2 ** 63)", ")",
     _T + "test_is_dotnet_date_is_what_convertfrom_json_converts[/Date(99999999999999999999)/-False]"),
    ("ghdeploy: matching ignores .NET's fold", GH,
     "               for fold in (_fold, _dotnet_fold))", "               for fold in (_fold,))",
     _T + "test_simulate_gate_refuses_when_either_gate_refuses[either9]"),
    ("ghdeploy: no fixed nesting bound (re-review CI)", GH,
     "    if _depth(text) > _MAX_DEPTH:\n", "    if False:\n",
     _T + "test_nesting_past_a_fixed_bound_is_refused_on_every_interpreter[201-True]"),
    ("ghdeploy: the bound is off by one", GH,
     "    if _depth(text) > _MAX_DEPTH:\n", "    if _depth(text) >= _MAX_DEPTH:\n",
     _T + "test_nesting_past_a_fixed_bound_is_refused_on_every_interpreter[200-False]"),
    ("ghdeploy: the depth scan counts brackets inside strings", GH,
     "        elif char == '\"':\n            in_string = True\n", "",
     _T + "test_depth_skips_brackets_inside_strings"),
    ("ghdeploy: the depth scan ignores escapes", GH,
     "                escaped = True\n", "                pass\n",
     _T + "test_depth_skips_brackets_inside_strings"),
    ("ghdeploy: an unencodable name in a message crashes check on cp1252", GH,
     'sys.stdout.reconfigure(errors="backslashreplace")', 'sys.stdout.reconfigure(errors="strict")',
     _T + "test_a_non_ascii_name_in_a_message_survives_a_cp1252_stdout"),
    # --- exit 3: could-not-tell -------------------------------------------
    ("ghdeploy: an absent map is not named as absent", GH,
     "    if not os.path.lexists(path):\n", "    if False:\n",
     _T + "test_check_unreadable_map_is_could_not_tell"),
    ("ghdeploy: an unparseable map crashes instead of could-not-tell", GH,
     "    except ValueError as exc:\n        raise CouldNotTell(",
     "    except KeyError as exc:\n        raise CouldNotTell(",
     _T + "test_check_unreadable_map_is_could_not_tell"),
    ("ghdeploy: `environments` that is not an object is not named", GH,
     "    if not isinstance(envs, dict):\n        raise CouldNotTell(",
     "    if False:\n        raise CouldNotTell(",
     _T + "test_check_unreadable_map_is_could_not_tell"),
    ("ghdeploy: a missing environment is not named", GH,
     "    if env not in envs:\n", "    if False:\n",
     _T + "test_check_unreadable_map_is_could_not_tell"),
    ("ghdeploy: an environment that is not an object is not named", GH,
     "    if not isinstance(envs[env], dict):\n", "    if False:\n",
     _T + "test_check_unreadable_map_is_could_not_tell"),
    ("ghdeploy: an unreadable HEAD prints a dispatch anyway", GH,
     '    if proc.returncode != 0 or re.fullmatch(r"[0-9a-f]{40}", sha) is None:\n',
     "    if False:\n",
     _T + "test_check_unreadable_map_is_could_not_tell"),
    ("ghdeploy: check runs gh", GH,
     "    sha = _head(root)\n",
     '    subprocess.run(["gh", "api", "user"], check=False, capture_output=True)\n'
     "    sha = _head(root)\n",
     _T + "test_check_calls_no_gh"),
    # --- must-allow non-vacuity -------------------------------------------
    ("ghdeploy: the prefix sorts inputs instead of keeping their order", GH,
     'for name, value in entry.get("inputs", {}).items():',
     'for name, value in sorted(entry.get("inputs", {}).items()):',
     _T + "test_prefix_is_listed_order"),
    ("ghdeploy: the correlation id goes before the sha", GH,
     "    if entry.get(\"shaInput\"):\n        line +=",
     "    if entry.get(\"correlationInput\"):\n        line += ' -f c=x'\n"
     "    if entry.get(\"shaInput\"):\n        line +=",
     _T + "test_dispatch_appends_sha_then_correlation"),
    ("ghdeploy: the printed dispatch no longer carries the deploy prefix", GH,
     "    line = prefix(entry)\n",
     '    line = prefix(entry).replace(" --ref ", " -r ")\n',
     _T + "test_dispatch_matches_promote_gate"),
    # --- prepare (L-0644): one per refusing branch, then must-allow ---------
    ("ghdeploy prepare: an environment with no github entry is let through", GH,
     '        raise Refused("github-none", f"environment {env!r} has no github entry")\n',
     '        return {}\n',
     _T + "test_prepare_refuses_an_environment_without_a_github_entry"),
    ("ghdeploy prepare: an unmapped workflow is treated as mapped", GH,
     "    if klass is None:\n        raise Refused(\"unmapped-workflow\",",
     "    if klass is None:\n        return crew_dispatch.ENV_NONPROD\n        raise Refused(\"unmapped-workflow\",",
     _R.format("unmapped-workflow")),
    ("ghdeploy prepare: an unknown environment is let through", GH,
     "    if problem or klass[0] == crew_dispatch.ENV_UNKNOWN:\n",
     "    if False:\n",
     _R.format("unknown-environment")),
    ("ghdeploy prepare: a class mismatch is let through", GH,
     "    if klass[0] != named:\n",
     "    if False:\n",
     _R.format("class-mismatch")),
    ("ghdeploy prepare: an unreadable actor is let through", GH,
     "    if not isinstance(login, str) or not login or not _fits(login):\n",
     "    if False:\n",
     _R.format("actor-unreadable")),
    ("ghdeploy prepare: a sha missing on the remote is let through", GH,
     '    if not isinstance(remote, dict) or remote.get("sha") != sha:\n',
     '    if False:\n',
     _R.format("sha-not-on-remote")),
    ("ghdeploy prepare: a branch tip that is not HEAD is let through", GH,
     "        if tip != sha:\n",
     "        if False:\n",
     _R.format("branch-tip-not-head")),
    ("ghdeploy prepare: an unreadable snapshot is let through", GH,
     "    if not isinstance(runs, list) or not all(\n",
     "    if False and not all(\n",
     _R.format("snapshot-unreadable")),
    ("ghdeploy prepare: a classifier crash is a pass", GH,
     "        raise Refused(\"classifier-failed\", f\"the dispatch classifier failed: \"\n",
     "        return crew_dispatch.ENV_NONPROD\n        raise Refused(\"classifier-failed\", f\"the dispatch classifier failed: \"\n",
     _T + "test_prepare_classifier_crash_refuses"),
    ("ghdeploy prepare: an environment name may leave the state directory", GH,
     '    if re.fullmatch(r"[A-Za-z0-9_][A-Za-z0-9._-]*", env) is None:\n',
     "    if False:\n",
     _T + "test_prepare_refuses_an_env_name_that_leaves_the_state_dir"),
    ("ghdeploy prepare: the machine layer's corrupt block is ignored", GH,
     "    problem = crew_dispatch._envs_problem(config)",
     "    problem = config.get(\"problem\")",
     _T + "test_prepare_refuses_a_corrupt_machine_environments_block"),
    ("ghdeploy prepare: a full refs/heads/ ref is passed to the branch queries as is", GH,
     '    return ref[len("refs/heads/"):] if ref.startswith("refs/heads/") else ref\n',
     '    return ref\n',
     _T + "test_prepare_and_identify_take_a_full_branch_ref"),
    ("ghdeploy prepare: the state file is written in place", GH,
     "        os.replace(tmp, path)\n",
     "        os.rename(tmp, path)\n",
     _T + "test_prepare_state_is_atomic"),
    ("ghdeploy prepare: the snapshot drops the run ids", GH,
     '             "snapshot": sorted(r["databaseId"] for r in runs),\n',
     '             "snapshot": [],\n',
     _T + "test_nonprod_prepare"),
    # --- identify (L-0645): one per refusing branch, then must-allow ------
    ("ghdeploy identify: a missing state file reads as empty", GH,
     '    if missing:\n        raise CouldNotTell("state-file-missing"',
     '    if False:\n        raise CouldNotTell("state-file-missing"',
     _T + "test_identify_state_file_missing"),
    ("ghdeploy identify: a state file without its keys is used", GH,
     "    if not good:\n        raise CouldNotTell(\"state-file-unreadable\"",
     "    if False:\n        raise CouldNotTell(\"state-file-unreadable\"",
     _T + "test_identify_state_file_unreadable"),
    ("ghdeploy identify: a stale prepare is used", GH,
     '    if start - state["t0"] > STALE_SECONDS:\n',
     "    if False:\n",
     _T + "test_identify_stale_prepare"),
    ("ghdeploy identify: the newest of two candidates is picked", GH,
     "            if len(candidates) > 1:\n",
     "            candidates = candidates[-1:]\n            if len(candidates) > 1:\n",
     _I.format("two-candidates")),
    ("ghdeploy identify: a run in the snapshot is a candidate", GH,
     '        if run["databaseId"] in seen or run.get("event")',
     '        if run.get("event")',
     _I.format("old-run-only")),
    ("ghdeploy identify: a run on another branch is a candidate", GH,
     '                or run.get("headBranch") != branch(state["ref"]):\n',
     '                or False:\n',
     _I.format("wrong-branch")),
    ("ghdeploy identify: a push run is a candidate", GH,
     ' or run.get("event") != "workflow_dispatch" \\\n',
     ' or False \\\n',
     _I.format("wrong-event")),
    ("ghdeploy identify: the time window is ignored", GH,
     '        if created < state["t0"] - SKEW_SECONDS:\n            continue\n',
     '',
     _I.format("outside-the-window")),
    ("ghdeploy identify: a run without the correlation id is a candidate", GH,
     '        if corr and corr not in str(run.get("displayTitle", "")):\n',
     '        if False:\n',
     _I.format("correlation-not-found")),
    ("ghdeploy identify: an unparseable createdAt is skipped", GH,
     '        if created is None:\n            raise CouldNotTell("created-unparseable",',
     '        if created is None:\n            continue\n            raise CouldNotTell("created-unparseable",',
     _I.format("created-unparseable")),
    ("ghdeploy identify: a createdAt with no zone is read as local time", GH,
     "    return when.timestamp() if when.tzinfo is not None else None\n",
     "    return when.timestamp()\n",
     _I.format("created-without-zone")),
    ("ghdeploy identify: a run list that is not runs is no runs", GH,
     '        raise CouldNotTell("run-list-unreadable", "`gh run list` gave no list of runs")\n',
     '        return [], 0\n',
     _I.format("run-list-not-runs")),
    ("ghdeploy identify: run-list failures are not named", GH,
     '    if not answered:\n',
     '    if False:\n',
     _I.format("run-list-fails")),
    ("ghdeploy identify: identify stops after one poll", GH,
     '        if poll + 1 == polls or _clock() >= deadline:\n',
     '        if True:\n',
     _T + "test_identify_polls_until_identify_seconds"),
    # --- identify must-allow non-vacuity ------------------------------------
    ("ghdeploy identify: the run id is not written", GH,
     '                state.update(runId=run["databaseId"], runUrl=run.get("url"))\n',
     '                state.update(runUrl=run.get("url"))\n',
     _T + "test_identify_one_new_run"),
    ("ghdeploy identify: a failed poll ends the search", GH,
     '        if runs is not None:\n',
     '        if runs is None:\n            break\n        if runs is not None:\n',
     _T + "test_identify_new_run_after_two_polls"),
    ("ghdeploy identify: the correlation id must be the whole title", GH,
     '        if corr and corr not in str(run.get("displayTitle", "")):\n',
     '        if corr and corr != str(run.get("displayTitle", "")):\n',
     _T + "test_identify_correlation_found"),
    ("ghdeploy identify: no clock skew is allowed", GH,
     '        if created < state["t0"] - SKEW_SECONDS:\n',
     '        if created < state["t0"]:\n',
     _T + "test_identify_clock_skew_within_30s"),
    ("ghdeploy identify: a stale-prepare edge of 600 seconds is stale", GH,
     '    if start - state["t0"] > STALE_SECONDS:\n',
     '    if start - state["t0"] >= STALE_SECONDS:\n',
     _T + "test_identify_at_600_seconds_is_not_stale"),
    # --- watch (L-0646): one per refusing branch, then must-allow ---------
    ("ghdeploy watch: the watch exit code decides", GH,
     "    verdict, reason = judge(view, state)\n",
     "    verdict, reason = judge(view, state)\n"
     "    if watched == 0:\n        verdict, reason = \"pass\", \"success-deploy-job-succeeded\"\n",
     _W.format("watch-exit0-conclusion-failure")),
    ("ghdeploy watch: a non-success conclusion is a pass", GH,
     '    if conclusion != "success":\n',
     "    if False:\n",
     _W.format("cancelled")),
    ("ghdeploy watch: a skipped deploy job passes", GH,
     '        if job.get("conclusion") != "success":\n',
     '        if job.get("conclusion") not in ("success", "skipped"):\n',
     _W.format("deploy-job-skipped")),
    ("ghdeploy watch: an absent deploy job passes", GH,
     "    if not matched:\n",
     "    if False:\n",
     _W.format("deploy-job-absent")),
    ("ghdeploy watch: the head sha is not compared", GH,
     '        if head != state["sha"]:\n',
     "        if False:\n",
     _W.format("headsha-mismatch")),
    ("ghdeploy watch: an unreadable view is a pass", GH,
     '        return "unknown", "view-unreadable"\n',
     '        return "pass", "view-unreadable"\n',
     _W.format("view-not-json")),
    ("ghdeploy watch: unreadable jobs pass", GH,
     '        return "unknown", "jobs-unreadable"\n',
     '        return "pass", "jobs-unreadable"\n',
     _W.format("jobs-unreadable")),
    ("ghdeploy watch: a run still going at the deadline is called again forever", GH,
     '    if reason == "still-running" and _clock() < deadline:\n',
     '    if reason == "still-running":\n',
     _T + "test_watch_timeout_is_unknown_and_never_cancels"),
    ("ghdeploy watch: no run id watches run 0", GH,
     "    if not isinstance(run_id, int) or isinstance(run_id, bool):\n        raise",
     "    if False:\n        raise",
     _T + "test_watch_no_run_id_in_state"),
    ("ghdeploy watch: the slice is not bounded", GH,
     "            if not 1 <= args.slice_seconds <= SLICE_MAX:\n",
     "            if False:\n",
     _T + "test_watch_slice_seconds_range"),
    # --- watch must-allow non-vacuity ---------------------------------------
    ("ghdeploy watch: a slice ending early is a verdict", GH,
     '        return 75, [f"run {run_id} is still running; the slice ended before the deadline",\n',
     '        return 3, [f"run {run_id} is still running; the slice ended before the deadline",\n',
     _T + "test_watch_queued_then_success"),
    ("ghdeploy watch: a missing deployJob is never a pass", GH,
     '        return "pass", "success-deploy-job-not-checked"\n',
     '        return "unknown", "success-deploy-job-not-checked"\n',
     _W.format("no-deploy-job-configured")),
    ("ghdeploy watch: a watch that could not run decides", GH,
     "    verdict, reason = judge(view, state)\n",
     "    verdict, reason = judge(view, state)\n"
     "    if watched not in (0, None):\n        verdict, reason = \"unknown\", \"view-unreadable\"\n",
     _W.format("watch-nonzero-view-success")),
    ("ghdeploy watch: the view is not polled after a failed watch", GH,
     "            and watched not in (None, 124):\n",
     "            and False:\n",
     _T + "test_watch_a_watch_that_cannot_run_polls_the_view"),
    ("ghdeploy watch: the verdict is not written", GH,
     "    state.update(verdict=verdict, verdictReason=reason, watchExit=watched,\n",
     "    state.update(verdictReason=reason, watchExit=watched,\n",
     _W.format("nonprod-happy")),
)
