"""T-0505 promote-gate effective-tree mutations, in `sabotage.py`'s tuple shape.

Wired into `sabotage.py`'s MUTATIONS by C-0046 (harness lane H2b), so the
full run and `test_every_shipped_anchor_is_present_in_its_target_exactly_once`
cover them; `test_ghdeploy_mutations_are_wired` keeps them there. To run this
family alone, with sabotage.py's own machinery:

    cd plugin/crew/tests && python3 -c "import sabotage, promote_tree_mutations as m; \
        sabotage.MUTATIONS = m.PROMOTE_TREE_MUTATIONS; raise SystemExit(sabotage.main())"

Each puts back one way the gate judged the wrong tree, or one neighbour the
fix opened, and names the must-block or must-allow case that has to go red.
The `.ps1` ones target the pwsh-flavour cases, which run wherever PowerShell 7
resolves (see test_promote_gate_effective_tree.py's docstring).
"""
import os

CREW = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_SCRIPTS = os.path.join(CREW, "hooks", "scripts")
SH = os.path.join(_SCRIPTS, "promote-gate.sh")
PS1 = os.path.join(_SCRIPTS, "promote-gate.ps1")
TREE = os.path.join(_SCRIPTS, "_promote_tree.py")
DISPATCH = os.path.join(_SCRIPTS, "_promote_dispatch.py")
REVIEW = os.path.join(_SCRIPTS, "_promote_review.py")
_T = "tests/test_promote_gate_effective_tree.py::"
_D = "tests/test_promote_gate_dispatch.py::"
_R = "tests/test_promote_gate_rows.py::test_the_newest_row_decides"
_M = "tests/test_promote_gate_match.py::"
_V = "tests/test_promote_gate_review.py::"

PROMOTE_TREE_MUTATIONS = (
    # Retargeted after review r1: the dirty-worktree case is now also caught by
    # the check on the tree the deploy RUNS in, which masks this mutation.
    ("promote-gate.sh judges the project dir again, not the deploy's tree", SH,
     '    TREE=$TOP\n',
     '    TREE=$PROJECT_TOP\n',
     _T + "test_a_pass_row_for_the_main_sha_does_not_admit_the_worktree_sha[sh]"),
    ("promote-gate.sh: a dirty main checkout blocks a clean worktree again", SH,
     '    TREE=$TOP\n',
     '    TREE=$PROJECT_TOP\n',
     _T + "test_a_clean_worktree_deploys_while_the_main_checkout_is_dirty[sh]"),
    ("promote-gate.sh accepts a worktree of a different repository", SH,
     'if [ "$TREE_COMMON" != "$PROJECT_COMMON" ]; then\n',
     'if false; then\n',
     _T + "test_a_worktree_of_a_different_repository_blocks[sh]"),
    ("promote-gate.sh lets a literal sha differ from the tree's HEAD", SH,
     '  if [ -n "$RESOLVED" ] && [ "$RESOLVED" != "$FULL" ]; then\n',
     '  if false; then\n',
     _T + "test_a_literal_sha_that_is_not_the_trees_head_blocks[sh]"),
    ("promote-gate.sh lets an uncommitted deploy-map edit become policy", SH,
     'if [ -n "$MAP_DIRTY" ]; then\n',
     'if false; then\n',
     _T + "test_uncommitted_edits_to_the_deploy_map_block[sh]"),
    ("promote-gate.sh ignores a cd after the start of the command", SH,
     '    midcd)\n      block ',
     '    midcd)\n      : ',
     _T + "test_a_cd_after_the_start_of_the_command_blocks[sh]"),
    ("promote-gate.ps1 judges the project dir again, not the deploy's tree", PS1,
     '  if (-not $tree) { $tree = $top }\n',
     '  if (-not $tree) { $tree = $projectTop }\n',
     _T + "test_a_pass_row_for_the_main_sha_does_not_admit_the_worktree_sha[ps1]"),
    ("promote-gate.ps1 accepts a worktree of a different repository", PS1,
     'if ($treeCommon -ne $projectCommon) {\n',
     'if ($false) {\n',
     _T + "test_a_worktree_of_a_different_repository_blocks[ps1]"),
    ("promote-gate.ps1 lets a literal sha differ from the tree's HEAD", PS1,
     '  if ($resolved -and $resolved -ne $full) {\n',
     '  if ($false) {\n',
     _T + "test_a_literal_sha_that_is_not_the_trees_head_blocks[ps1]"),
    ("promote-gate.ps1 ignores a cd after the start of the command", PS1,
     'if ($mid.Success) {\n',
     'if ($false) {\n',
     _T + "test_a_cd_after_the_start_of_the_command_blocks[ps1]"),
    ("_promote_tree.py stops refusing env -C / make -C", TREE,
     '    for m in _TOOLDIR.finditer(command):\n',
     '    for m in _TOOLDIR.finditer(""):\n',
     _T + "test_a_tool_that_changes_directory_is_could_not_tell[sh-env -C {wt} deploy-dev]"),
    ("_promote_tree.py reads a quoted `bash -c 'cd x'` as no directory change", TREE,
     """(?:^|(?<=[\\s;&|(){}'"`]))(?:cd|pushd|popd|chdir)""",
     """(?:^|(?<=[\\s;&|(){}]))(?:cd|pushd|popd|chdir)""",
     _T + "test_a_cd_in_any_other_form_is_could_not_tell[sh-bash -c 'cd {wt} && deploy-qa']"),
    # T-0505 review round 1 (Codex): one mutation per fixed finding.
    ("promote-gate.sh trusts git status for the map again (skip-worktree hides an edit)", SH,
     '  elif [ "$WORK_MAP" != "$HEAD_MAP" ]; then\n',
     '  elif false; then\n',
     _T + "test_skip_worktree_does_not_hide_an_uncommitted_map_edit[sh]"),
    ("promote-gate.sh stops matching a dirty map against the committed one", SH,
     '    pick(matching(committed_envs, strict=False))\n',
     '    pass\n',
     _T + "test_an_uncommitted_rename_of_the_deploy_command_still_blocks[sh]"),
    ("promote-gate.sh reads an uncommitted map deletion as the opt-out", SH,
     '  [ -z "$HEAD_MAP" ] && exit 0\n  MAP_DIRTY="deleted',
     '  exit 0\n  MAP_DIRTY="deleted',
     _T + "test_an_uncommitted_deletion_of_the_map_is_not_an_opt_out[sh]"),
    ("promote-gate.sh lets git -C launder the dirty tree the deploy runs in", SH,
     '[ "$RUN_TOP" != "$TREE" ] && clean_or_block "$RUN_TOP"\n',
     'true\n',
     _T + "test_git_dash_C_does_not_launder_the_dirty_tree_the_deploy_runs_in[sh]"),
    ("promote-gate.sh reads a failed git status as clean", SH,
     '    || block "could not read git status in',
     '    || : "could not read git status in',
     _T + "test_an_unreadable_status_is_not_clean[sh]"),
    ("promote-gate.sh ignores skip-worktree entries in the deployed tree", SH,
     "grep -q '^[a-zS]'",
     "grep -q '^NEVER'",
     _T + "test_skip_worktree_in_the_deployed_tree_blocks[sh]"),
    ("_promote_tree.py reads git -C inside quoted text again", TREE,
     '        if not live[m.start()]:\n',
     '        if False:\n',
     _T + "test_git_forms_outside_the_allowlist_are_could_not_tell"
     "[sh-deploy-dev --note \"x git -C {wt} rev-parse HEAD\"]"),
    ("_promote_tree.py accepts any git global option", TREE,
     '        if expands or text not in _GIT_FLAGS:\n',
     '        if expands:\n',
     _T + "test_git_forms_outside_the_allowlist_are_could_not_tell"
     "[sh-deploy-dev --ref $(git --bare -C {wt} rev-parse HEAD)]"),
    ("_promote_tree.py loses --no-pager from the allowlist", TREE,
     '_GIT_FLAGS = {"--no-pager", ',
     '_GIT_FLAGS = {',
     _T + "test_git_global_options_before_dash_C_still_name_the_tree[sh]"),
    ("promote-gate.ps1 trusts git status for the map again", PS1,
     '  elseif ($workMap -ne $headMap) {',
     '  elseif ($false) {',
     _T + "test_skip_worktree_does_not_hide_an_uncommitted_map_edit[ps1]"),
    ("promote-gate.ps1 lets git -C launder the dirty tree the deploy runs in", PS1,
     'if ($runTop -ne $tree) { Assert-Clean $runTop }\n',
     '\n',
     _T + "test_git_dash_C_does_not_launder_the_dirty_tree_the_deploy_runs_in[ps1]"),
    ("promote-gate.ps1 reads git -C inside quoted text again", PS1,
     '  if (-not $live[$m.Index]) {',
     '  if ($false) {',
     _T + "test_git_forms_outside_the_allowlist_are_could_not_tell"
     "[ps1-deploy-dev --note \"x git -C {wt} rev-parse HEAD\"]"),
    ("promote-gate.ps1 reads a failed git status as clean", PS1,
     '  if ($LASTEXITCODE -ne 0) { Stop-Promotion "could not read git status',
     '  if ($false) { Stop-Promotion "could not read git status',
     _T + "test_an_unreadable_status_is_not_clean[ps1]"),
    ("promote-gate.ps1's leading cd chain is case-sensitive again", PS1,
     "'\\s*(?:&&|;)'), 'IgnoreCase')",
     "'\\s*(?:&&|;)'), 'None')",
     _T + "test_powershell_directory_changes_are_case_insensitive"),
    ("_promote_tree.py lets a git -C outside a substitution name the sha", TREE,
     '            out.append(("Crun" if kind == "C" and not sub[m.start()] else kind, text))\n',
     '            out.append((kind, text))\n',
     _T + "test_git_dash_C_outside_a_substitution_does_not_name_the_sha[sh]"),
    ("promote-gate.ps1 lets a git -C outside a substitution name the sha", PS1,
     '  if ($inSub[$m.Index]) { $trees.Add($dir) } else { $runDirs.Add($dir) }\n',
     '  $trees.Add($dir)\n',
     _T + "test_git_dash_C_outside_a_substitution_does_not_name_the_sha[ps1]"),
    ("promote-gate.sh reads an unreadable committed map as matching nothing", SH,
     '        unreadable(f"the committed .crew/verify.json does not parse as JSON: {exc}", 3)\n',
     '        sys.exit(0)\n',
     _T + "test_an_unreadable_committed_map_is_could_not_tell_while_the_map_is_dirty[sh]"),
    ("promote-gate.ps1 reads an unreadable committed map as matching nothing", PS1,
     '  catch { Deny-UnreadableMap "the committed .crew/verify.json does not parse: $($_.Exception.Message)" }\n',
     '  catch { exit 0 }\n',
     _T + "test_an_unreadable_committed_map_is_could_not_tell_while_the_map_is_dirty[ps1]"),
    # T-0062: promote-gate reads a workflow dispatch with T-0009's reader.
    ("promote-gate.sh no longer reads an unmatched command as a dispatch", SH,
     '  "$PY" "$(dirname "${BASH_SOURCE[0]}")/_promote_dispatch.py" "$CMD") \\\n',
     '  true) \\\n',
     _D + "test_the_rest_spelling_of_a_prod_deploy_is_gated[sh]"),
    ("_promote_dispatch.py does not read a command again without its declared deploys",
     DISPATCH, "        return _decide(rest, shell, maps)\n", "        return []\n",
     _D + "test_a_contained_deploy_does_not_hide_a_second_dispatch[sh-declared-dispatch]"),
    ("promote-gate.sh reads a dispatch only when containment matched nothing", SH,
     'ENVNAME=${ENVNAMES:-workflow dispatch}\n',
     '[ -n "$ENVNAMES" ] && CMD=true\nENVNAME=${ENVNAMES:-workflow dispatch}\n',
     _D + "test_a_contained_deploy_does_not_hide_a_second_dispatch[sh-script]"),
    ("promote-gate.ps1 reads a dispatch only when containment matched nothing", PS1,
     "$envName = if ($envNames.Count -eq 0) { \"workflow dispatch\" } else { $envNames -join ',' }\n",
     "if ($envNames.Count -gt 0) { $cmd = 'true' }\n"
     "$envName = if ($envNames.Count -eq 0) { \"workflow dispatch\" } else { $envNames -join ',' }\n",
     _D + "test_a_contained_deploy_does_not_hide_a_second_dispatch[ps1-script]"),
    ("_promote_dispatch.py reads a dispatch it cannot read as no match", DISPATCH,
     '    if kind == "unsure":\n        raise Block(',
     '    if kind == "unsure":\n        return []\n        raise Block(',
     _D + "test_a_dispatch_the_gate_cannot_read_is_could_not_tell"
     "[sh-gh workflow run deploy.yml -f environment=$E]"),
    ("_promote_dispatch.py picks the environment by workflow alone", DISPATCH,
     '        if scope_inputs.get(name) != value:\n',
     '        if False:\n',
     _D + "test_the_rest_spelling_of_a_dev_deploy_runs[sh]"),
    ("_promote_dispatch.py drops the committed map's declared dispatches", DISPATCH,
     '        ("the committed .crew/verify.json", committed_envs()),\n',
     '        ("the committed .crew/verify.json", None),\n',
     _D + "test_a_dispatch_deploy_removed_from_the_working_map_still_matches[sh]"),
    ("promote-gate.sh reads the dispatch helper's failure as empty output", SH,
     '  || block "the command could not be read as a workflow dispatch',
     '  || true "the command could not be read as a workflow dispatch',
     _D + "test_the_helper_failing_blocks[sh]"),
    # L-0664: promote-gate.ps1 reads a workflow dispatch with the same helper.
    ("promote-gate.ps1 no longer reads an unmatched command as a dispatch", PS1,
     "    $dispatch = @($cmd | & $py (Join-Path $scriptDir '_promote_dispatch.py') --shell powershell -)\n",
     "    $dispatch = @()\n",
     _D + "test_the_rest_spelling_of_a_prod_deploy_is_gated[ps1]"),
    ("promote-gate.ps1 reads the helper's could-not-tell as no match", PS1,
     "    if ($parts[0] -ceq 'block') { Stop-Promotion $parts[1] }\n",
     "    if ($parts[0] -ceq 'block') { continue }\n",
     _D + "test_a_dispatch_the_gate_cannot_read_is_could_not_tell"
     "[ps1-gh workflow run deploy.yml -f environment=$E]"),
    ("promote-gate.ps1 with no python lets a declared dispatch through", PS1,
     "    Stop-Promotion \"python could not be found, so the gate cannot read",
     "    exit 0; Stop-Promotion \"python could not be found, so the gate cannot read",
     _D + "test_ps1_without_python_blocks_a_dispatch_the_map_declares"),
    ("promote-gate.ps1 reads the dispatch helper's failure as empty output", PS1,
     "  if ($dispatchExit -ne 0) {\n",
     "  if ($false) {\n",
     _D + "test_the_helper_failing_blocks[ps1]"),
    ("promote-gate.ps1 exits before the dispatch read when the dirty map lost environments", PS1,
     "if (-not $envProperty -and $envNames.Count -eq 0 -and -not $mapDirty) { exit 0 }\n",
     "if (-not $envProperty -and $envNames.Count -eq 0) { exit 0 }\n",
     _D + "test_a_working_map_without_environments_still_reads_the_committed_dispatches[ps1]"),
    # L-0665: the newest row decides, both flavours.
    ("promote-gate.sh returns on the first matching row again (fail then pass)", SH,
     '            newest = all(c.lower() == "pass" for c in cells[3:6])\n    return newest',
     '            return all(c.lower() == "pass" for c in cells[3:6])\n    return newest',
     _R + "[fail-then-pass-sh]"),
    ("promote-gate.sh returns on the first matching row again (pass then fail)", SH,
     '            newest = all(c.lower() == "pass" for c in cells[3:6])\n    return newest',
     '            return all(c.lower() == "pass" for c in cells[3:6])\n    return newest',
     _R + "[pass-then-fail-sh]"),
    ("promote-gate.ps1 returns on the first matching row again (fail then pass)", PS1,
     "      $newest = if ($cells[3] -ieq 'pass' -and $cells[4] -ieq 'pass' -and $cells[5] -ieq '"
     "pass') { 'pass' } else { 'fail' }\n",
     "      return $(if ($cells[3] -ieq 'pass' -and $cells[4] -ieq 'pass' -and $cells[5] -ieq 'p"
     "ass') { 'pass' } else { 'fail' })\n",
     _R + "[fail-then-pass-ps1]"),
    ("promote-gate.ps1 returns on the first matching row again (pass then fail)", PS1,
     "      $newest = if ($cells[3] -ieq 'pass' -and $cells[4] -ieq 'pass' -and $cells[5] -ieq '"
     "pass') { 'pass' } else { 'fail' }\n",
     "      return $(if ($cells[3] -ieq 'pass' -and $cells[4] -ieq 'pass' -and $cells[5] -ieq 'p"
     "ass') { 'pass' } else { 'fail' })\n",
     _R + "[pass-then-fail-ps1]"),
    # L-0689: a fragment of a declared deploy is no deploy, both flavours, both maps.
    ("promote-gate.sh matches a fragment of a declared deploy again", SH,
     "        if any(isinstance(d, str) and d and fold(d) in fcmd\n",
     "        if any(isinstance(d, str) and d and (fold(d) in fcmd or fcmd in fold(d))\n",
     _M + "test_a_fragment_of_a_declared_deploy_is_not_a_deploy_must_allow[git rev-parse HEAD-sh]"),
    ("promote-gate.sh matches a fragment against the committed map again", SH,
     "        if any(isinstance(d, str) and d and fold(d) in fcmd\n",
     "        if any(isinstance(d, str) and d and (fold(d) in fcmd or fcmd in fold(d))\n",
     _M + "test_a_fragment_with_the_map_dirty_matches_nothing_committed[sh]"),
    ("promote-gate.ps1 matches a fragment of a declared deploy again", PS1,
     "    return ($c.IndexOf($Dep, [StringComparison]::OrdinalIgnoreCase) -ge 0)\n",
     "    return ($c.IndexOf($Dep, [StringComparison]::OrdinalIgnoreCase) -ge 0 -or\n"
     "            $Dep.IndexOf($c, [StringComparison]::OrdinalIgnoreCase) -ge 0)\n",
     _M + "test_a_fragment_of_a_declared_deploy_is_not_a_deploy_must_allow[git rev-parse HEAD-ps1]"),
    ("promote-gate.ps1 reads a declared deploy as a wildcard pattern again", PS1,
     "    return ($c.IndexOf($Dep, [StringComparison]::OrdinalIgnoreCase) -ge 0)\n",
     "    return ($c -like \"*$Dep*\")\n",
     "tests/test_promote_gate_literal_match.py::test_a_deploy_holding_brackets_matches_itself_and_blocks[ps1]"),
    # --- L-0703: the exact-sha rule and the review evidence ------------------
    ("promote-gate.sh counts a 7-character prefix as this sha again", SH,
     '    if cell == full:\n        return "full"\n',
     '    if full.startswith(cell[:7]):\n        return "full"\n',
     _V + "test_a_pass_row_for_a_same_prefix_different_sha_is_refused[sh]"),
    ("promote-gate.sh counts a short row as the full sha", SH,
     '    if 0 < len(cell) < len(full) and full.startswith(cell):\n        return "short"\n',
     '    if 0 < len(cell) < len(full) and full.startswith(cell):\n        return "full"\n',
     _V + "test_a_short_row_for_the_deploying_sha_is_refused[7-sh]"),
    ("promote-gate.ps1 counts a 7-character prefix as this sha again", PS1,
     '    if ($cell -ceq $sha) {\n',
     '    if ($sha.StartsWith($cell.Substring(0, [Math]::Min(7, $cell.Length)))) {\n',
     _V + "test_a_pass_row_for_a_same_prefix_different_sha_is_refused[ps1]"),
    ("_promote_review.py drops the tree-identity filter", REVIEW,
     '                  if line == f"{want} tree"]\n',
     '                  if line.endswith(" tree")]\n',
     _V + "test_a_change_the_bundle_cannot_see_is_still_a_different_tree[sh]"),
    ("_promote_review.py accepts a receipt on its state alone", REVIEW,
     '            ok, why = review_ledger.check_receipt(tree, ticket)\n',
     '            ok, why = True, "not checked"\n',
     _V + "test_a_receipt_whose_bundle_no_longer_matches_is_refused[sh]"),
    ("_promote_review.py waits on a hung receipt check without a bound", REVIEW,
     '        out, err = proc.communicate(timeout=seconds)\n',
     '        out, err = proc.communicate()\n',
     _V + "test_a_hung_receipt_check_blocks_within_the_hook_timeout[sh]"),
    ("promote-gate.sh gives the review search a fixed budget, not what is left", SH,
     '  "$GATE_DEADLINE" "${ENVLIST[@]}")\n',
     '  "$(( $(date +%s) + 60 ))" "${ENVLIST[@]}")\n',
     _V + "test_a_slow_python_plus_a_hung_check_still_ends_inside_the_hook_timeout[sh]"),
    ("promote-gate.sh skips the review evidence", SH,
     'REVIEW=$("$PY" "$(dirname "${BASH_SOURCE[0]}")/_promote_review.py" "$TREE" "$FULL" \\\n',
     'REVIEW=$(true "$(dirname "${BASH_SOURCE[0]}")/_promote_review.py" "$TREE" "$FULL" \\\n',
     _V + "test_no_ledger_is_refused[sh]"),
    ("promote-gate.ps1 skips the review evidence", PS1,
     'foreach ($reason in ($reviewOut -split [char]0x1e)) {\n',
     'foreach ($reason in @()) {\n',
     _V + "test_no_ledger_is_refused[ps1]"),
    ("promote-gate.sh stands down again when no python resolves", SH,
     'PY=$(crew_py) || PY=""\n',
     'PY=$(crew_py) || exit 0\n',
     _V + "test_sh_without_python_blocks_a_declared_deploy[True]"),
    ("promote-gate.ps1 allows a deploy when no python resolves", PS1,
     '  Deny-ReviewUnknown "no usable python was found (python 3.8+ is required to read the review ledgers)."\n',
     '  exit 0\n',
     _V + "test_ps1_without_python_blocks_a_declared_deploy"),
    # --- L-0703 review round 1 ------------------------------------------------
    ("promote-gate.sh reads a newline-only jq hit as no match", SH,
     "($v | contains($c))) | tojson) // empty'",
     "($v | contains($c)))) // empty'",
     _V + "test_sh_without_python_sees_a_match_after_a_newline_only_value"),
    ("promote-gate.sh runs the no-python jq without a bound", SH,
     '    timeout "$left" jq "$@"\n',
     '    jq "$@"\n',
     _V + "test_sh_without_python_blocks_when_jq_stalls"),
    ("_promote_review.py trusts the map as it is now, not as committed", REVIEW,
     '    if hashed.returncode != 0 or not mine or mine != committed:\n',
     '    if False:\n',
     _V + "test_the_helper_refuses_a_map_that_is_not_the_committed_one"),
    ("promote-gate.sh starts its deadline after the first probes", SH,
     'GATE_DEADLINE=$(( $(date +%s) - SECONDS + 16 ))\n',
     'GATE_DEADLINE=$(( $(date +%s) - SECONDS + 21 ))\n',
     _V + "test_a_slow_first_git_probe_counts_against_the_deadline"),
    ("_promote_review.py hashes the map without git's eol rules for its path", REVIEW,
     '[git, "hash-object", "--stdin", "--path", ".crew/verify.json"]',
     '[git, "hash-object", "--stdin"]',
     _V + "test_a_crlf_checkout_of_the_committed_map_is_the_committed_map[sh]"),
    # --- L-0703 review round 2 ------------------------------------------------
    ("_promote_review.py reads a failed map listing as no map at HEAD", REVIEW,
     '    if listed.returncode != 0:\n',
     '    if False:\n',
     _V + "test_the_helper_never_reads_a_failed_map_probe_as_no_map"),
    ("_promote_review.py gives each map probe a flat 10s, not what is left", REVIEW,
     '                                input=raw, capture_output=True, check=False,\n'
     '                                timeout=_left(deadline))\n',
     '                                input=raw, capture_output=True, check=False,\n'
     '                                timeout=GIT_SECONDS)\n',
     _V + "test_the_helper_bounds_its_map_probes_by_the_deadline"),
    ("_promote_review.py reads an unreadable ledger as holding no receipt", REVIEW,
     '        if digest is None or st.get("state") == review_ledger.UNKNOWN:\n',
     '        if False:\n',
     _V + "test_an_unreadable_ledger_is_reported_as_could_not_tell"),
    ("promote-gate.sh opens a map that is not a regular file", SH,
     'if [ -e .crew/verify.json ] && [ ! -f .crew/verify.json ] && [ ! -d .crew/verify.json ]; then\n',
     'if false; then\n',
     _V + "test_sh_refuses_a_map_that_is_not_a_regular_file[True]"),
    ("promote-gate.ps1 opens a map that is not a regular file", PS1,
     "if ($mapStat -and $mapStat.Value -and @('File', 'Directory') -notcontains",
     "if ($false -and $mapStat.Value -and @('File', 'Directory') -notcontains",
     _V + "test_ps1_refuses_a_map_that_is_not_a_regular_file[fifo]"),
    ("promote-gate.ps1 follows no link before judging the map's type", PS1,
     "if ($mapItem -and $mapItem.LinkTarget) {\n",
     "if ($false) {\n",
     _V + "test_a_map_reached_through_a_link_to_a_regular_file_is_read[ps1]"),
    # --- L-0703 Codex r1 -------------------------------------------------------
    ("promote-gate.sh's no-python fallback passes a map it cannot classify", SH,
     '    if [ "$shape" != "ok" ]; then\n',
     '    if false; then\n',
     _V + "test_without_python_a_map_it_cannot_classify_blocks[sh-deploy-true]"),
    ("promote-gate.sh blocks a failed review helper during an incident", SH,
     'if [ "$REVIEW_STATUS" -ne 0 ] && crew_incident_active; then\n',
     'if false; then\n',
     _V + "test_an_open_incident_records_a_failing_helper_as_a_skip[sh-exits-nonzero]"),
    ("promote-gate.ps1 blocks a failed review helper during an incident", PS1,
     '  if ($incident) {\n    $problems.Add("the review-evidence check',
     '  if ($false) {\n    $problems.Add("the review-evidence check',
     _V + "test_an_open_incident_records_a_failing_helper_as_a_skip[ps1-missing]"),
    # --- L-0703 Codex r2 -------------------------------------------------------
    ("promote-gate.sh's fallback compares leaf paths for repeated keys again", SH,
     '    dup=$(printf \'%s\' "$text" | np_jq -n --stream "$NP_DUP" 2>/dev/null)\n',
     '    dup=$(printf \'%s\' "$text" | np_jq -n --stream \'[inputs | select(length == 2) | .[0]]'
     ' | (length != (unique | length))\' 2>/dev/null)\n',
     _V + "test_without_python_a_map_it_cannot_classify_blocks[sh-dup-key-other-children]"),
    ("promote-gate.sh's fallback folds ASCII case only", SH,
     '"$NP_FOLD"\' ($c | coarse) as $c',
     '\'def coarse: ascii_downcase; ($c | coarse) as $c',
     _V + "test_sh_without_python_matches_as_the_matcher_folds_case[False-e-acute]"),
    ("promote-gate.sh's fallback forgets the two characters python folds onto ASCII", SH,
     'elif . == 305 then 105 elif . == 383 then 115 else 65533 end',
     'else 65533 end',
     _V + "test_sh_without_python_matches_as_the_matcher_folds_case[False-long-s]"),
    # --- L-0703 Codex r3 -------------------------------------------------------
    ("promote-gate.sh's fallback reads the committed map without a bound", SH,
     '    NP_HEAD_MAP=$(timeout "$NP_LEFT" git cat-file blob "$HEAD_MAP" 2>/dev/null) || {\n',
     '    NP_HEAD_MAP=$(git cat-file blob "$HEAD_MAP" 2>/dev/null) || {\n',
     _V + "test_sh_without_python_bounds_the_committed_map_read"),
    ("_promote_review.py gives Windows taskkill a flat 5s again", REVIEW,
     'timeout=max((until - time.monotonic()) / 2, 0.1))',
     'timeout=5)',
     _V + "test_windows_cleanup_stays_inside_the_reap_allowance"),
    # --- rush 1.2.1: L-0703's no-python shape check meets main's L-0648 rule --
    ("promote-gate.sh's fallback passes a map whose github entry python refuses", SH,
     '              elif has_ci("github") and (get_ci("github") | github_ok | not) then',
     '              elif false then',
     _V + "test_without_python_a_map_it_cannot_classify_blocks[sh-github-string]"),
)
