"""A repository whose refresh artifacts are anchored, and the refresh that
re-anchors them, for `test_refresh_admission.py` (T-0094) and, once L-0540
wires the completion audit to `artifact_verdicts`, its
`test_completion_audit_refresh_artifacts.py` (split by the owner, 2026-09-30).

The refresh `refreshed` performs is the shape `8bbb26d9` (T-0075) wrote in
this repository, not "the anchor line only": the map's `anchor:` moves AND its
citations and prose are re-derived, the INDEX row of that map gains a clause,
`.claude/rules/` is regenerated by `crew_instructions.rules`, the diagram's
`%% Generated from` sha moves and a `%%` provenance line is added, and both
graph files are rewritten. A fixture that only moved anchors would let an
"anchor line only" admission pass here and refuse every real refresh.

Plain functions, no pytest fixtures: each suite calls them with its own
`tmp_path`. Everything is built under that path; nothing touches the real
repository.
"""
import hashlib
import json
import os
import re

import context  # noqa: F401  pylint: disable=unused-import
import crew_instructions
import scope_fixtures
from crew_fixtures import head_sha
from review_fixtures import git

MAP = ".crew/codemap/{name}.md"
RULE = ".claude/rules/{name}.md"
INDEX = ".crew/codemap/INDEX.md"
DIAGRAM = "docs/diagrams/{name}.mmd"
RENDERED = "docs/diagrams/flow.svg"
GRAPH = ("graphify-out/graph.json", "graphify-out/GRAPH_REPORT.md")
ARTIFACTS = [MAP.format(name="app"), INDEX, RULE.format(name="app"),
             DIAGRAM.format(name="flow"), RENDERED] + list(GRAPH)


def write(root, rel, text):
    path = root.joinpath(*rel.split("/"))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def read(root, rel):
    return root.joinpath(*rel.split("/")).read_text(encoding="utf-8")


def map_text(name, anchor, cites, claim):
    """A code map: explicit `paths:`, an `anchor:` line (none when `anchor`
    is None) and one Landmines bullet per citation."""
    lines = [f"# {name}", "paths: src/**"]
    if anchor is not None:
        lines.append(f"anchor: r@{anchor}")
    lines += ["", "## Landmines"] + [f"- `{c}` - {claim}" for c in cites]
    return "\n".join(lines) + "\n"


def _index(anchor):
    return ("# Code map index\n\nOne row per subsystem map.\n\n"
            "| File | Anchor | Last pass | Covers |\n|---|---|---|---|\n"
            f"| [`app.md`](app.md) | `{anchor[:8]}` | first pass | the app |\n")


def _diagram(anchor, anchors="src/app.py"):
    """A diagram source; `anchors` None leaves out the `%% Anchors:` line, so
    any code path reaches it."""
    declared = f"%% Anchors: {anchors}\n" if anchors is not None else ""
    return f"%% Generated from r@{anchor} on 2026-09-28.\n{declared}flowchart LR\n  a --> b\n"


def _graph(root, sha):
    write(root, GRAPH[0], json.dumps({"nodes": [], "links": [], "built_at_commit": sha}) + "\n")
    write(root, GRAPH[1], f"# report {sha}\n")


def _side_commit(root, start):
    """A commit on a branch off `start` that HEAD never reaches; back on main."""
    git(root, "checkout", "-q", "-b", "side", start)
    write(root, "other/side.py", "s = 1\n")
    git(root, "add", "-A")
    git(root, "commit", "-qm", "side commit")
    side = head_sha(root, 40)
    git(root, "checkout", "-q", "main")
    return side


def anchored_repo(tmp_path, touch=("src/**",), map_anchor=None, extra=None,
                  cites=("src/app.py:1",), diagram_anchors="src/app.py", diagram_ext=".mmd"):
    """(root, base). A `scope_fixtures.make_repo` repo with `.crew/codemap/`
    un-ignored, whose BASE commit holds the code map `app.md` (explicit
    `paths: src/**`, anchored at the commit before the base unless
    `map_anchor` says otherwise -- `"side"` anchors it to a commit on a
    branch HEAD never reaches -- citing `cites`), INDEX.md with its row, the
    rule `crew_instructions.rules` writes for it, a diagram source anchored
    the same way with `%% Anchors: <diagram_anchors>` (None: no Anchors
    line), a rendered diagram beside it and both graph files, plus any
    `extra` {rel: text}. The diagram source is `docs/diagrams/flow<diagram_ext>`
    (review round 4: `.MMD` proves the pairing is case-folded). The ticket
    T-1 is then made, approved as the user and its base recorded, and one
    commit edits `src/app.py`."""
    root = scope_fixtures.make_repo(tmp_path, mode="block")
    write(root, ".gitignore", ".work/\n.crew/*\n!.crew/codemap/\n")
    git(root, "commit", "-qam", "un-ignore the code map")
    first = head_sha(root, 40)
    if map_anchor == "side":
        map_anchor = _side_commit(root, first)
    write(root, MAP.format(name="app"),
          map_text("app", map_anchor or first, cites, "x is one"))
    write(root, INDEX, _index(first))
    _problems, written = crew_instructions.rules(str(root))
    assert written == [os.path.join(".claude", "rules", "app.md")], written
    write(root, _diagram_rel("flow", diagram_ext), _diagram(first, diagram_anchors))
    write(root, RENDERED, f"<svg><!-- {first} --></svg>\n")
    _graph(root, first)
    for rel, text in (extra or {}).items():
        write(root, rel, text)
    git(root, "add", "-A")
    git(root, "commit", "-qm", "base artifacts")
    base = head_sha(root, 40)
    scope_fixtures.ready(root, touch=touch)
    write(root, "src/app.py", "x = 2\n")
    git(root, "commit", "-qam", "ticket edit")
    return root, base


def re_anchor_map(root, name, sha, cites=("src/app.py:2",)):
    """Rewrite the map's claims AND move its anchor to `sha`, as a refresh does."""
    write(root, MAP.format(name=name),
          map_text(name, sha, cites, f"x is two (re-derived at {sha[:8]})"))


def index_row_append(root, name, clause):
    """Append `; <clause>` to the Last pass cell of `<name>.md`'s INDEX row
    (the row `crew_context.index_covers` reads)."""
    row = re.compile(r"^\|\s*\[`?" + re.escape(name) + r"\.md`?\]\([^)]*\)\s*\|")
    out = []
    for line in read(root, INDEX).splitlines():
        if row.match(line):
            cells = line.split("|")
            cells[3] = cells[3].rstrip() + f"; {clause} "
            line = "|".join(cells)
        out.append(line)
    write(root, INDEX, "\n".join(out) + "\n")


def _diagram_rel(name, ext):
    return DIAGRAM.format(name=name)[:-len(".mmd")] + ext


def re_anchor_diagram(root, name, sha, ext=".mmd"):
    """Move the `%% Generated from` sha to `sha` and add a provenance line."""
    rel = _diagram_rel(name, ext)
    text = re.sub(r"(%% Generated from r@)[0-9a-f]+", lambda m: m.group(1) + sha,
                  read(root, rel), count=1)
    write(root, rel, text + f"%% Re-anchored at {sha[:8]}\n")


def rebuild_graph(root, sha):
    _graph(root, sha)


def refreshed(root):
    """The `8bbb26d9` shape on every artifact, anchored at HEAD."""
    head = head_sha(root, 40)
    re_anchor_map(root, "app", head)
    index_row_append(root, "app", f"re-anchored to `{head[:8]}`")
    crew_instructions.rules(str(root))
    re_anchor_diagram(root, "flow", head)
    write(root, RENDERED, f"<svg><!-- {head} --></svg>\n")
    rebuild_graph(root, head)
    return head


EMPTY_TREE = "4b825dc642cb6eb9a060e54bf8d69288fbee4904"


def ambiguous_commit_prefix(length=7, limit=2_000_000):
    """(prefix, [body_a, body_b]): two raw commit bodies (the empty tree, a
    fixed author and date, messages `n<i>`) whose sha1 share their first
    `length` hex digits, found by a bounded, deterministic birthday search in
    hashlib (no git). Written into a repo with
    `git hash-object -t commit -w --stdin`; the caller asserts git's sha equals
    the computed one. A search that finds nothing fails loudly, never skips."""
    seen = {}
    for i in range(limit):
        body = (f"tree {EMPTY_TREE}\nauthor t <t@t> 0 +0000\n"
                f"committer t <t@t> 0 +0000\n\nn{i}\n").encode()
        sha = hashlib.sha1(b"commit %d\0" % len(body) + body).hexdigest()
        prefix = sha[:length]
        if prefix in seen:
            return prefix, [seen[prefix], body]
        seen[prefix] = body
    raise AssertionError(f"no {length}-hex sha1 collision in {limit} candidates")
