"""Mutations for crew_coord.py (T-0030: cross-session claims) -- a module of
its own, same tuple shape as sabotage_scope.py's SCOPE_MUTATIONS
(label, target, find, replace, test), appended to MUTATIONS by sabotage.py,
which sits at `.pylintrc`'s max-module-lines. Run `sabotage.py`, not this file.

The first eight are the spec's Acceptance list, in its order. The next two
cover the retry and the identity-file check, which the list does not name but
which the claim and recovery guarantees rest on. The rest are review round 1's
findings (T-0030-coord--r8XvAI), one per guard branch the fixes added: each
reintroduces the defect the finding reproduced, and names the test that
reproduces it.
"""
import os

CREW = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COORD = os.path.join(CREW, "hooks", "scripts", "crew_coord.py")
_T = "tests/test_crew_coord.py::"

COORD_MUTATIONS = (
    ("crew_coord pushes with --force-with-lease", COORD,
     '        return ["push", "--no-verify", "--", PUSH_REMOTE, f"{sha}:{self.ref}"]\n',
     '        return ["push", "--force-with-lease", "--no-verify", "--", PUSH_REMOTE, f"{sha}:{self.ref}"]\n',
     _T + "test_push_argv_never_forces"),
    ("crew_coord reads a stale claim as free", COORD,
     '    return claim["state"] == "working" and heartbeat_age(claim) > ttl_minutes * 60\n',
     "    return False\n",
     _T + "test_stale_working_claim_reads_owner_unknown_and_blocks_claim"),
    ("crew_coord status skips a corrupt claim", COORD,
     ("        if claim is None:\n"
      '            lines.append(f"{safe(key)} unknown (corrupt claim file: {why}) [peer-written]")\n'
      "            code = EXIT_UNKNOWN\n"),
     ("        if claim is None:\n"
      "            continue\n"),
     _T + "test_corrupt_claim_reads_unknown_not_skipped[{not json]"),
    ("crew_coord accepts a claim when the fetch failed", COORD,
     ('            if state == "failed":\n'
      '                return Result("unknown", f"unknown - could not fetch'),
     ("            if False:\n"
      '                return Result("unknown", f"unknown - could not fetch'),
     _T + "test_claim_when_fetch_failed_is_refused_unknown"),
    ("crew_coord lets a non-holder release", COORD,
     ('        if claim["holder"]["session"] != me["session"]:\n'
      '            return "refused", peer(f"refused: only the holder may'),
     ("        if False:\n"
      '            return "refused", peer(f"refused: only the holder may'),
     _T + "test_release_done_heartbeat_by_non_holder_refused[release]"),
    ("crew_coord adopts a claim from another machine", COORD,
     '    if old["machine"] != machine():\n',
     "    if False:\n",
     _T + "test_recover_refuses_other_machine"),
    ("crew_coord adopts while the old PID is alive", COORD,
     ('    if probe.state == "alive":\n'
      '        return False, f"pid {pid} is alive, so the old session may still be running"\n'),
     ('    if probe.state == "alive":\n'
      '        probe = PidProbe("gone", probe.start, probe.measured)\n'),
     _T + "test_recover_refuses_live_pid"),
    ("crew_coord reads an unreadable PID check as dead", COORD,
     '    if probe.state != "gone" or not probe.measured:\n',
     "    if False:\n",
     _T + "test_recover_refuses_when_pid_check_cannot_tell"),
    ("crew_coord gives up on the first rejected push", COORD,
     "        for _ in range(1 + MAX_RETRIES):\n",
     "        for _ in range(1):\n",
     _T + "test_two_sessions_claim_different_tickets_concurrently"),
    ("crew_coord recovers without the identity file naming the holder", COORD,
     "    if not named:\n",
     "    if False:\n",
     _T + "test_recover_refuses_identity_file_naming_another_holder"),
    # --- review round 1 ---
    ("crew_coord reads a live pid whose /proc is unreadable as gone", COORD,
     ('        # hidepid hiding another user -- cannot tell: ALIVE, never gone.\n'
      '        return PidProbe("alive", None, True)\n'),
     ('        # hidepid hiding another user -- cannot tell: ALIVE, never gone.\n'
      '        return PidProbe("gone", None, True)\n'),
     _T + "test_linux_probe_live_pid_with_unreadable_proc_reads_alive"),
    ("crew_coord reads another user's pid as gone", COORD,
     "    except PermissionError:\n        pass\n",
     '    except PermissionError:\n        return PidProbe("gone", None, True)\n',
     _T + "test_linux_probe_another_users_pid_with_unreadable_proc_reads_alive"),
    ("crew_coord's fetch writes FETCH_HEAD", COORD,
     '"--no-write-fetch-head", ',
     "",
     _T + "test_fetch_writes_no_fetch_head"),
    ("crew_coord pushes to the remote's name (writes a tracking ref)", COORD,
     '        return ["push", "--no-verify", "--", PUSH_REMOTE, f"{sha}:{self.ref}"]\n',
     '        return ["push", "--no-verify", "--", self.remote, f"{sha}:{self.ref}"]\n',
     _T + "test_commands_write_no_remote_tracking_ref"),
    ("crew_coord pushes to the URL, putting it in argv", COORD,
     "            pushed = run_git(self.root, self.push_argv(sha), env=push_env)\n",
     ('            pushed = run_git(self.root, ["push", "--no-verify", "--", push_env[max(\n'
      '                k for k in push_env if k.startswith("GIT_CONFIG_VALUE_"))], f"{sha}:{self.ref}"])\n'),
     _T + "test_push_argv_never_carries_the_remote_url"),
    ("crew_coord pushes into a configured remote of the same name", COORD,
     "        if remotes.code != 0 or PUSH_REMOTE in remotes.out.decode(\"utf-8\", \"replace\").split():\n",
     "        if remotes.code != 0:\n",
     _T + "test_push_refuses_when_the_push_remote_name_is_taken"),
    ("crew_coord drops the remote's receivepack from its push remote", COORD,
     '_PUSH_REMOTE_KEYS = ("url", "pushurl", "proxy", "proxyAuthMethod", "receivepack", "vcs")\n',
     '_PUSH_REMOTE_KEYS = ("url", "pushurl", "proxy", "proxyAuthMethod", "vcs")\n',
     _T + "test_push_carries_the_remotes_receivepack_but_never_mirror"),
    ("crew_coord copies the remote's mirror setting", COORD,
     '_PUSH_REMOTE_KEYS = ("url", "pushurl", "proxy", "proxyAuthMethod", "receivepack", "vcs")\n',
     '_PUSH_REMOTE_KEYS = ("url", "pushurl", "proxy", "proxyAuthMethod", "receivepack", "vcs", "mirror")\n',
     _T + "test_push_carries_the_remotes_receivepack_but_never_mirror"),
    ("crew_coord overwrites the caller's GIT_CONFIG entries", COORD,
     "        first = int(base) if base.isdigit() else 0\n",
     "        first = 0\n",
     _T + "test_push_keeps_a_callers_git_config_environment"),
    ("crew_coord's push runs the pre-push hook", COORD,
     '        return ["push", "--no-verify", "--", PUSH_REMOTE, f"{sha}:{self.ref}"]\n',
     '        return ["push", "--", PUSH_REMOTE, f"{sha}:{self.ref}"]\n',
     _T + "test_push_runs_no_pre_push_hook[hooks-dir]"),
    ("crew_coord pushes to a remote with several push URLs", COORD,
     "        if listed.code != 0 or len(urls) != 1:\n",
     "        if listed.code != 0 or not urls:\n",
     _T + "test_push_refuses_a_remote_with_several_push_urls"),
    ("crew_coord launches the heartbeat without --pid", COORD,
     '            "--pid", str(me["pid"]), "--interval", str(interval)]\n',
     '            "--interval", str(interval)]\n',
     _T + "test_claim_launches_the_heartbeat_with_its_pid_and_interval"),
    ("crew_coord hands the heartbeat the full environment", COORD,
     "env=child_env(), close_fds=True",
     "env=dict(os.environ), close_fds=True",
     _T + "test_heartbeat_launch_drops_the_token_even_when_the_process_holds_it"),
    ("crew_coord launches the heartbeat in the caller's session", COORD,
     '{"start_new_session": True} if os.name != "nt"',
     '{"start_new_session": False} if os.name != "nt"',
     _T + "test_claim_launches_the_heartbeat_detached_without_the_token"),
    ("crew_coord hands git the full environment", COORD,
     "    full_env = child_env()\n",
     "    full_env = dict(os.environ)\n",
     _T + "test_run_git_drops_the_messaging_token_on_its_own"),
    ("crew_coord keeps the token in its own environment", COORD,
     "        os.environ.pop(name, None)\n",
     "        pass\n",
     _T + "test_git_children_never_receive_the_messaging_token"),
    ("crew_coord prints URL credentials from git's stderr", COORD,
     '    return safe(_URL_CREDENTIALS_RE.sub(r"\\1***@", lines[-1])) if lines else "no message"\n',
     '    return safe(lines[-1]) if lines else "no message"\n',
     _T + "test_git_error_output_has_url_credentials_redacted"),
    ("crew_coord strips only C0/C1 from peer text", COORD,
     '    text = "".join("?" if unicodedata.category(ch) in _UNSAFE_CATEGORIES else ch for ch in str(value))\n',
     '    text = re.sub(r"[\\x00-\\x1f\\x7f-\\x9f]", "?", str(value))\n',
     _T + "test_peer_text_cannot_forge_an_unlabelled_line[U+2028]"),
    ("crew_coord's held refusal is unlabelled", COORD,
     '    return Result("refused", peer(f"refused: {key} is held working by {describe(claim)}"))\n',
     '    return Result("refused", f"refused: {key} is held working by {describe(claim)}")\n',
     _T + "test_refusals_label_peer_written_holder_fields[claim]"),
    ("crew_coord's recover refusal is unlabelled", COORD,
     '            return "refused", peer(f"{key} {body}")\n',
     '            return "refused", f"{key} {body}"\n',
     _T + "test_refusals_label_peer_written_holder_fields[recover]"),
    ("crew_coord rewrites the identity file without its lock", COORD,
     '        with _locked(path + ".lock"):\n',
     "        with contextlib.nullcontext():\n",
     _T + "test_identity_update_holds_the_lock_across_read_and_write"),
    ("crew_coord rewrites other channel files as 100644", COORD,
     "            return known[2], known[1]\n",
     '            return "100644", known[1]\n',
     _T + "test_other_files_on_the_channel_keep_their_mode"),
    ("crew_coord re-splits the recovered key", COORD,
     ('        _maybe_start_heartbeat(chan, top, key, repo, ticket, me, ttl, args)\n'
      '    if outcome.get("mine"):\n'),
     ('        repo, _, ticket = key.partition("__")\n'
      '        _maybe_start_heartbeat(chan, top, key, repo, ticket, me, ttl, args)\n'
      '    if outcome.get("mine"):\n'),
     _T + "test_recover_passes_the_parsed_ticket_to_the_heartbeat"),
    ("crew_coord skips the identity on an ambiguous adopt", COORD,
     '    if result.status == "ok" or outcome.get("mine"):\n',
     '    if result.status == "ok":\n',
     _T + "test_recover_retry_that_finds_itself_holding_records_the_identity"),
    ("crew_coord accepts a shared heartbeat directory", COORD,
     "    if uid is not None and (info.st_uid != uid or info.st_mode & 0o077):\n",
     "    if False:\n",
     _T + "test_heartbeat_refuses_a_shared_or_loose_directory[511]"),
    ("crew_coord follows a symlink at the heartbeat log", COORD,
     '    return os.open(path, flags | os.O_CREAT | getattr(os, "O_NOFOLLOW", 0), 0o600)\n',
     "    return os.open(path, flags | os.O_CREAT, 0o600)\n",
     _T + "test_heartbeat_log_never_follows_a_planted_symlink"),
    ("crew_coord opens the heartbeat log world-readable", COORD,
     '    return os.open(path, flags | os.O_CREAT | getattr(os, "O_NOFOLLOW", 0), 0o600)\n',
     '    return os.open(path, flags | os.O_CREAT | getattr(os, "O_NOFOLLOW", 0), 0o644)\n',
     _T + "test_heartbeat_log_is_private_to_this_user"),
    ("crew_coord runs a second heartbeat loop for one claim", COORD,
     "            _lock_fd(lock, wait=False)\n",
     "            pass\n",
     _T + "test_a_second_heartbeat_loop_for_the_same_claim_exits"),
    ("crew_coord reads any OpenProcess error as gone on Windows", COORD,
     "            if last_error() == _ERROR_INVALID_PARAMETER:\n",
     "            if True:\n",
     _T + "test_windows_probe_reads_the_measured_answers[err5-alive]"),
    ("crew_coord reads an unexpected OpenProcess error as gone", COORD,
     '            return PidProbe("alive", None, True)  # any other OpenProcess error cannot tell\n',
     '            return PidProbe("gone", None, True)  # any other OpenProcess error cannot tell\n',
     _T + "test_windows_probe_reads_the_measured_answers[err6-alive]"),
    ("crew_coord reads an opened Windows handle as gone", COORD,
     '            return PidProbe("alive", str(created) if created else None, True)\n',
     '            return PidProbe("gone", None, True)\n',
     _T + "test_windows_probe_reads_the_measured_answers[running-alive]"),
    ("crew_coord ignores the Windows exit FILETIME", COORD,
     "            if exited:\n",
     "            if False:\n",
     _T + "test_windows_probe_reads_the_measured_answers[exit-filetime-gone]"),
    ("crew_coord reads a failed GetProcessTimes as gone", COORD,
     ('                return PidProbe("alive", None, True)\n'
      "            created, exited = "),
     ('                return PidProbe("gone", None, True)\n'
      "            created, exited = "),
     _T + "test_windows_probe_reads_the_measured_answers[times-fail-alive]"),
    ("crew_coord ignores a reused pid's start time", COORD,
     '    if probe.state == "alive" and old.get("pid_start") and probe.start and probe.start != old["pid_start"]:\n',
     "    if False:\n",
     _T + "test_recover_on_windows_refuses_a_reused_pid"),
)
