"""The T-0004 mutations: `crew_autopilot.py`, `crew_ticket.parse_risk` and
`commands/autopilot.md`. Same tuple shape as `sabotage.py`'s MUTATIONS --
(label, target, find, replace, test) -- and appended to it there;
`sabotage.py` sits near `.pylintrc`'s max-module-lines, so this list lives
apart. Run `sabotage.py`, not this file.

Each one is a way autopilot could drive past a person, guess a ticket, or
write where it must not.
"""
import os

CREW = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPTS = os.path.join(CREW, "hooks", "scripts")
AUTOPILOT = os.path.join(SCRIPTS, "crew_autopilot.py")
TICKET = os.path.join(SCRIPTS, "crew_ticket.py")
COMMAND = os.path.join(CREW, "commands", "autopilot.md")
_T = "tests/test_crew_autopilot.py::"

AUTOPILOT_MUTATIONS = (
    ("an unknown spec risk reads as low", TICKET,
     '    return {"risk": "high", "known": False}\n',
     '    return {"risk": "low", "known": False}\n',
     _T + "test_risk_absent_reads_high"),
    ("plan approval stops nothing", AUTOPILOT,
     '        return answer("approve", True, ',
     '        return answer("approve", False, ',
     _T + "test_next_never_returns_approve_without_stop"),
    ("T-0008 missing reads as fresh artifacts", AUTOPILOT,
     '        return {"state": UNAVAILABLE, "command": "", "reason": REFRESH_UNAVAILABLE}\n',
     '        return {"state": FRESH, "command": "", "reason": REFRESH_UNAVAILABLE}\n',
     _T + "test_refresh_unavailable_stops"),
    ("the INDEX fallback takes the first of several open tickets", AUTOPILOT,
     "            if len(candidates) > 1:\n",
     "            if False:\n",
     _T + "test_resume_several_open_tickets_stops"),
    ("the command drops an AUTONOMOUS_STOPS id", COMMAND,
     "- `git-destruction` - ",
     "- ",
     _T + "test_command_names_every_autonomous_stop"),
    ("a mode typo arms autopilot", AUTOPILOT,
     '    armed = mode == "plan"\n',
     '    armed = str(mode).strip().lower() == "plan"\n',
     _T + "test_mode_typo_is_off"),
    # ---- round 1 (T-0004-02ixAb), one per new stop
    ("BLOCK: a spent budget with no receipt still reviews (writes NEEDS_REPLAN)", AUTOPILOT,
     "    if not ok and (not isinstance(left, int) or left < 1):\n",
     "    if False:\n",
     _T + "test_next_budget_spent_without_a_receipt_stops"),
    ("an INCOMPLETE round is rerun unattended", AUTOPILOT,
     '    if latest.get("verdict") != "CLEAN" and not ok:\n',
     "    if False:\n",
     _T + "test_next_incomplete_round_stops"),
    ("BLOCK: the command lets a review phase fix and rerun", COMMAND,
     "never fix and rerun inside the phase",
     "fix and rerun inside the phase",
     _T + "test_command_ends_the_review_phase_at_the_verdict"),
    ("a pre-T-0026 approval stop loses its header-only reason", AUTOPILOT,
     "                return was\n",
     "                return None\n",
     _T + "test_next_legacy_receipt_header_edit_names_the_header_edit"),
    ("no INDEX row reads as an approved direction", AUTOPILOT,
     "    if status is None:\n",
     "    if False:\n",
     _T + "test_next_direction_approval_unknown_stops"),
    ("open questions do not stop", AUTOPILOT,
     "    if questions:\n",
     "    if False:\n",
     _T + "test_next_open_questions_stop"),
    ("any unknown artifact is refreshed", AUTOPILOT,
     '    return (artifact.get("status") == UNKNOWN and artifact.get("refreshable") is True\n'
     "            and ORPHANED_ANCHOR in reason)\n",
     '    return artifact.get("status") == UNKNOWN\n',
     _T + "test_refresh_unknown_other_cause_stops"),
    ("one settled artifact carries an unsettled one", AUTOPILOT,
     "            or not all(_settles(a) for a in pending):\n",
     "            or not any(_settles(a) for a in pending):\n",
     _T + "test_refresh_one_unsettled_artifact_stops_the_rest"),
    ("an answer-level unknown is refreshed through a stale artifact", AUTOPILOT,
     '    overall_unknown = status == UNKNOWN and not any(a.get("status") == UNKNOWN '
     "for a in pending)\n",
     "    overall_unknown = False\n",
     _T + "test_refresh_overall_unknown_over_stale_artifacts_stops"),
    ("a refresh check that raised reads as fresh", AUTOPILOT,
     '        return {"state": UNSETTLED, "command": "",\n'
     '                "reason": f"the refresh check could not run',
     '        return {"state": FRESH, "command": "",\n'
     '                "reason": f"the refresh check could not run',
     _T + "test_refresh_check_that_raises_stops"),
    ("the handoff's ticket folder is not checked", AUTOPILOT,
     "    if not os.path.isdir(crew_ticket.ticket_dir(top, arg)):\n",
     "    if False:\n",
     _T + "test_resume_handoff_ticket_without_a_folder_falls_through"),
    ("a ticket other than the active one is driven", AUTOPILOT,
     '    if where == "active-ticket" and active != ticket:\n',
     "    if False:\n",
     _T + "test_resume_handoff_disagreeing_with_the_active_pointer_stops"),
    ("the driven ticket is never activated", AUTOPILOT,
     '"activate": where != "active-ticket"}',
     '"activate": False}',
     _T + "test_resume_from_handoff_line"),
    ("the command never activates the ticket", COMMAND,
     "`activate=1` (no pointer is set)",
     "(no pointer is set)",
     _T + "test_command_activates_the_ticket_only_without_a_pointer"),
    ("stale-after-review writes crew state", AUTOPILOT,
     "        return answer(\"stale-after-review\", True, ",
     "        os.close(os.open(os.path.join(crew_ticket.state_dir(top), \"x\"), "
     "os.O_CREAT | os.O_WRONLY))\n"
     "        return answer(\"stale-after-review\", True, ",
     _T + "test_next_stale_after_review_stops_without_writing"),
    # ---- round-2 fixes: human-stop bypasses found after round 1
    ("a blank or unknown INDEX status reads as an approved direction", AUTOPILOT,
     "    if status not in DIRECTION_APPROVED:\n",
     "    if False:\n",
     _T + "test_next_index_status_that_does_not_say_approved_stops"),
    ("an INDEX done row is re-driven", AUTOPILOT,
     "    if status in INDEX_DONE:\n",
     "    if False:\n",
     _T + "test_next_index_status_done_stops_as_closed"),
    ("an open question starting with `none` reads as answered", AUTOPILOT,
     '_ANSWERED = re.compile(r"^(?:(?:none|n/a)(?:$|\\s*[-:,(\\u2013\\u2014])|\\[x\\]|~~|-$)")\n',
     '_ANSWERED = re.compile(r"^(?:none|n/a|\\[x\\]|~~|-$)")\n',
     _T + "test_next_open_question_that_only_looks_answered_stops"),
    ("a sub-heading ends the open questions section", AUTOPILOT,
     "            if depth and level > depth:\n                continue\n",
     "            if False:\n                continue\n",
     _T + "test_next_open_question_that_only_looks_answered_stops"),
    ("next drives a ticket the scope guard does not judge by", AUTOPILOT,
     "    if broken or active != ticket:\n",
     "    if broken:\n",
     _T + "test_next_stops_when_another_ticket_is_active"),
    ("next drives when no pointer and INDEX names another ticket", AUTOPILOT,
     "    if broken or active != ticket:\n",
     "    if broken or (where == \"active-ticket\" and active != ticket):\n",
     _T + "test_next_stops_when_the_scope_guard_would_judge_another_ticket"),
    ("a crash in next prints no stop", AUTOPILOT,
     "        except Exception as exc:  # pylint: disable=broad-except\n"
     "            # A crash cannot tell the phase",
     "        except crew_ticket.TicketError as exc:  # pylint: disable=broad-except\n"
     "            # A crash cannot tell the phase",
     _T + "test_cli_that_raises_prints_a_stop"),
    ("a crash in resume prints no stop", AUTOPILOT,
     "        except Exception as exc:  # pylint: disable=broad-except\n"
     "            # A crash cannot tell which ticket",
     "        except crew_ticket.TicketError as exc:  # pylint: disable=broad-except\n"
     "            # A crash cannot tell which ticket",
     _T + "test_cli_that_raises_prints_a_stop"),
    ("the command lets autopilot accept or post a review", COMMAND,
     "are the human's. Go back",
     "are autopilot's. Go back",
     _T + "test_command_leaves_accept_and_pr_review_to_the_human"),
    ("the command reads a crash or no output as permission", COMMAND,
     "No output, a traceback or a non-zero exit is a stop.",
     "",
     _T + "test_command_reads_no_answer_as_a_stop"),
)

# ---- T-0010: the approval and questions policies. One per refusing branch;
# each names the test that must go red. Registered in sabotage.py beside
# AUTOPILOT_MUTATIONS; test_crew_autopilot_policy.py holds every anchor to
# exactly one match.
GUARD = os.path.join(SCRIPTS, "scope_guard.py")
_P = "tests/test_crew_autopilot_policy.py::"
_CT = "tests/test_crew_ticket.py::"
_SG = "tests/test_scope_guard.py::"

POLICY_MUTATIONS = (
    ("approval: risk approves a med spec", AUTOPILOT,
     '    elif risk["known"] and risk["risk"] == "low":\n',
     '    elif risk["risk"] in ("low", "med"):\n',
     _P + "test_approval_risk_allows_only_low[med-False]"),
    ("approval: an unknown risk is approved under risk", AUTOPILOT,
     '    elif risk["known"] and risk["risk"] == "low":\n',
     '    elif risk["risk"] == "low" or not risk["known"]:\n',
     _P + "test_approval_risk_unknown_denies[status: spec]"),
    ("a header naming risk twice is trusted", AUTOPILOT,
     '    if len(re.findall(r"\\brisk:", crew_ticket.header_line(text), re.IGNORECASE)) > 1:\n',
     "    if False:\n",
     _P + "test_approval_header_naming_risk_twice_is_unknown"
     "[cut risk: low paths   status: spec   risk: high]"),
    ("approval: the allowCliApproval check is skipped", AUTOPILOT,
     "    if not allowed:\n",
     "    if False:\n",
     _P + "test_approval_requires_allow_cli_approval[False-risk]"),
    ("approval: the human policy approves", AUTOPILOT,
     "    elif policy == HUMAN:\n",
     "    elif False:\n",
     _P + "test_approval_human_never_allows[low]"),
    ("approval: an unreadable review ledger still self-approves", AUTOPILOT,
     "    elif ledger == review_ledger.UNKNOWN:\n",
     "    elif False:\n",
     _P + "test_approval_refuses_when_the_review_ledger_is_unreadable"),
    # ---- T-0010 review round 1 (T-0010-solo--VfNkU3): each FIX and its neighbour
    ("FIX: a NEEDS_REPLAN ledger vetoes self-approving the successor plan", AUTOPILOT,
     "    elif ledger == review_ledger.UNKNOWN:\n",
     "    elif ledger in (review_ledger.NEEDS_REPLAN, review_ledger.UNKNOWN):\n",
     _P + "test_approval_self_allows_a_successor_plan_under_needs_replan[high]"),
    ("FIX: a taken: line must name the policy in force today", AUTOPILOT,
     "        if policy not in (SELF, RISK):\n",
     '        if policy != decision["policy"]:\n',
     _P + "test_questions_file_taken_under_an_earlier_policy_that_took_stays_valid"
     "[risk-self-high]"),
    ("questions-check: a taken: line may name a policy that never takes", AUTOPILOT,
     "        if policy not in (SELF, RISK):\n",
     "        if False:\n",
     _P + "test_questions_file_taken_naming_a_policy_that_never_takes_invalid[human]"),
    ("FIX: the guard reads a bash line continuation as a separator", GUARD,
     '    bash = _BASH_CONTINUATION_RE.sub("", command)\n',
     "    bash = command\n",
     _SG + "test_autopilot_approve_across_a_line_continuation_is_refused"
     "[before-approve-self-module]"),
    ("the guard reads a PowerShell line continuation as a separator", GUARD,
     '    return command, bash, _PS_CONTINUATION_RE.sub(" ", command)\n',
     "    return command, bash, command\n",
     _SG + "test_an_approval_split_across_a_line_continuation_is_refused[ps-crew-ticket-module]"),
    ("FIX: the command stops at approve before the policy runs", COMMAND,
     "- `stop=1` with `phase=approve` or `phase=open-questions` - not yet a stop",
     "- `stop=1` - a stop",
     _P + "test_command_sends_a_stop_at_approve_or_open_questions_to_the_policy_first"),
    ("a policy value that is not a policy reads as self", AUTOPILOT,
     '    return HUMAN, (f"autopilot.{key} is',
     '    return SELF, (f"autopilot.{key} is',
     _P + "test_approval_bad_value_reads_human[Self]"),
    ("questions: an unknown risk is taken under risk", AUTOPILOT,
     '    if policy == RISK and risk["known"] and risk["risk"] == "low":\n',
     '    if policy == RISK and (risk["risk"] == "low" or not risk["known"]):\n',
     _P + "test_questions_risk_takes_only_low[status: spec-stop]"),
    ("questions: the human policy takes the recommendation", AUTOPILOT,
     "    if policy == SELF:\n",
     "    if policy in (SELF, HUMAN):\n",
     _P + "test_questions_human_stops[low]"),
    ("approve runs with autopilot unarmed", AUTOPILOT,
     '    if not settings(top)["armed"]:\n',
     "    if False:\n",
     _P + "test_autopilot_approve_refuses_unarmed"),
    ("approve ignores a policy refusal", AUTOPILOT,
     '    if not got["allow"]:\n',
     "    if False:\n",
     _P + "test_autopilot_approve_refused_prints_reason[human-low]"),
    ("next offers the autopilot route when the policy refuses", AUTOPILOT,
     '    if got["allow"]:\n',
     "    if True:\n",
     _P + "test_next_approve_phase_names_the_human_when_the_policy_refuses"),
    ("questions-check: the recommendation need not be first", AUTOPILOT,
     "    if not options or RECOMMENDED not in options[0][1] or len(marked) != 1:\n",
     "    if not options:\n",
     _P + "test_questions_file_recommendation_not_first_invalid"),
    ("questions-check: one option is enough", AUTOPILOT,
     "    if not 2 <= len(options) <= 4:\n",
     "    if not 1 <= len(options) <= 4:\n",
     _P + "test_questions_file_one_option_invalid"),
    ("questions-check: an option needs no cost", AUTOPILOT,
     "                 if not any(_COST_RE.match(line) for line in lines)]\n",
     "                 if False]\n",
     _P + "test_questions_file_option_without_cost_invalid"),
    ("questions-check: a question needs no research", AUTOPILOT,
     "    if not any(_RESEARCH_RE.match(line) for line in preamble):\n",
     "    if False:\n",
     _P + "test_questions_file_without_research_invalid"),
    ("questions-check: taken while the policy says stop", AUTOPILOT,
     '        if decision["action"] != TAKE:\n',
     "        if False:\n",
     _P + "test_questions_file_taken_while_the_policy_stops_invalid[human-low]"),
    ("questions-check: taken a non-recommended option", AUTOPILOT,
     "        if not options or oid != options[0][0]:\n",
     "        if not options:\n",
     _P + "test_questions_file_taken_non_recommended_invalid"),
    ("the library writes an autopilot receipt the policy refuses", TICKET,
     "        if refusal is not None:\n",
     "        if False:\n",
     _P + "test_the_library_refuses_an_autopilot_receipt_the_policy_denies"),
    ("accepted keeps an autopilot receipt the policy no longer allows", TICKET,
     '    if isinstance(decision, dict) and decision.get("allow") is True:\n',
     "    if True:\n",
     _CT + "test_autopilot_receipt_demoted_when_the_policy_no_longer_allows[human]"),
    ("accepted keeps an autopilot receipt without allowCliApproval", TICKET,
     '    if not cli_approval_allowed(top):\n        return "scope.allowCliApproval',
     '    if False:\n        return "scope.allowCliApproval',
     _CT + "test_autopilot_receipt_needs_allow_cli_even_when_the_policy_says_yes"),
    ("accepted reads a policy it cannot import as a yes", TICKET,
     "    except Exception as exc:  # pylint: disable=broad-except\n"
     '        return (f"whether autopilot.approval',
     "    except Exception as exc:  # pylint: disable=broad-except\n"
     '        return None and (f"whether autopilot.approval',
     _CT + "test_autopilot_receipt_demoted_when_policy_module_missing"),
    ("the guard allows autopilot approve whatever the policy says", GUARD,
     '    if isinstance(decision, dict) and decision.get("allow") is True:\n',
     "    if True:\n",
     _SG + "test_autopilot_approve_is_refused_when_the_policy_says_no[human-low-True-module]"),
    ("the guard never looks at autopilot approve", GUARD,
     "        return _autopilot_refusal(command, top)\n",
     "        return None\n",
     _SG + "test_autopilot_approve_is_refused_when_the_policy_says_no[human-low-True-module]"),
    ("the guard allows a chained autopilot approve", GUARD,
     "    bare = _AUTOPILOT_BARE_RE.fullmatch(command)\n",
     "    bare = _AUTOPILOT_BARE_RE.match(command)\n",
     _SG + "test_autopilot_approve_that_is_not_the_bare_command_is_refused"
     "[python3 hooks/scripts/crew_autopilot.py approve --root . --ticket T-1; rm x-module]"),
    ("the guard reads a policy crash as a yes", GUARD,
     "    except Exception as exc:  # pylint: disable=broad-except\n"
     '        return (f"could not tell whether autopilot.approval',
     "    except Exception as exc:  # pylint: disable=broad-except\n"
     '        return None and (f"could not tell whether autopilot.approval',
     _SG + "test_a_policy_that_cannot_be_told_is_refused"),
    ("the command drops `human` always stops", COMMAND,
     "`human` always stops",
     "`human` usually stops",
     _P + "test_command_routes_approval_through_policy"),
)
