"""The T-0004 mutations: `crew_autopilot.py`, `crew_ticket.parse_risk` and
`commands/autopilot.md`. Same tuple shape as `sabotage.py`'s MUTATIONS --
(label, target, find, replace, test) -- and appended to it there;
`sabotage.py` sits near `.pylintrc`'s max-module-lines, so this list lives
apart. Run `sabotage.py`, not this file.

Each one is a way autopilot could drive past a person, guess a ticket, or
write where it must not.
"""
import os

CREW = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPTS = os.path.join(CREW, "hooks", "scripts")
AUTOPILOT = os.path.join(SCRIPTS, "crew_autopilot.py")
TICKET = os.path.join(SCRIPTS, "crew_ticket.py")
COMMAND = os.path.join(CREW, "commands", "autopilot.md")
_T = "tests/test_crew_autopilot.py::"

AUTOPILOT_MUTATIONS = (
    ("an unknown spec risk reads as low", TICKET,
     '    return {"risk": "high", "known": False}\n',
     '    return {"risk": "low", "known": False}\n',
     _T + "test_risk_absent_reads_high"),
    ("plan approval stops nothing", AUTOPILOT,
     '        return answer("approve", True, ',
     '        return answer("approve", False, ',
     _T + "test_next_never_returns_approve_without_stop"),
    ("T-0008 missing reads as fresh artifacts", AUTOPILOT,
     '        return {"state": UNAVAILABLE, "command": "", "reason": REFRESH_UNAVAILABLE}\n',
     '        return {"state": FRESH, "command": "", "reason": REFRESH_UNAVAILABLE}\n',
     _T + "test_refresh_unavailable_stops"),
    ("the INDEX fallback takes the first of several open tickets", AUTOPILOT,
     "            if len(candidates) > 1:\n",
     "            if False:\n",
     _T + "test_resume_several_open_tickets_stops"),
    ("the command drops an AUTONOMOUS_STOPS id", COMMAND,
     "- `git-destruction` - ",
     "- ",
     _T + "test_command_names_every_autonomous_stop"),
    ("a mode typo arms autopilot", AUTOPILOT,
     '    armed = mode == "plan"\n',
     '    armed = str(mode).strip().lower() == "plan"\n',
     _T + "test_mode_typo_is_off"),
    # ---- round 1 (T-0004-02ixAb), one per new stop
    ("BLOCK: a spent budget with no receipt still reviews (writes NEEDS_REPLAN)", AUTOPILOT,
     "    if not ok and (not isinstance(left, int) or left < 1):\n",
     "    if False:\n",
     _T + "test_next_budget_spent_without_a_receipt_stops"),
    ("an INCOMPLETE round is rerun unattended", AUTOPILOT,
     '    if latest.get("verdict") != "CLEAN" and not ok:\n',
     "    if False:\n",
     _T + "test_next_incomplete_round_stops"),
    ("BLOCK: the command lets a review phase fix and rerun", COMMAND,
     "never fix and rerun inside the phase",
     "fix and rerun inside the phase",
     _T + "test_command_ends_the_review_phase_at_the_verdict"),
    ("a pre-T-0026 approval stop loses its header-only reason", AUTOPILOT,
     "                return was\n",
     "                return None\n",
     _T + "test_next_legacy_receipt_header_edit_names_the_header_edit"),
    ("no INDEX row reads as an approved direction", AUTOPILOT,
     "    if status is None:\n",
     "    if False:\n",
     _T + "test_next_direction_approval_unknown_stops"),
    ("open questions do not stop", AUTOPILOT,
     "    if questions:\n",
     "    if False:\n",
     _T + "test_next_open_questions_stop"),
    ("any unknown artifact is refreshed", AUTOPILOT,
     '    return (artifact.get("status") == UNKNOWN and artifact.get("refreshable") is True\n'
     "            and ORPHANED_ANCHOR in reason)\n",
     '    return artifact.get("status") == UNKNOWN\n',
     _T + "test_refresh_unknown_other_cause_stops"),
    ("one settled artifact carries an unsettled one", AUTOPILOT,
     "            or not all(_settles(a) for a in pending):\n",
     "            or not any(_settles(a) for a in pending):\n",
     _T + "test_refresh_one_unsettled_artifact_stops_the_rest"),
    ("an answer-level unknown is refreshed through a stale artifact", AUTOPILOT,
     '    overall_unknown = status == UNKNOWN and not any(a.get("status") == UNKNOWN '
     "for a in pending)\n",
     "    overall_unknown = False\n",
     _T + "test_refresh_overall_unknown_over_stale_artifacts_stops"),
    ("a refresh check that raised reads as fresh", AUTOPILOT,
     '        return {"state": UNSETTLED, "command": "",\n'
     '                "reason": f"the refresh check could not run',
     '        return {"state": FRESH, "command": "",\n'
     '                "reason": f"the refresh check could not run',
     _T + "test_refresh_check_that_raises_stops"),
    ("the handoff's ticket folder is not checked", AUTOPILOT,
     "    if not os.path.isdir(crew_ticket.ticket_dir(top, arg)):\n",
     "    if False:\n",
     _T + "test_resume_handoff_ticket_without_a_folder_falls_through"),
    ("a ticket other than the active one is driven", AUTOPILOT,
     '    if where == "active-ticket" and active != ticket:\n',
     "    if False:\n",
     _T + "test_resume_handoff_disagreeing_with_the_active_pointer_stops"),
    ("the driven ticket is never activated", AUTOPILOT,
     '"activate": where != "active-ticket"}',
     '"activate": False}',
     _T + "test_resume_from_handoff_line"),
    ("the command never activates the ticket", COMMAND,
     "`activate=1` (no pointer is set)",
     "(no pointer is set)",
     _T + "test_command_activates_the_ticket_only_without_a_pointer"),
    ("stale-after-review writes crew state", AUTOPILOT,
     "        return answer(\"stale-after-review\", True, ",
     "        os.close(os.open(os.path.join(crew_ticket.state_dir(top), \"x\"), "
     "os.O_CREAT | os.O_WRONLY))\n"
     "        return answer(\"stale-after-review\", True, ",
     _T + "test_next_stale_after_review_stops_without_writing"),
    # ---- round-2 fixes: human-stop bypasses found after round 1
    ("a blank or unknown INDEX status reads as an approved direction", AUTOPILOT,
     "    if status not in DIRECTION_APPROVED:\n",
     "    if False:\n",
     _T + "test_next_index_status_that_does_not_say_approved_stops"),
    ("an INDEX done row is re-driven", AUTOPILOT,
     "    if status in INDEX_DONE:\n",
     "    if False:\n",
     _T + "test_next_index_status_done_stops_as_closed"),
    ("an open question starting with `none` reads as answered", AUTOPILOT,
     '_ANSWERED = re.compile(r"^(?:(?:none|n/a)(?:$|\\s*[-:,(\\u2013\\u2014])|\\[x\\]|~~|-$)")\n',
     '_ANSWERED = re.compile(r"^(?:none|n/a|\\[x\\]|~~|-$)")\n',
     _T + "test_next_open_question_that_only_looks_answered_stops"),
    ("a sub-heading ends the open questions section", AUTOPILOT,
     "            if depth and level > depth:\n                continue\n",
     "            if False:\n                continue\n",
     _T + "test_next_open_question_that_only_looks_answered_stops"),
    ("next drives a ticket the scope guard does not judge by", AUTOPILOT,
     "    if broken or active != ticket:\n",
     "    if broken:\n",
     _T + "test_next_stops_when_another_ticket_is_active"),
    ("next drives when no pointer and INDEX names another ticket", AUTOPILOT,
     "    if broken or active != ticket:\n",
     "    if broken or (where == \"active-ticket\" and active != ticket):\n",
     _T + "test_next_stops_when_the_scope_guard_would_judge_another_ticket"),
    ("a crash in next prints no stop", AUTOPILOT,
     "        except Exception as exc:  # pylint: disable=broad-except\n"
     "            # A crash cannot tell the phase",
     "        except crew_ticket.TicketError as exc:  # pylint: disable=broad-except\n"
     "            # A crash cannot tell the phase",
     _T + "test_cli_that_raises_prints_a_stop"),
    ("a crash in resume prints no stop", AUTOPILOT,
     "        except Exception as exc:  # pylint: disable=broad-except\n"
     "            # A crash cannot tell which ticket",
     "        except crew_ticket.TicketError as exc:  # pylint: disable=broad-except\n"
     "            # A crash cannot tell which ticket",
     _T + "test_cli_that_raises_prints_a_stop"),
    ("the command lets autopilot accept or post a review", COMMAND,
     "are the human's. Go back",
     "are autopilot's. Go back",
     _T + "test_command_leaves_accept_and_pr_review_to_the_human"),
    ("the command reads a crash or no output as permission", COMMAND,
     "Anything but a\n`stop=0` line - no output, a traceback, a non-zero exit - is a stop.",
     "",
     _T + "test_command_reads_no_answer_as_a_stop"),
)

# ---- T-0011: the ship phase. Kept apart from AUTOPILOT_MUTATIONS because
# test_crew_autopilot.py pins every entry there to its own file; these name
# test_crew_autopilot_ship.py. One per refusing branch: each is a way an
# unattended merge could happen on something that was not green, not read,
# or reviewed only by the author's family.
_S = "tests/test_crew_autopilot_ship.py::"

SHIP_MUTATIONS = (
    ("ship: merge on pending", AUTOPILOT,
     "    if pending:\n",
     "    if False:\n",
     _S + "test_decision_merge_waits_on_pending"),
    ("ship: the same-family refusal is dropped", AUTOPILOT,
     "    if risk not in LOW_RISKS and all(_family(f) in SAME_FAMILY for f in families or ()):\n",
     "    if False:\n",
     _S + "test_decision_high_risk_same_family_stops"),
    ("ship: a missing model_family counts as cross-family", AUTOPILOT,
     'SAME_FAMILY = ("claude", None)\n',
     'SAME_FAMILY = ("claude",)\n',
     _S + "test_decision_missing_family_counts_as_same_family"),
    ("ship: known failures match by substring", AUTOPILOT,
     '    failed = [n for n, s in rows if s == "fail" and n not in known]\n',
     '    failed = [n for n, s in rows if s == "fail" and not any(k in n for k in known)]\n',
     _S + "test_decision_known_failure_needs_exact_name"),
    ("ship: an unknown risk reads as low", AUTOPILOT,
     "    if risk not in LOW_RISKS and all(",
     '    if risk == "high" and all(',
     _S + "test_decision_unknown_risk_counts_as_high"),
    ("ship: a family's spelling escapes same-family", AUTOPILOT,
     "        return value.strip().lower()\n",
     "        return value\n",
     _S + "test_decision_family_spelling_does_not_escape_same_family"),
    ("ship: a policy that is not exactly merge merges", AUTOPILOT,
     '    if policy != "merge":\n',
     '    if policy == "pr":\n',
     _S + "test_decision_policy_not_exactly_merge_opens_pr"),
    ("ship: unreadable checks wait instead of stopping", AUTOPILOT,
     "    if not isinstance(checks, list):\n",
     "    if False:\n",
     _S + "test_decision_merge_stops_on_unreadable_checks"),
    ("ship: no check reported yet merges", AUTOPILOT,
     "    if not checks:\n",
     "    if False:\n",
     _S + "test_decision_no_required_check_reported_waits"),
    ("ship: an unknown check state reads as pass", AUTOPILOT,
     "    if unread:\n",
     "    if False:\n",
     _S + "test_decision_merge_stops_on_unknown_state"),
    ("ship: an unlisted failure merges", AUTOPILOT,
     "    if failed:\n",
     "    if False:\n",
     _S + "test_decision_merge_stops_on_unlisted_failure"),
    ("ship: a skipped required check reads as pass", AUTOPILOT,
     "    if skipped:\n",
     "    if False:\n",
     _S + "test_decision_skipped_required_check_stops"),
    ("ship: the merge gains --admin", AUTOPILOT,
     '    return ["pr", "merge", str(number), "--merge", "--match-head-commit", head]\n',
     '    return ["pr", "merge", str(number), "--merge", "--match-head-commit", head, "--admin"]\n',
     _S + "test_merge_argv_is_merge_commit_without_admin"),
    ("ship: the merge squashes again", AUTOPILOT,
     '    return ["pr", "merge", str(number), "--merge", "--match-head-commit", head]\n',
     '    return ["pr", "merge", str(number), "--squash", "--match-head-commit", head]\n',
     _S + "test_merge_argv_is_merge_commit_without_admin"),
    ("ship: the merge rebases", AUTOPILOT,
     '    return ["pr", "merge", str(number), "--merge", "--match-head-commit", head]\n',
     '    return ["pr", "merge", str(number), "--rebase", "--match-head-commit", head]\n',
     _S + "test_merge_argv_is_merge_commit_without_admin"),
    ("ship: the push forces", AUTOPILOT,
     '    return ["git", "push", "-u", "origin", branch]\n',
     '    return ["git", "push", "--force", "-u", "origin", branch]\n',
     _S + "test_push_argv_never_forces"),
    ("ship: gh that could not run reads as no PR", AUTOPILOT,
     "    if got is None:\n        return None\n    code, out, err = got\n    if code != 0:\n",
     '    if got is None:\n        return {"state": "NONE"}\n    code, out, err = got\n'
     "    if code != 0:\n",
     _S + "test_phase_gh_failure_stops"),
    ("ship: any gh error reads as no PR", AUTOPILOT,
     '        return {"state": "NONE"} if err.strip() == none else None\n',
     '        return {"state": "NONE"}\n',
     _S + "test_phase_gh_answer_that_is_not_a_pr_state_stops"),
    ("ship: a PR closed unmerged is shipped again", AUTOPILOT,
     '    if state not in ("NONE", "OPEN"):\n',
     "    if False:\n",
     _S + "test_phase_closed_unmerged_pr_stops"),
    ("ship: a receipt that no longer stands still ships", AUTOPILOT,
     "    ok, message = review_ledger.check_receipt(top, ticket)\n    if not ok:\n"
     '        return answer("ship", True,',
     "    ok, message = review_ledger.check_receipt(top, ticket)\n    if False:\n"
     '        return answer("ship", True,',
     _S + "test_phase_receipt_that_no_longer_stands_stops"),
    ("ship: a detached HEAD ships as branch HEAD", AUTOPILOT,
     '    return branch if branch and branch != "HEAD" else None\n',
     "    return branch or None\n",
     _S + "test_phase_detached_head_stops"),
    ("ship: an unarmed autopilot reads gh and ships", AUTOPILOT,
     '    if not config["armed"]:\n        return answer("closed", True,',
     '    if False:\n        return answer("closed", True,',
     _S + "test_phase_unarmed_done_is_closed_without_reading_gh"),
    ("ship: an open PR under ship: pr is re-shipped", AUTOPILOT,
     '    if state == "OPEN" and config["ship"] != "merge":\n',
     "    if False:\n",
     _S + "test_phase_open_pr_under_pr_policy_closes_with_note"),
    ("ship: INDEX done alone reaches ship", AUTOPILOT,
     '        if spec_text is not None and _header_status(spec_text) == "done":\n',
     "        if spec_text is not None:\n",
     _S + "test_phase_index_done_without_a_done_header_stays_closed"),
    ("ship: runs when next does not name ship", AUTOPILOT,
     '    if phase["phase"] != "ship" or phase["stop"]:\n',
     "    if False:\n",
     _S + "test_ship_refuses_when_next_is_not_ship"),
    ("ship: pushes the default branch", AUTOPILOT,
     "    if not branch or not default or branch == default:\n",
     "    if not branch or not default:\n",
     _S + "test_ship_refuses_the_default_branch_before_pushing"),
    ("ship: an unreadable default branch pushes", AUTOPILOT,
     "    if not branch or not default or branch == default:\n",
     "    if not branch or branch == default:\n",
     _S + "test_ship_unreadable_default_branch_stops_before_pushing"),
    ("ship: a failed push continues", AUTOPILOT,
     "    if not pushed:\n",
     "    if False:\n",
     _S + "test_ship_push_failure_stops"),
    ("ship: a failed gh pr create continues", AUTOPILOT,
     "        if created is None or created[0] != 0:\n",
     "        if False:\n",
     _S + "test_ship_pr_create_failure_stops"),
    ("ship: an unreadable ledger reads as no reviews", AUTOPILOT,
     "    if families is None:\n",
     "    if False:\n",
     _S + "test_ship_unreadable_ledger_stops_without_merging"),
    ("ship: a timeout merges", AUTOPILOT,
     '            return _ship_result(ticket, "stop", True, f"{decision[\'reason\']} after "\n',
     '            return _ship_result(ticket, "merged", False, f"{decision[\'reason\']} after "\n',
     _S + "test_ship_timeout_pending_stops"),
    ("ship: a PR head that moved is merged", AUTOPILOT,
     '    if not head or now is None or now.get("state") != "OPEN" '
     'or now.get("headRefOid") != head:\n',
     "    if not head or now is None:\n",
     _S + "test_ship_head_moved_stops_without_merging"),
    ("ship: a failed gh pr merge reads as merged", AUTOPILOT,
     "    if merged is None or merged[0] != 0:\n",
     "    if merged is None:\n",
     _S + "test_ship_merge_failure_stops"),
    ("ship: a merge is never confirmed", AUTOPILOT,
     '    if after is None or after.get("state") != "MERGED":\n',
     "    if False:\n",
     _S + "test_ship_merge_that_does_not_read_merged_stops"),
    ("ship: a crash in ship prints no stop", AUTOPILOT,
     "        except Exception as exc:  # pylint: disable=broad-except\n"
     "            # A crash cannot tell whether it is safe to merge",
     "        except crew_ticket.TicketError as exc:  # pylint: disable=broad-except\n"
     "            # A crash cannot tell whether it is safe to merge",
     _S + "test_cli_ship_that_raises_prints_a_stop"),
    ("ship: checks with an exit code outside 0/1/8 are read", AUTOPILOT,
     "    if got is None or got[0] not in _CHECK_EXITS:\n",
     "    if got is None:\n",
     _S + "test_adapter_checks_that_cannot_be_read_are_none"),
    ("ship: exit 0 with a pending line is read", AUTOPILOT,
     "    if code == 0 and not states <= set(_CHECK_EXITS[0]):\n",
     "    if False:\n",
     _S + "test_adapter_checks_that_cannot_be_read_are_none"),
    ("ship: exit 8 with nothing pending is read", AUTOPILOT,
     '    if code == 8 and "pending" not in states:\n',
     "    if False:\n",
     _S + "test_adapter_checks_that_cannot_be_read_are_none"),
    ("ship: any empty checks answer reads as none reported", AUTOPILOT,
     "        return [] if code == 1 and err.strip().startswith(_NO_CHECKS) else None\n",
     "        return []\n",
     _S + "test_adapter_checks_that_cannot_be_read_are_none"),
    ("ship: a cancelled check reads as pass", AUTOPILOT,
     '            "cancel": "fail"}\n',
     '            "cancel": "pass"}\n',
     _S + "test_adapter_checks_parse_the_text_output"),
    ("ship: an unknown bucket reads as pass", AUTOPILOT,
     '"state": _BUCKETS.get(parts[1], "unknown")})\n',
     '"state": _BUCKETS.get(parts[1], "pass")})\n',
     _S + "test_adapter_checks_an_unknown_bucket_reads_unknown"),
    ("ship: a bad autopilot.ship value is kept", AUTOPILOT,
     "    if ship not in SHIP_POLICIES:\n",
     "    if False:\n",
     _S + "test_ship_bad_value_reads_pr"),
    ("ship: knownFailures with a non-string is kept", AUTOPILOT,
     "    if not isinstance(known, list) or not all(isinstance(k, str) for k in known):\n",
     "    if not isinstance(known, list):\n",
     _S + "test_known_failures_bad_type_is_empty"),
    ("ship: ciTimeoutMinutes true reads as 1", AUTOPILOT,
     "    if isinstance(timeout, bool) or not isinstance(timeout, int) or timeout < 1:\n",
     "    if not isinstance(timeout, int) or timeout < 1:\n",
     _S + "test_ci_timeout_bad_value_reads_60"),
    # Round 1 of T-0011's review (Codex): one per new refusing branch.
    ("ship: the merge is not bound to the head that was checked", AUTOPILOT,
     '    return ["pr", "merge", str(number), "--merge", "--match-head-commit", head]\n',
     '    return ["pr", "merge", str(number), "--merge"]\n',
     _S + "test_ship_merge_command_is_merge_commit_without_admin"),
    ("ship: check names are trimmed before exact matching", AUTOPILOT,
     '        checks.append({"name": parts[0],\n',
     '        checks.append({"name": parts[0].strip(),\n',
     _S + "test_adapter_check_name_is_read_verbatim"),
    ("ship: check buckets are folded to a known one", AUTOPILOT,
     '"state": _BUCKETS.get(parts[1], "unknown")})\n',
     '"state": _BUCKETS.get(parts[1].strip().lower(), "unknown")})\n',
     _S + "test_adapter_bucket_is_read_verbatim"),
    ("ship: stderr beside the check rows is ignored", AUTOPILOT,
     "    if err.strip():\n        return None\n",
     "    if False:\n        return None\n",
     _S + "test_adapter_checks_that_cannot_be_read_are_none"),
    ("ship: exit 1 without a failing row is read", AUTOPILOT,
     '    if code == 1 and "fail" not in states:\n',
     "    if False:\n",
     _S + "test_adapter_checks_that_cannot_be_read_are_none"),
    ("ship: the gate is read once, before CI", AUTOPILOT,
     "        gate = _ship_gate(top, ticket)\n",
     "        pass\n",
     _S + "test_ship_rereads_the_review_families_while_waiting"),
    ("ship: a disarmed autopilot keeps merging", AUTOPILOT,
     '    if not config["armed"]:\n        gate["stop"]',
     '    if False:\n        gate["stop"]',
     _S + "test_ship_disarmed_while_waiting_stops"),
    ("ship: a receipt staled while CI ran still merges", AUTOPILOT,
     "    if not stands:\n",
     "    if False:\n",
     _S + "test_ship_receipt_staled_while_waiting_stops"),
    ("ship: a green past the deadline merges", AUTOPILOT,
     '        if decision["action"] == "merge" and not late:\n',
     '        if decision["action"] == "merge":\n',
     _S + "test_ship_green_after_the_deadline_stops"),
    ("ship: a merge queue is handed the PR", AUTOPILOT,
     "    if queue is not False:\n",
     "    if False:\n",
     _S + "test_ship_merge_queue_or_unreadable_queue_never_merges"),
    ("ship: an unreadable merge queue reads as none", AUTOPILOT,
     "    if queue is not False:\n",
     "    if queue:\n",
     _S + "test_ship_merge_queue_or_unreadable_queue_never_merges"),
    ("ship: a queue flag that is not a bool is read", AUTOPILOT,
     "    if not all(isinstance(flag, bool) for flag in flags):\n",
     "    if False:\n",
     _S + "test_adapter_merge_queue"),
)
