"""The T-0008 mutations: `crew_refresh_check.py`, the read-only check that
the code maps, diagrams and code graph a ticket's changes reach are current,
and the refresh-artifact allowance it defines for `scope_guard.py` and
`completion_audit.py`. Same tuple shape as `sabotage.py`'s MUTATIONS --
(label, target, find, replace, test) -- and appended to it there; `sabotage.py`
sits near `.pylintrc`'s max-module-lines, so this list lives apart. Run
`sabotage.py`, not this file.

Each one is a way the check could collapse an unknown or a stale artifact
into the pass the owner asked it never to give, or a way the allowance could
open a blocking hook wider than an approved ticket's refresh. Review round 1
(T-0008-tG6OPn) named five of them as surviving; each now has a test the
same mutation turns red. Review round 2 (T-0008-TPCCYg) added the ones
after the ROUND 2 marker: a fallback base trusted after the ticket's commits
reached the default branch, a measured-looking line printed over nothing
measured, and three "could not tell" cases read as fresh. Review round 3
(T-0008-refresh-check--5uPdfQ) added the ones after the ROUND 3 marker: a
recorded base trusted with the ticket's commits behind it, an artifact
keeping a measured status under a base that may hide the change, a quoted
name breaking the audit's hash, and a guard module with no pytest rule.
T-0094 added the fifteen after its marker: each test of `artifact_verdicts`'
reach-and-shape admission (reach, anchor moved, ancestor, in the base, INDEX
rows, rule bytes and removal, graph, rendered diagram, could-not-tell,
bookkeeping in the reach) removed or widened, and the audit ignoring the
verdicts, admitting a could-not-tell one, or dropping the reason. Its
approval-gate tests now perform a refresh the verdicts admit, so the
`_AUDIT_GATE` entries stay red with the verdicts in place. T-0094 review
round 1 added the sixteen after its marker: a diagram's reach and no-Anchors
branch, a base anchor git cannot resolve read as moved, a backwards anchor,
INDEX.md's deleted lines, every bookkeeping file or an added citation in the
reach, the rule renderer raising, the verdicts judged without approval, and a
verdict step's raise escaping the audit -- plus the stale-approval case the
round found no longer tested the gate (a test change: the `_AUDIT_GATE`
entries above are its mutations). T-0094 review round 2 added the nine after
its marker: an unreadable rule file admitted as regenerated or read as "bytes
differ", and each could-not-tell branch of `_sha_moved`, `_moved_from` and
`_rule_verdict` read as a move. T-0094 review round 3 added the twelve after
its marker: an anchor or provenance line added to a base copy with none read
as moved, INDEX.md judged as decoded lines (blind to a removed final newline,
CRLF and a BOM) or with a mode change or a failed diff admitted, and a rule
compared as decoded text, admitted when git would store it differently or
could not hash it, or refused as a CRLF checkout under core.autocrlf.
T-0094 review round 4 added the eight after its marker: an ambiguous short
base anchor (or one git cannot disambiguate or type) read as naming no
commit, a rendered diagram paired only with a lower-case source extension or
with another stem's source, and artifact dirs that cannot be resolved
dropping the could-not-tell reason (or every path, when the defaults raise).
T-0094 review round 5 added the five after its marker: a config, a rule or a
map whose presence lstat cannot prove (a parent the hook user cannot search)
read as absent, removed or deleted, and either proven-absence errno (ENOENT,
ENOTDIR) read as could-not-tell.
A mutation listed twice with different tests is on purpose: dropping the
approval condition must fail the unapproved, the `cli` and the stale case
each, not just whichever runs first.
"""
import os

CREW = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_S = os.path.join(CREW, "hooks", "scripts")
CHECK = os.path.join(_S, "crew_refresh_check.py")
GUARD = os.path.join(_S, "scope_guard.py")
AUDIT = os.path.join(_S, "completion_audit.py")
_T = "tests/test_refresh_check.py::"
_SG = "tests/test_scope_guard_refresh_artifacts.py::"
_CA = "tests/test_completion_audit_refresh_artifacts.py::"
_CAI = "tests/test_completion_audit.py::"
_TA = "tests/test_refresh_admission.py::"

_WORKTREE_DIFF = ("        return sorted(completion_audit.worktree_changes(root, sha, list(paths), "
                  "literal=True))\n")
_GUARD_GATE = '    if approval["status"] != "approved":\n        return False\n    if real_rel'
_AUDIT_GATE = '    if approval["status"] != "approved":\n        return paths, {}\n'
_INDEX_LINES = "    lines, mode = _diff_lines(out)\n"
_INDEX_DECODED = ("    lines, mode = [(f\"line {j + 1}\", t) for j, t in enumerate(_after.splitlines())"
                  " if t not in _before.splitlines()], False\n")
_AUDIT_ADMIT = ('    return [p for p in paths if verdicts.get(p, (False, ""))[0] is not True], '
                'verdicts\n')
# The pre-round-2 listing exactly (review round 3's NIT on :182): newline-split
# through `_git_lines`, so a name git C-quotes never matches. Dropping only
# `-z` would leave one unsplit string, which fails every name, quoted or not.
_UNTRACKED = ("        untracked = {p for p in completion_audit._git_fields(  "
              "# pylint: disable=protected-access\n"
              '            top, ["ls-files", "-z", "--others", "--exclude-standard"]) if p}\n')
_DEMOTE = '        if item["status"] in (FRESH, STALE):\n'
_RECORD_DOUBT = "        doubt = _named_behind(top, base, ticket)\n"
VERIFY = os.path.join(os.path.dirname(os.path.dirname(CREW)), ".crew", "verify.json")

REFRESH_MUTATIONS = (
    ("the refresh check reports fresh whatever the artifacts say", CHECK,
     '    result = {"status": overall, "reason": f"scope base {base[:12]} ({why})", "stop": None,\n',
     '    result = {"status": FRESH, "reason": f"scope base {base[:12]} ({why})", "stop": None,\n',
     _T + "test_codemap_citing_changed_path_behind_is_stale"),
    ("an unknown artifact reads as fresh", CHECK,
     'UNKNOWN = "unknown"\n',
     'UNKNOWN = "fresh"\n',
     _T + "test_graphify_missing_is_unknown"),
    ("the freshness diff is <anchor>..HEAD, blind to an uncommitted edit", CHECK,
     _WORKTREE_DIFF,
     '        return _git_lines(root, "diff", "--name-only", f"{sha}..HEAD", "--", *paths)\n',
     _T + "test_uncommitted_edit_in_cited_path_is_stale"),
    ("the freshness diff is `git diff`, which rewrites the index", CHECK,
     _WORKTREE_DIFF,
     '        return _git_lines(root, "diff", "--name-only", sha, "--", *paths)\n',
     _T + "test_a_library_call_never_rewrites_the_index"),
    ("an untracked cited file is not a change", CHECK,
     "    new = [p for p in reached if p in untracked]\n",
     "    new = []\n",
     _T + "test_untracked_cited_file_is_stale"),
    ("every diagram reads as unanchored", CHECK,
     "        anchor = _DIAGRAM_ANCHOR_RE.search(body)\n",
     "        anchor = None\n",
     _T + "test_diagram_refreshed_is_fresh"),
    ("a fallback base equal to HEAD is trusted", CHECK,
     "    if hides:\n",
     "    if False:\n",
     _T + "test_fallback_equal_to_head_on_a_fresh_branch_is_unknown"),
    ("every fallback base reads unknown", CHECK,
     "    hides = head is None or base == head\n",
     "    hides = True\n",
     _T + "test_fallback_base_on_a_branch_ahead_of_main_is_judged_and_marked"),
    ("a line judged against a fallback base is not marked", CHECK,
     '        item["reason"] += " [fallback base]"\n',
     "        pass\n",
     _T + "test_fallback_base_on_a_branch_ahead_of_main_is_judged_and_marked"),
    ("a dot-directory citation is not parsed", CHECK,
     '    r"`(\\.?[A-Za-z0-9_]',
     '    r"`([A-Za-z0-9_]',
     _T + "test_codemap_dot_directory_citation_is_in_scope"),
    ("a line-range citation is not parsed", CHECK,
     '(?::\\d+(?:-\\d+)?)?`"\n',
     '(?::\\d+)?`"\n',
     _T + "test_codemap_line_range_citation_is_in_scope"),
    ("a trailing-slash prose mention reads as a directory citation", CHECK,
     '(?:/[A-Za-z0-9_.@+-]+)*)(?::\\d+',
     '(?:/[A-Za-z0-9_.@+-]+)*/?)(?::\\d+',
     _T + "test_a_trailing_slash_prose_mention_is_not_a_citation"),
    ("a code map citing no path is out of scope", CHECK,
     "        if not cited:\n            if changed:\n",
     "        if not cited:\n            if False:\n",
     _T + "test_codemap_with_no_parseable_citation_is_unknown"),
    ("release bookkeeping stales artifacts", CHECK,
     "    return any(crew_ticket.glob_match(path, glob) for glob in RELEASE_BOOKKEEPING)\n",
     "    return False\n",
     _T + "test_release_bookkeeping_alone_stales_nothing"),
    ("a cited directory reaches nothing under it", CHECK,
     '    return bool(entry) and (path == entry or path.startswith(entry + "/"))\n',
     "    return bool(entry) and path == entry\n",
     _T + "test_diagram_anchors_naming_a_directory_reach_files_under_it"),
    ("an anchor naming no commit is a stop, not a refresh", CHECK,
     '"squash-merged or rebased branch?); a refresh re-anchors it"), True\n',
     '"squash-merged or rebased branch?); a refresh re-anchors it"), False\n',
     _T + "test_an_anchor_naming_no_commit_is_refreshable"),
    ("every unknown line says refresh", CHECK,
     '        if item["refreshable"]:\n',
     '        if item["status"] in (STALE, UNKNOWN):\n',
     _T + "test_graphify_missing_is_a_stop_not_a_refresh"),
    ("the graph always names graphify update", CHECK,
     '    command = ("graphify update ." if info["reportTracked"]\n',
     '    command = ("graphify update ." if True\n',
     _T + "test_graph_without_a_tracked_report_names_the_code_only_build"),
    ("an artifact dir matches by string prefix", CHECK,
     "        if len(folded) > len(stem) and folded[:len(stem)] == stem:\n",
     '        if "/".join(folded).startswith("/".join(stem)):\n',
     _T + "test_is_refresh_artifact_matches_whole_segments_only[.crew/codemapX/crew.md-False]"),
    ("an artifact path keeps its '..' segments", CHECK,
     '    if any(p in ("", ".", "..") for p in parts):\n',
     "    if False:\n",
     _T + "test_is_refresh_artifact_matches_whole_segments_only[.crew/codemap/../config.json-False]"),
    ("a configured dir naming the repo root is an artifact dir", CHECK,
     '        if rel in ("", ".") or first in ("..", os.path.normcase(".git")):\n',
     "        if False:\n",
     _T + "test_a_configured_dir_naming_the_repo_root_is_never_an_artifact_dir"),
    ("an artifact dir reached through a link is kept", CHECK,
     "        if os.path.normcase(real) not in named:\n            continue\n",
     "        if False:\n            continue\n",
     _T + "test_an_artifact_dir_reached_through_a_link_is_dropped"),
    ("a linked artifact dir opens its target to the guard", CHECK,
     "        if os.path.normcase(real) not in named:\n            continue\n",
     "        if False:\n            continue\n",
     _SG + "test_an_artifact_dir_that_is_itself_a_link_opens_nothing[other/keep.py-module]"),
    ("the guard's artifact allowance ignores approval (unapproved)", GUARD,
     _GUARD_GATE, _GUARD_GATE.replace('approval["status"] != "approved"', "False"),
     _SG + "test_an_unapproved_ticket_cannot_write_a_refresh_artifact[module]"),
    ("the guard's artifact allowance ignores approval (cli receipt)", GUARD,
     _GUARD_GATE, _GUARD_GATE.replace('approval["status"] != "approved"', "False"),
     _SG + "test_a_cli_approval_cannot_write_a_refresh_artifact[module]"),
    ("the guard's artifact allowance ignores approval (stale)", GUARD,
     _GUARD_GATE, _GUARD_GATE.replace('approval["status"] != "approved"', "False"),
     _SG + "test_a_stale_approval_cannot_write_a_refresh_artifact[module]"),
    ("the guard's artifact allowance follows a link out of the worktree", GUARD,
     "    if real_rel is None:\n        return False\n",
     "    if False:\n        return False\n",
     _SG + "test_a_link_in_an_artifact_dir_pointing_out_of_the_worktree_is_blocked[module]"),
    ("the audit's artifact allowance ignores approval (unapproved)", AUDIT,
     _AUDIT_GATE, _AUDIT_GATE.replace('approval["status"] != "approved"', "False"),
     _CA + "test_an_unapproved_ticket_cannot_leave_a_refresh_artifact_changed"),
    ("the audit's artifact allowance ignores approval (cli receipt)", AUDIT,
     _AUDIT_GATE, _AUDIT_GATE.replace('approval["status"] != "approved"', "False"),
     _CA + "test_a_cli_approval_cannot_leave_a_refresh_artifact_changed"),
    ("the audit's artifact allowance ignores approval (stale)", AUDIT,
     _AUDIT_GATE, _AUDIT_GATE.replace('approval["status"] != "approved"', "False"),
     _CA + "test_a_stale_approval_cannot_leave_a_refresh_artifact_changed"),
    ("the audit lists paths with `git diff`, which rewrites the index", AUDIT,
     '    fields = _git_fields(top, ["diff-index", "--raw", "-z", "-M", sha, "--"] + pathspec,\n',
     '    fields = _git_fields(top, ["diff", "--raw", "-z", "-M", sha, "--"] + pathspec,\n',
     _CAI + "test_the_audit_never_rewrites_the_index"),
    ("the audit counts a stat-dirty unchanged file as changed", AUDIT,
     "    return paths | (set(suspects) - _unchanged(top, suspects))\n",
     "    return paths | set(suspects)\n",
     _CAI + "test_a_stat_dirty_unchanged_file_is_not_a_change"),
    ("the audit misses a mode change with the same content", AUDIT,
     '        if (status == "M" and src_mode == dst_mode and src_mode in _FILE_MODES\n',
     '        if (status == "M" and src_mode in _FILE_MODES\n',
     _CAI + "test_a_mode_change_with_the_same_content_is_a_change"),
    # ROUND 2 (T-0008-TPCCYg)
    ("a fallback base is trusted on the default branch", CHECK,
     "    if branch[0] in (name, default):\n",
     "    if False:\n",
     _T + "test_fallback_on_main_with_pushed_commits_is_unknown"),
    ("a fallback base is trusted with the ticket's commits behind it", CHECK,
     "    if named:\n",
     "    if False:\n",
     _T + "test_fallback_after_a_fast_forward_into_main_is_unknown"),
    ("a detached HEAD reads as a branch that is not the default", CHECK,
     '    branch = _git_lines(top, "symbolic-ref", "--quiet", "--short", "HEAD")\n',
     '    branch = _git_lines(top, "symbolic-ref", "--quiet", "--short", "HEAD") or ["x"]\n',
     _T + "test_fallback_with_a_detached_head_is_unknown"),
    ("an unknown scope base prints no stop on the top line", CHECK,
     '    if result.get("stop"):\n',
     "    if False:\n",
     _T + "test_hides_case_renders_a_stop_on_the_top_line"),
    ("the no-codemap-cites line prints under unknown", CHECK,
     "        if result[\"status\"] in (FRESH, STALE):\n",
     "        if True:\n",
     _T + "test_no_codemap_cites_line_only_when_fresh_or_stale[unknown-False]"),
    ("the untracked list is newline-split, so a quoted name never matches", CHECK,
     _UNTRACKED,
     '        untracked = set(_git_lines(top, "ls-files", "--others", "--exclude-standard") or [])\n',
     _T + "test_an_untracked_file_git_would_quote_stales_the_graph"),
    ("a corrupt config reads as the defaults", CHECK,
     '            return None, f".crew/{name} is not valid JSON"\n',
     "            return {}, None\n",
     _T + "test_a_corrupt_config_is_unknown_not_the_defaults[crew-json-truncated]"),
    ("an unreadable config falls through to the next file", CHECK,
     '            return None, f".crew/{name} could not be read"\n',
     "            continue\n",
     _T + "test_an_unreadable_config_is_not_skipped_for_the_next_one"),
    ("an unlistable artifact dir holds no artifacts", CHECK,
     "        return None, exc.strerror or type(exc).__name__\n",
     "        return [], None\n",
     _T + "test_an_unlistable_artifact_dir_is_unknown[codemap-.crew/codemap]"),
    ("an unreadable code map reads as citing no path", CHECK,
     "        body = read_text(os.path.join(mapdir, name))\n",
     '        body = read_text(os.path.join(mapdir, name)) or ""\n',
     _T + "test_an_unreadable_codemap_is_unknown"),
    ("filing a TODO item stales every map citing TODO.md", CHECK,
     '    "TODO.md",\n',
     "",
     _T + "test_filing_a_todo_item_alone_stales_nothing"),
    # ROUND 3 (T-0008-refresh-check--5uPdfQ)
    ("a recorded base is trusted with the ticket's commits behind it", CHECK,
     _RECORD_DOUBT, "        doubt = None\n",
     _T + "test_a_record_after_a_fast_forward_into_main_is_unknown"),
    ("a recorded base behind the default tip is trusted with the ticket behind it", CHECK,
     _RECORD_DOUBT, "        doubt = None\n",
     _T + "test_a_record_behind_the_default_tip_with_the_ticket_behind_it_is_unknown"),
    ("an artifact keeps its measured fresh under a fallback that may hide", CHECK,
     _DEMOTE, "        if False:\n",
     _T + "test_no_artifact_keeps_a_measured_fresh_under_a_fallback_that_may_hide"),
    ("--json keeps a measured fresh under a fallback that may hide", CHECK,
     _DEMOTE, "        if False:\n",
     _T + "test_no_json_artifact_reads_fresh_under_a_fallback_that_may_hide"),
    ("an artifact keeps its measured fresh under a record that may hide", CHECK,
     _DEMOTE, "        if False:\n",
     _T + "test_no_artifact_keeps_a_measured_fresh_under_a_record_that_may_hide"),
    ("an artifact keeps its measured status under a fallback equal to HEAD", CHECK,
     _DEMOTE, "        if False:\n",
     _T + "test_no_artifact_keeps_a_measured_status_under_a_fallback_equal_to_head"),
    ("a stat-dirty name starting with a quote reaches hash-object unquoted", AUDIT,
     "    if not path.startswith('\"'):\n        return path\n",
     "    if True:\n        return path\n",
     _CAI + "test_a_stat_dirty_file_whose_name_starts_with_a_quote_is_not_a_change"),
    ("an edit to scope_guard.py runs no pytest rule", VERIFY,
     '                "plugin/crew/hooks/scripts/scope_guard.py",\n', "",
     _T + "test_every_module_the_refresh_allowance_touches_runs_a_pytest_rule[scope_guard.py]"),
    # T-0094 (reach-gated, re-anchor-shaped admission)
    ("a re-anchored map no changed path reaches is admitted", CHECK,
     "    if not _reached(_cited(before), reach):\n",
     "    if False:\n",
     _TA + "test_a_re_anchored_map_no_changed_path_reaches_is_refused"),
    ("a map re-anchored to the same commit by another name is admitted", CHECK,
     "    if was[0] == now:\n",
     "    if False:\n",
     _TA + "test_a_map_re_anchored_to_the_same_commit_by_another_name_is_refused"),
    ("an anchor on a commit HEAD cannot reach is admitted", CHECK,
     "    if not ancestor:\n",
     "    if False:\n",
     _TA + "test_a_map_anchored_to_a_commit_not_reachable_from_head_is_refused"),
    ("a map absent from the base reads as a re-anchor", CHECK,
     '    if state == "absent":\n        return None, None, (False, "new file, not a re-anchor")\n',
     '    if state == "absent":\n        before, state = "", "ok"\n',
     _TA + "test_a_new_map_is_not_a_re_anchor"),
    ("an INDEX.md line that is no row passes as one", CHECK,
     "        if not row or row.group(1) not in admitted:\n",
     "        if row and row.group(1) not in admitted:\n",
     _TA + "test_an_index_edit_outside_a_re_anchored_row_is_refused"),
    ("a rule's bytes are not compared with expected_rules", CHECK,
     "            if data == want:\n",
     "            if True:\n",
     _TA + "test_a_hand_edited_rule_is_refused"),
    ("a removed rule is admitted without the generated marker", CHECK,
     "    if state == \"ok\" and crew_instructions.MARKER in before[:2000]:\n",
     "    if state == \"ok\":\n",
     _TA + "test_a_rule_removed_that_was_not_generated_is_refused"),
    ("a rule removed while its map still expects it is admitted", CHECK,
     "    if key in expected:\n",
     "    if False:\n",
     _TA + "test_a_rule_removed_while_its_map_still_expects_it_is_refused"),
    ("the graph is admitted with no code change", CHECK,
     '    judge("graph", lambda rel: (True, "rebuilt after a code change") if graph_code\n',
     '    judge("graph", lambda rel: (True, "rebuilt after a code change") if True\n',
     _TA + "test_a_graph_rebuild_with_no_code_change_is_refused"),
    ("a rendered diagram is admitted without its source", CHECK,
     "    for source in sources:\n        if out.get(source, (False,))[0] is True:\n",
     "    for source in [rel]:\n        if True:\n",
     _TA + "test_a_rendered_diagram_whose_source_was_not_re_anchored_is_refused"),
    ("could-not-tell on a map collapses into admitted", CHECK,
     '        return None, None, (None, f"{COULD_NOT_TELL}: base copy {state}")\n',
     '        return None, None, (True, f"{COULD_NOT_TELL}: base copy {state}")\n',
     _TA + "test_a_git_failure_while_judging_a_map_is_could_not_tell"),
    ("a manifest bump is dropped from the admission reach", CHECK,
     "    return not _bookkeeping(path) or any(crew_ticket.glob_match(path, glob)\n",
     "    return not _bookkeeping(path) and any(crew_ticket.glob_match(path, glob)\n",
     _TA + "test_a_version_bump_reaches_the_map_citing_the_manifest[root]"),
    ("the audit drops every artifact whatever its verdict", AUDIT,
     _AUDIT_ADMIT, "    return [p for p in paths if p not in verdicts], verdicts\n",
     _CA + "test_a_map_edited_without_moving_its_anchor_fails_the_audit"),
    ("the audit admits a could-not-tell verdict", AUDIT,
     _AUDIT_ADMIT, _AUDIT_ADMIT.replace("is not True", "is False"),
     _CA + "test_a_could_not_tell_verdict_fails_the_audit_and_says_so"),
    ("the audit does not print why an artifact was refused", AUDIT,
     '        return f"{shown(path)} [{shown(verdicts[path][1])}]"\n',
     "        return shown(path)\n",
     _CA + "test_a_could_not_tell_verdict_fails_the_audit_and_says_so"),
    # T-0094 review round 1
    ("a re-anchored diagram no changed path reaches is admitted", CHECK,
     "        reached = _reached(declared, reach)\n    if not reached:\n",
     "        reached = _reached(declared, reach)\n    if False:\n",
     _TA + "test_a_re_anchored_diagram_no_changed_path_reaches_is_refused"),
    ("a diagram with no Anchors line is reached by any change, code or not", CHECK,
     "        reached = code\n",
     "        reached = reach\n",
     _TA + "test_a_diagram_with_no_anchors_line_is_refused_with_no_code_change"),
    ("a diagram with no Anchors line is reached by nothing", CHECK,
     "        reached = code\n",
     "        reached = []\n",
     _TA + "test_a_diagram_with_no_anchors_line_is_reached_by_any_code_change"),
    ("an unchanged anchor git cannot resolve reads as moved", CHECK,
     '    if old == new:\n        return False, "anchor did not move"\n',
     '    if False:\n        return False, "anchor did not move"\n',
     _TA + "test_an_unchanged_anchor_git_cannot_resolve_is_not_a_move"),
    ("a base anchor git cannot resolve reads as moved", CHECK,
     '        return None, f"{COULD_NOT_TELL}: git could not resolve the base anchor {old[:12]}"\n',
     '        return True, f"{COULD_NOT_TELL}: git could not resolve the base anchor {old[:12]}"\n',
     _TA + "test_a_base_anchor_git_cannot_resolve_is_could_not_tell[rev-parse]"),
    ("a base anchor git cannot read reads as moved", CHECK,
     '        return None, f"{COULD_NOT_TELL}: git could not read the base anchor {old[:12]}"\n',
     '        return True, f"{COULD_NOT_TELL}: git could not read the base anchor {old[:12]}"\n',
     _TA + "test_a_base_anchor_git_cannot_resolve_is_could_not_tell[cat-file]"),
    ("an anchor moved backwards is admitted", CHECK,
     "    if not forward:\n",
     "    if False:\n",
     _TA + "test_a_map_anchored_backwards_is_refused"),
    ("a base anchor off HEAD's history is never moved from", CHECK,
     '    if not behind_head:\n        return True, "re-anchored"\n',
     '    if not behind_head:\n        return False, "re-anchored"\n',
     _TA + "test_a_map_whose_base_anchor_is_off_heads_history_is_admitted_when_re_anchored"),
    ("a citation the edit adds makes the map reached", CHECK,
     "    if not _reached(_cited(before), reach):\n",
     "    if not _reached(_cited(before) + _cited(after), reach):\n",
     _TA + "test_a_citation_the_edit_adds_does_not_make_the_map_reached"),
    ("all release bookkeeping reaches a map", CHECK,
     "    return not _bookkeeping(path) or any(crew_ticket.glob_match(path, glob)\n",
     "    return True or any(crew_ticket.glob_match(path, glob)\n",
     _TA + "test_release_bookkeeping_other_than_a_manifest_reaches_no_map[CHANGELOG.md]"),
    ("all release bookkeeping reaches a map, through the audit", CHECK,
     "    return not _bookkeeping(path) or any(crew_ticket.glob_match(path, glob)\n",
     "    return True or any(crew_ticket.glob_match(path, glob)\n",
     _CA + "test_a_bookkeeping_bump_does_not_admit_a_rewrite_of_the_map_citing_it"),
    ("a deleted INDEX.md line is never judged", CHECK,
     '            removed.append((f"base line {old}", raw[1:].decode("utf-8", "surrogateescape")))\n',
     "            pass\n",
     _TA + "test_an_index_line_deleted_outside_a_re_anchored_row_is_refused[another-maps-row]"),
    ("a rule renderer that raises reads as expecting nothing", CHECK,
     '        return f"expected_rules raised {type(exc).__name__}"\n',
     "        return {}\n",
     _TA + "test_a_rule_renderer_that_raises_is_could_not_tell[removed]"),
    ("the audit judges an unapproved ticket's artifacts", AUDIT,
     _AUDIT_GATE, '    if False:\n        return paths, {}\n',
     _CA + "test_an_unapproved_ticket_is_never_judged_for_reach_or_shape"),
    ("a verdict step that raises escapes the audit", AUDIT,
     ('    except Exception as exc:  # noqa: BLE001  pylint: disable=broad-except\n'
      '        why = f"{crew_refresh_check.COULD_NOT_TELL}'),
     ('    except ValueError as exc:  # noqa: BLE001  pylint: disable=broad-except\n'
      '        why = f"{crew_refresh_check.COULD_NOT_TELL}'),
     _CA + "test_a_verdict_step_that_raises_fails_the_audit_closed[artifact_verdicts]"),
    ("artifact dirs that cannot be resolved escape the audit", AUDIT,
     "    except Exception as exc:  # noqa: BLE001  pylint: disable=broad-except\n"
     "        why = (f\"{crew_refresh_check.COULD_NOT_TELL}: {type(exc).__name__} \"\n",
     "    except ValueError as exc:  # noqa: BLE001  pylint: disable=broad-except\n"
     "        why = (f\"{crew_refresh_check.COULD_NOT_TELL}: {type(exc).__name__} \"\n",
     _CA + "test_a_verdict_step_that_raises_fails_the_audit_closed[refresh_artifact_paths]"),
    # T-0094 review round 2
    ("an unreadable rule no map expects is judged as if read", CHECK,
     '        if data is None:\n            return None, f"{COULD_NOT_TELL}: could not read {rel}"\n',
     '        if False:\n            return None, f"{COULD_NOT_TELL}: could not read {rel}"\n',
     _TA + "test_an_unreadable_rule_is_could_not_tell[unexpected]"),
    ("an unreadable rule a map expects reads as bytes differ", CHECK,
     '            return None, f"{COULD_NOT_TELL}: could not read {rel}"\n',
     '            return False, "bytes differ"\n',
     _TA + "test_an_unreadable_rule_is_could_not_tell[expected]"),
    ("a new anchor git could not check reads as moved", CHECK,
     '        return None, f"{COULD_NOT_TELL}: git could not run"\n',
     '        return True, "re-anchored"\n',
     _TA + "test_a_new_anchor_git_cannot_judge_is_could_not_tell[cat-file-none]"),
    ("a new anchor git errored reading reads as moved", CHECK,
     '        return None, f"{COULD_NOT_TELL}: git exited {code} reading anchor {new}"\n',
     '        return True, "re-anchored"\n',
     _TA + "test_a_new_anchor_git_cannot_judge_is_could_not_tell[cat-file-129]"),
    ("a new anchor git cannot place behind HEAD reads as moved", CHECK,
     '        return None, f"{COULD_NOT_TELL}: git could not say whether {new[:12]} is behind HEAD"\n',
     '        return True, "re-anchored"\n',
     _TA + "test_a_new_anchor_git_cannot_judge_is_could_not_tell[ancestor-129]"),
    ("a new anchor git cannot resolve reads as moved", CHECK,
     '        return None, f"{COULD_NOT_TELL}: git could not resolve {new[:12]}"\n',
     '        return True, "re-anchored"\n',
     _TA + "test_a_new_anchor_git_cannot_judge_is_could_not_tell[rev-parse]"),
    ("a base anchor git cannot place behind HEAD reads as moved", CHECK,
     '        return None, f"{COULD_NOT_TELL}: git could not say whether {old[:12]} is behind HEAD"\n',
     '        return True, "re-anchored"\n',
     _TA + "test_a_moved_anchor_git_cannot_order_is_could_not_tell[behind-head]"),
    ("an anchor git cannot order after the base reads as moved", CHECK,
     '        return None, f"{COULD_NOT_TELL}: git could not say whether {now[:12]} follows {old[:12]}"\n',
     '        return True, "re-anchored"\n',
     _TA + "test_a_moved_anchor_git_cannot_order_is_could_not_tell[forward]"),
    ("a removed rule whose base copy git cannot read is admitted", CHECK,
     '    return None, f"{COULD_NOT_TELL}: base copy {state}"\n',
     '    return True, "a generated rule no map expects, removed"\n',
     _TA + "test_a_removed_rule_whose_base_copy_git_cannot_read_is_could_not_tell"),
    # T-0094 review round 3
    ("an anchor added where the base map had none reads as moved", CHECK,
     '        return False, "the base copy has no anchor, so nothing moved from it"\n',
     '        return True, "re-anchored"\n',
     _TA + "test_an_anchor_added_where_the_base_copy_had_none_is_refused[map]"),
    ("provenance added where the base diagram had none reads as moved", CHECK,
     '        return False, "the base copy has no anchor, so nothing moved from it"\n',
     '        return True, "re-anchored"\n',
     _TA + "test_an_anchor_added_where_the_base_copy_had_none_is_refused[diagram]"),
    ("INDEX.md compared as decoded lines, blind to a removed final newline", CHECK,
     _INDEX_LINES, _INDEX_DECODED,
     _TA + "test_an_index_byte_edit_with_no_re_anchored_map_is_refused[final-newline-removed]"),
    ("INDEX.md compared as decoded lines, blind to CRLF", CHECK,
     _INDEX_LINES, _INDEX_DECODED,
     _TA + "test_an_index_byte_edit_with_no_re_anchored_map_is_refused[crlf]"),
    ("INDEX.md compared as decoded lines, blind to a BOM", CHECK,
     _INDEX_LINES, _INDEX_DECODED,
     _TA + "test_an_index_byte_edit_with_no_re_anchored_map_is_refused[bom]"),
    ("an INDEX.md mode change is admitted", CHECK,
     "    if mode:\n",
     "    if False:\n",
     _TA + "test_an_index_mode_change_with_no_re_anchored_map_is_refused"),
    ("a git diff of INDEX.md that failed reads as rows only", CHECK,
     "    if code != 0:\n        why = ",
     "    if False:\n        why = ",
     _TA + "test_an_index_git_cannot_diff_is_could_not_tell[129]"),
    ("a rule compared as decoded text, blind to CRLF", CHECK,
     "            if data == want:\n",
     "            if read_text(path) == expected.get(key):\n",
     _TA + "test_a_rule_whose_bytes_are_not_the_generated_bytes_is_refused[crlf]"),
    ("a rule compared as decoded text, blind to a BOM", CHECK,
     "            if data == want:\n",
     "            if read_text(path) == expected.get(key):\n",
     _TA + "test_a_rule_whose_bytes_are_not_the_generated_bytes_is_refused[bom]"),
    ("a rule git stores differently is admitted", CHECK,
     "            if got == wanted:\n",
     "            if True:\n",
     _TA + "test_a_rule_whose_bytes_are_not_the_generated_bytes_is_refused[crlf]"),
    ("a CRLF checkout of a regenerated rule under autocrlf is refused", CHECK,
     "            if got == wanted:\n",
     "            if False:\n",
     _TA + "test_a_crlf_checkout_under_autocrlf_is_judged_as_git_stores_it[rule]"),
    ("a rule git cannot hash is admitted", CHECK,
     '                return None, f"{COULD_NOT_TELL}: git could not hash {rel}"\n',
     '                return True, "regenerated"\n',
     _TA + "test_a_rule_git_cannot_hash_is_could_not_tell[129]"),
    # T-0094 review round 4
    ("an ambiguous base anchor reads as naming no commit", CHECK,
     '        return None, f"{COULD_NOT_TELL}: base anchor {old[:12]} is ambiguous"\n',
     '        return True, "re-anchored"\n',
     _TA + "test_an_ambiguous_base_anchor_is_could_not_tell"),
    ("a base anchor git cannot disambiguate reads as naming no commit", CHECK,
     '            return None, f"{COULD_NOT_TELL}: git could not say whether {old[:12]} names a commit"\n',
     '            return True, "re-anchored"\n',
     _TA + "test_a_base_anchor_git_cannot_disambiguate_is_could_not_tell"),
    ("every cat-file exit 128 on a base anchor reads as naming no commit", CHECK,
     "    if code == 128:\n        missing = _names_no_commit(root, old)\n",
     '    if code == 128:\n        return True, "re-anchored"\n',
     _TA + "test_an_ambiguous_base_anchor_is_could_not_tell"),
    ("a candidate git cannot type is skipped as naming no commit", CHECK,
     "        if not kind:\n            return None\n",
     "        if not kind:\n            continue\n",
     _TA + "test_a_base_anchor_whose_candidates_git_cannot_type_is_could_not_tell"),
    ("a rendered diagram pairs only with a lower-case source extension", CHECK,
     "               and os.path.splitext(p)[1].lower() in _DIAGRAM_EXTS]\n",
     "               and os.path.splitext(p)[1] in _DIAGRAM_EXTS]\n",
     _TA + "test_a_rendered_diagram_beside_an_admitted_source_is_admitted_whatever_its_case[.MMD]"),
    ("a rendered diagram pairs with any admitted source, whatever its stem", CHECK,
     "               and os.path.splitext(p)[0] == stem\n",
     "               and True\n",
     _TA + "test_a_rendered_diagram_is_not_paired_with_another_stems_admitted_source"),
    ("artifact dirs that cannot be resolved drop the reason", AUDIT,
     "        return {p: (None, why) for p in _default_artifacts(crew_refresh_check, top, paths)}\n",
     "        return {}\n",
     _CA + "test_artifact_dirs_that_cannot_be_resolved_fail_the_audit_as_could_not_tell"),
    ("default artifact dirs that raise too leave every path bare", AUDIT,
     "        return list(paths)\n",
     "        return []\n",
     _CA + "test_a_verdict_step_that_raises_fails_the_audit_closed[refresh_artifact_paths]"),
    # T-0094 review round 5
    ("a config whose presence lstat cannot prove reads as absent", CHECK,
     '            return None, f"could not tell whether .crew/{name} exists: {why}"\n',
     "            continue\n",
     _TA + "test_a_config_whose_presence_cannot_be_proven_is_judged_by_its_errno[denied]"),
    ("a rule whose presence lstat cannot prove reads as removed", CHECK,
     '        return None, f"{COULD_NOT_TELL}: whether {rel} exists: {why}"\n    if present:\n',
     "        present = False\n    if present:\n",
     _TA + "test_a_generated_rule_whose_absence_cannot_be_proven_is_could_not_tell[denied]"),
    ("a map whose presence lstat cannot prove reads as deleted", CHECK,
     '        return None, None, (None, f"{COULD_NOT_TELL}: whether {rel} exists: {why}")\n',
     '        return None, None, (False, "deleted, not a re-anchor")\n',
     _TA + "test_a_map_whose_presence_cannot_be_proven_is_could_not_tell"),
    ("a parent that is not a directory is could-not-tell, not absent", CHECK,
     '    except (FileNotFoundError, NotADirectoryError):\n        return False, ""\n',
     '    except FileNotFoundError:\n        return False, ""\n',
     _TA + "test_a_config_whose_presence_cannot_be_proven_is_judged_by_its_errno[not-a-dir]"),
    ("a path lstat proves missing is could-not-tell, not removed", CHECK,
     '    except (FileNotFoundError, NotADirectoryError):\n        return False, ""\n',
     '    except (FileNotFoundError, NotADirectoryError):\n        return None, "absent"\n',
     _TA + "test_a_generated_rule_whose_absence_cannot_be_proven_is_could_not_tell[removed]"),
)
