"""The L-0574 mutations: `review_checks.py` and `review_run.py`'s pre-review
gate. Same tuple shape as `sabotage.py`'s MUTATIONS -- (label, target, find,
replace, test) -- and appended to it there. Run `sabotage.py`, not this file.

Each is a way the pre-review checks could read an unknown as a pass, let a
new finding through, or spend a round they promised not to.
"""
import os

CREW = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHECKS = os.path.join(CREW, "hooks", "scripts", "review_checks.py")
RUN = os.path.join(CREW, "hooks", "scripts", "review_run.py")
_C = "tests/test_review_checks.py::"
_R = "tests/test_review_run_prereview.py::"

PREREVIEW_MUTATIONS = (
    ("a check that could not run reports pass", CHECKS,
     "        result.update(status=COULD_NOT, detail=_detail(exc))\n",
     "        result.update(status=PASS, detail=_detail(exc))\n",
     _C + "test_could_not_check_cases"),
    ("the base count is ignored, every finding is new", CHECKS,
     '        added = n - counts["base"][key]\n',
     "        added = n\n",
     _C + "test_existing_finding_moved_is_not_new"),
    ("a parse abort is not treated as unchecked", CHECKS,
     "                if abort:\n                    unparsed.add(rel)\n",
     "                if False:\n                    unparsed.add(rel)\n",
     _C + "test_parse_abort_either_side"),
    ("shellcheck's error exit is accepted as a run", CHECKS,
     '    _expect(proc, (0, 1), "shellcheck")\n',
     '    _expect(proc, (0, 1, 4), "shellcheck")\n',
     _C + "test_could_not_check_cases"),
    ("the linter config is dropped from the checked trees", CHECKS,
     "            with_base = _materialise(root, selected, _config_blobs(root, manifest), tmp)\n",
     "            with_base = _materialise(root, selected, {}, tmp)\n",
     _C + "test_path_dependent_config_applies"),
    ("a missing record reads as None", CHECKS,
     '        return {"result": NOT_RECORDED, "reason": f"no {RESULT_FILE} in the scratch directory"}\n',
     "        return None\n",
     _C + "test_a_missing_or_torn_record_is_not_recorded_never_none"),
    ("exit 1 with no findings is accepted as clean", CHECKS,
     "    if (proc.returncode == 1) != bool(rows):\n",
     "    if False:\n",
     _C + "test_could_not_check_cases"),
    ("an unreadable base drops the linter config silently", CHECKS,
     '    if _git(root, "rev-parse", "--verify", "--quiet", f"{base}^{{commit}}").returncode != 0:\n',
     "    if False:\n",
     _C + "test_could_not_check_cases"),
    ("a record of the wrong shape is copied into review.json", CHECKS,
     "    if not (payload.get(\"result\") in (PASS, FAIL, COULD_NOT, NOT_CONFIGURED)\n",
     "    if False and not (payload.get(\"result\") in (PASS, FAIL, COULD_NOT, NOT_CONFIGURED)\n",
     _C + "test_a_record_of_the_wrong_shape_is_not_recorded"),
    ("a line number inside a message makes a moved finding new", CHECKS,
     "        text = pattern.sub(replacement, text)\n",
     "        text = text\n",
     _C + "test_line_numbers_inside_a_message_do_not_make_a_finding_new"),
    ("every digit is normalised, so a changed value cancels against the base", CHECKS,
     "        text = pattern.sub(replacement, text)\n    return text\n",
     '        text = pattern.sub(replacement, text)\n    return re.sub(r"\\d+", "N", text)\n',
     _C + "test_digits_that_are_not_positions_still_tell_findings_apart"),
    ("a parse failure in one file hides a new finding in another", CHECKS,
     "    if new:\n        detail = ",
     "    if new and not aborted:\n        detail = ",
     _C + "test_a_parse_failure_does_not_hide_a_new_finding_elsewhere"),
    ("--allow-unverified passes a new finding hidden by a parse failure", CHECKS,
     "    if new:\n        detail = ",
     "    if new and not aborted:\n        detail = ",
     _R + "test_allow_unverified_never_passes_a_new_finding_beside_a_parse_failure"),
    ("a row with no message is accepted with an empty one", CHECKS,
     "    if not isinstance(message, str):\n",
     "    if False:\n",
     _C + "test_a_row_with_no_message_is_could_not_check"),
    ("an unreadable .py is reported as nothing", CHECKS,
     '                          "--extend-select", "E902"]\n',
     "                          ]\n",
     _C + "test_real_ruff_unreadable_file_is_could_not_check"),
    ("a [bracketed] PowerShell name matches nothing", CHECKS,
     "        $params = @{ Path = [System.Management.Automation.WildcardPattern]::Escape($path) }\n",
     "        $params = @{ Path = $path }\n",
     _C + "test_real_pssa_reads_awkward_names_and_utf16"),
    ("--allow-unverified overrides a new finding", RUN,
     "    if verdict == review_checks.COULD_NOT and args.allow_unverified:\n",
     "    if args.allow_unverified:\n",
     _R + "test_new_finding_is_not_overridable"),
    ("the pre-review refusal is dropped and a round is reserved", RUN,
     "        refused = prereview_gate(args)\n",
     "        prereview_gate(args)\n        refused = None\n",
     _R + "test_new_finding_refuses_before_reserve"),
    ("an expired or stood-down incident stands the checks down", RUN,
     '    if incident["active"]:\n        crew_incident.log_skip(args.root, "prereview-checks"',
     '    if incident["present"]:\n        crew_incident.log_skip(args.root, "prereview-checks"',
     _R + "test_only_an_active_incident_stands_down"),
    ("a config renamed away is reloaded from the base", CHECKS,
     "        if rel in at_base and rel not in renamed_away:\n",
     "        if rel in at_base:\n",
     _C + "test_a_config_renamed_away_is_gone_from_the_bundle"),
    ("a _note under preReview is accepted", CHECKS,
     'BLOCK_KEYS = {"linters"}',
     'BLOCK_KEYS = {"linters", "_note"}',
     _C + "test_a_note_in_the_block_is_an_unknown_key"),
    ("a record whose result contradicts its checks is accepted", CHECKS,
     '            payload["result"] != overall(payload["checks"], configured) or \\\n',
     '            False or \\\n',
     _C + "test_a_record_that_contradicts_itself_is_not_recorded"),
    ("a check row of the wrong shape is accepted", CHECKS,
     "            and all(_is_check_row(c) for c in payload[\"checks\"])\n",
     "            and all(isinstance(c, dict) for c in payload[\"checks\"])\n",
     _C + "test_a_record_that_contradicts_itself_is_not_recorded"),
    # review round 4 (owner grant 2026-10-02), each fix and the neighbour it was checked against
    ("a verify map that is not an object reads as unconfigured", CHECKS,
     "    if not isinstance(data, dict):\n        # Valid JSON",
     "    if False:\n        # Valid JSON",
     _C + "test_a_verify_map_that_is_not_an_object_is_could_not_check"),
    ("a bad row throws away the rows already read", CHECKS,
     '            yield _BadRow(where, f"{tool} reported a row it could not read "\n',
     '            raise CouldNotCheck(f"{tool} reported a row it could not read "\n',
     _C + "test_a_bad_row_does_not_discard_a_known_new_finding"),
    ("a bad base row leaves its file checked against a short base", CHECKS,
     '                    if row.where is not None and row.where[0] == "base":\n',
     "                    if False:\n",
     _C + "test_a_bad_base_row_leaves_that_file_unchecked"),
    ("a status that disagrees with its rows throws the rows away", CHECKS,
     '        yield _BadRow(None, f"{tool} exited {proc.returncode} but reported {len(rows)} "\n',
     '        raise CouldNotCheck(f"{tool} exited {proc.returncode} but reported {len(rows)} "\n',
     _C + "test_a_status_that_disagrees_with_its_rows_keeps_the_rows"),
    ("the bundle hash is read again after the linters ran", RUN,
     "        results, configured, bundle = review_checks.run_checks_bound(args.root, args.manifest)\n",
     "        results, configured, _ = review_checks.run_checks_bound(args.root, args.manifest)\n"
     "        with open(args.manifest, encoding=\"utf-8\") as fh:\n"
     "            bundle = json.load(fh).get(\"bundle_sha256\")\n",
     _R + "test_the_record_is_bound_to_the_manifest_the_checks_read"),
    ("a timeout kills only the direct child", CHECKS,
     "        else:\n            os.killpg(proc.pid, signal.SIGKILL)\n    except (OSError, subprocess.SubprocessError):\n",
     "        else:\n            pass\n    except (OSError, subprocess.SubprocessError):\n",
     _C + "test_the_timeout_holds_when_a_child_keeps_the_output_open"),
    ("a record with a flag its result cannot carry is accepted", CHECKS,
     "            not _flags_fit(payload):\n",
     "            False:\n",
     _C + "test_a_record_that_contradicts_itself_is_not_recorded"),
    ("a check row whose status disagrees with its findings is accepted", CHECKS,
     '    if (row.get("status") == FAIL) != bool(row["new"]) or (\n',
     '    if False and (\n',
     _C + "test_a_record_that_contradicts_itself_is_not_recorded"),
)
