"""The T-0008 mutations: `crew_refresh_check.py`, the read-only check that
the code maps, diagrams and code graph a ticket's changes reach are current,
and the refresh-artifact allowance it defines for `scope_guard.py` and
`completion_audit.py`. Same tuple shape as `sabotage.py`'s MUTATIONS --
(label, target, find, replace, test) -- and appended to it there; `sabotage.py`
sits near `.pylintrc`'s max-module-lines, so this list lives apart. Run
`sabotage.py`, not this file.

Each one is a way the check could collapse an unknown or a stale artifact
into the pass the owner asked it never to give, or a way the allowance could
open a blocking hook wider than an approved ticket's refresh. Review round 1
(T-0008-tG6OPn) named five of them as surviving; each now has a test the
same mutation turns red. Review round 2 (T-0008-TPCCYg) added the ones
after the ROUND 2 marker: a fallback base trusted after the ticket's commits
reached the default branch, a measured-looking line printed over nothing
measured, and three "could not tell" cases read as fresh. A mutation listed twice with different tests is on
purpose: dropping the approval condition must fail the unapproved, the `cli`
and the stale case each, not just whichever runs first.
"""
import os

CREW = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_S = os.path.join(CREW, "hooks", "scripts")
CHECK = os.path.join(_S, "crew_refresh_check.py")
GUARD = os.path.join(_S, "scope_guard.py")
AUDIT = os.path.join(_S, "completion_audit.py")
_T = "tests/test_refresh_check.py::"
_SG = "tests/test_scope_guard_refresh_artifacts.py::"
_CA = "tests/test_completion_audit_refresh_artifacts.py::"
_CAI = "tests/test_completion_audit.py::"

_WORKTREE_DIFF = ("        return sorted(completion_audit.worktree_changes(root, sha, list(paths), "
                  "literal=True))\n")
_GUARD_GATE = '    if approval["status"] != "approved":\n        return False\n    if real_rel'
_AUDIT_GATE = '    if approval["status"] != "approved":\n        return paths\n'

REFRESH_MUTATIONS = (
    ("the refresh check reports fresh whatever the artifacts say", CHECK,
     '    result = {"status": overall, "reason": f"scope base {base[:12]} ({why})", "stop": None,\n',
     '    result = {"status": FRESH, "reason": f"scope base {base[:12]} ({why})", "stop": None,\n',
     _T + "test_codemap_citing_changed_path_behind_is_stale"),
    ("an unknown artifact reads as fresh", CHECK,
     'UNKNOWN = "unknown"\n',
     'UNKNOWN = "fresh"\n',
     _T + "test_graphify_missing_is_unknown"),
    ("the freshness diff is <anchor>..HEAD, blind to an uncommitted edit", CHECK,
     _WORKTREE_DIFF,
     '        return _git_lines(root, "diff", "--name-only", f"{sha}..HEAD", "--", *paths)\n',
     _T + "test_uncommitted_edit_in_cited_path_is_stale"),
    ("the freshness diff is `git diff`, which rewrites the index", CHECK,
     _WORKTREE_DIFF,
     '        return _git_lines(root, "diff", "--name-only", sha, "--", *paths)\n',
     _T + "test_a_library_call_never_rewrites_the_index"),
    ("an untracked cited file is not a change", CHECK,
     "    new = [p for p in reached if p in untracked]\n",
     "    new = []\n",
     _T + "test_untracked_cited_file_is_stale"),
    ("every diagram reads as unanchored", CHECK,
     "        anchor = _DIAGRAM_ANCHOR_RE.search(body)\n",
     "        anchor = None\n",
     _T + "test_diagram_refreshed_is_fresh"),
    ("a fallback base equal to HEAD is trusted", CHECK,
     "    if hides:\n",
     "    if False:\n",
     _T + "test_fallback_equal_to_head_on_a_fresh_branch_is_unknown"),
    ("every fallback base reads unknown", CHECK,
     "    hides = head is None or base == head\n",
     "    hides = True\n",
     _T + "test_fallback_base_on_a_branch_ahead_of_main_is_judged_and_marked"),
    ("a line judged against a fallback base is not marked", CHECK,
     '        item["reason"] += " [fallback base]"\n',
     "        pass\n",
     _T + "test_fallback_base_on_a_branch_ahead_of_main_is_judged_and_marked"),
    ("a dot-directory citation is not parsed", CHECK,
     '    r"`(\\.?[A-Za-z0-9_]',
     '    r"`([A-Za-z0-9_]',
     _T + "test_codemap_dot_directory_citation_is_in_scope"),
    ("a line-range citation is not parsed", CHECK,
     '(?::\\d+(?:-\\d+)?)?`"\n',
     '(?::\\d+)?`"\n',
     _T + "test_codemap_line_range_citation_is_in_scope"),
    ("a trailing-slash prose mention reads as a directory citation", CHECK,
     '(?:/[A-Za-z0-9_.@+-]+)*)(?::\\d+',
     '(?:/[A-Za-z0-9_.@+-]+)*/?)(?::\\d+',
     _T + "test_a_trailing_slash_prose_mention_is_not_a_citation"),
    ("a code map citing no path is out of scope", CHECK,
     "        if not cited:\n            if changed:\n",
     "        if not cited:\n            if False:\n",
     _T + "test_codemap_with_no_parseable_citation_is_unknown"),
    ("release bookkeeping stales artifacts", CHECK,
     "    return any(crew_ticket.glob_match(path, glob) for glob in RELEASE_BOOKKEEPING)\n",
     "    return False\n",
     _T + "test_release_bookkeeping_alone_stales_nothing"),
    ("a cited directory reaches nothing under it", CHECK,
     '    return bool(entry) and (path == entry or path.startswith(entry + "/"))\n',
     "    return bool(entry) and path == entry\n",
     _T + "test_diagram_anchors_naming_a_directory_reach_files_under_it"),
    ("an anchor naming no commit is a stop, not a refresh", CHECK,
     '"squash-merged or rebased branch?); a refresh re-anchors it"), True\n',
     '"squash-merged or rebased branch?); a refresh re-anchors it"), False\n',
     _T + "test_an_anchor_naming_no_commit_is_refreshable"),
    ("every unknown line says refresh", CHECK,
     '        if item["refreshable"]:\n',
     '        if item["status"] in (STALE, UNKNOWN):\n',
     _T + "test_graphify_missing_is_a_stop_not_a_refresh"),
    ("the graph always names graphify update", CHECK,
     '    command = ("graphify update ." if info["reportTracked"]\n',
     '    command = ("graphify update ." if True\n',
     _T + "test_graph_without_a_tracked_report_names_the_code_only_build"),
    ("an artifact dir matches by string prefix", CHECK,
     "        if len(folded) > len(stem) and folded[:len(stem)] == stem:\n",
     '        if "/".join(folded).startswith("/".join(stem)):\n',
     _T + "test_is_refresh_artifact_matches_whole_segments_only[.crew/codemapX/crew.md-False]"),
    ("an artifact path keeps its '..' segments", CHECK,
     '    if any(p in ("", ".", "..") for p in parts):\n',
     "    if False:\n",
     _T + "test_is_refresh_artifact_matches_whole_segments_only[.crew/codemap/../config.json-False]"),
    ("a configured dir naming the repo root is an artifact dir", CHECK,
     '        if rel in ("", ".") or first in ("..", os.path.normcase(".git")):\n',
     "        if False:\n",
     _T + "test_a_configured_dir_naming_the_repo_root_is_never_an_artifact_dir"),
    ("an artifact dir reached through a link is kept", CHECK,
     "        if os.path.normcase(real) not in named:\n            continue\n",
     "        if False:\n            continue\n",
     _T + "test_an_artifact_dir_reached_through_a_link_is_dropped"),
    ("a linked artifact dir opens its target to the guard", CHECK,
     "        if os.path.normcase(real) not in named:\n            continue\n",
     "        if False:\n            continue\n",
     _SG + "test_an_artifact_dir_that_is_itself_a_link_opens_nothing[other/keep.py-module]"),
    ("the guard's artifact allowance ignores approval (unapproved)", GUARD,
     _GUARD_GATE, _GUARD_GATE.replace('approval["status"] != "approved"', "False"),
     _SG + "test_an_unapproved_ticket_cannot_write_a_refresh_artifact[module]"),
    ("the guard's artifact allowance ignores approval (cli receipt)", GUARD,
     _GUARD_GATE, _GUARD_GATE.replace('approval["status"] != "approved"', "False"),
     _SG + "test_a_cli_approval_cannot_write_a_refresh_artifact[module]"),
    ("the guard's artifact allowance ignores approval (stale)", GUARD,
     _GUARD_GATE, _GUARD_GATE.replace('approval["status"] != "approved"', "False"),
     _SG + "test_a_stale_approval_cannot_write_a_refresh_artifact[module]"),
    ("the guard's artifact allowance follows a link out of the worktree", GUARD,
     "    if real_rel is None:\n        return False\n",
     "    if False:\n        return False\n",
     _SG + "test_a_link_in_an_artifact_dir_pointing_out_of_the_worktree_is_blocked[module]"),
    ("the audit's artifact allowance ignores approval (unapproved)", AUDIT,
     _AUDIT_GATE, _AUDIT_GATE.replace('approval["status"] != "approved"', "False"),
     _CA + "test_an_unapproved_ticket_cannot_leave_a_refresh_artifact_changed"),
    ("the audit's artifact allowance ignores approval (cli receipt)", AUDIT,
     _AUDIT_GATE, _AUDIT_GATE.replace('approval["status"] != "approved"', "False"),
     _CA + "test_a_cli_approval_cannot_leave_a_refresh_artifact_changed"),
    ("the audit lists paths with `git diff`, which rewrites the index", AUDIT,
     '    fields = _git_fields(top, ["diff-index", "--raw", "-z", "-M", sha, "--"] + pathspec,\n',
     '    fields = _git_fields(top, ["diff", "--raw", "-z", "-M", sha, "--"] + pathspec,\n',
     _CAI + "test_the_audit_never_rewrites_the_index"),
    ("the audit counts a stat-dirty unchanged file as changed", AUDIT,
     "    return paths | (set(suspects) - _unchanged(top, suspects))\n",
     "    return paths | set(suspects)\n",
     _CAI + "test_a_stat_dirty_unchanged_file_is_not_a_change"),
    ("the audit misses a mode change with the same content", AUDIT,
     '        if (status == "M" and src_mode == dst_mode and src_mode in _FILE_MODES\n',
     '        if (status == "M" and src_mode in _FILE_MODES\n',
     _CAI + "test_a_mode_change_with_the_same_content_is_a_change"),
    # ROUND 2 (T-0008-TPCCYg)
    ("a fallback base is trusted on the default branch", CHECK,
     "    if branch[0] in (name, default):\n",
     "    if False:\n",
     _T + "test_fallback_on_main_with_pushed_commits_is_unknown"),
    ("a fallback base is trusted with the ticket's commits behind it", CHECK,
     "    if named:\n",
     "    if False:\n",
     _T + "test_fallback_after_a_fast_forward_into_main_is_unknown"),
    ("a detached HEAD reads as a branch that is not the default", CHECK,
     '    branch = _git_lines(top, "symbolic-ref", "--quiet", "--short", "HEAD")\n',
     '    branch = _git_lines(top, "symbolic-ref", "--quiet", "--short", "HEAD") or ["x"]\n',
     _T + "test_fallback_with_a_detached_head_is_unknown"),
    ("an unknown scope base prints no stop on the top line", CHECK,
     '    if result.get("stop"):\n',
     "    if False:\n",
     _T + "test_hides_case_renders_a_stop_on_the_top_line"),
    ("the no-codemap-cites line prints under unknown", CHECK,
     "        if result[\"status\"] in (FRESH, STALE):\n",
     "        if True:\n",
     _T + "test_no_codemap_cites_line_only_when_fresh_or_stale[unknown-False]"),
    ("the untracked list is newline-split, so a quoted name never matches", CHECK,
     '["ls-files", "-z", "--others", "--exclude-standard"]',
     '["ls-files", "--others", "--exclude-standard"]',
     _T + "test_an_untracked_file_git_would_quote_stales_the_graph"),
    ("a corrupt config reads as the defaults", CHECK,
     '            return None, f".crew/{name} is not valid JSON"\n',
     "            return {}, None\n",
     _T + "test_a_corrupt_config_is_unknown_not_the_defaults[crew-json-truncated]"),
    ("an unreadable config falls through to the next file", CHECK,
     '            return None, f".crew/{name} could not be read"\n',
     "            continue\n",
     _T + "test_an_unreadable_config_is_not_skipped_for_the_next_one"),
    ("an unlistable artifact dir holds no artifacts", CHECK,
     "        return None, exc.strerror or type(exc).__name__\n",
     "        return [], None\n",
     _T + "test_an_unlistable_artifact_dir_is_unknown[codemap-.crew/codemap]"),
    ("an unreadable code map reads as citing no path", CHECK,
     "        body = read_text(os.path.join(mapdir, name))\n",
     '        body = read_text(os.path.join(mapdir, name)) or ""\n',
     _T + "test_an_unreadable_codemap_is_unknown"),
    ("filing a TODO item stales every map citing TODO.md", CHECK,
     '    "TODO.md",\n',
     "",
     _T + "test_filing_a_todo_item_alone_stales_nothing"),
)
