"""The T-0004 mutations: `crew_autopilot.py`, `crew_ticket.parse_risk` and
`commands/autopilot.md`. Same tuple shape as `sabotage.py`'s MUTATIONS --
(label, target, find, replace, test) -- and appended to it there;
`sabotage.py` sits near `.pylintrc`'s max-module-lines, so this list lives
apart. Run `sabotage.py`, not this file.

Each one is a way autopilot could drive past a person, guess a ticket, or
write where it must not.

STATUS_MUTATIONS are T-0018's (`route` and `status`). They are appended to
AUTOPILOT_MUTATIONS, which sabotage.py already registers, so they run with
the rest; test_crew_autopilot.py holds every anchor to exactly one match and
asserts each one reaches sabotage.MUTATIONS.
"""
import os

CREW = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPTS = os.path.join(CREW, "hooks", "scripts")
AUTOPILOT = os.path.join(SCRIPTS, "crew_autopilot.py")
TICKET = os.path.join(SCRIPTS, "crew_ticket.py")
COMMAND = os.path.join(CREW, "commands", "autopilot.md")
_T = "tests/test_crew_autopilot.py::"
_S = "tests/test_crew_autopilot_status.py::"

AUTOPILOT_MUTATIONS = (
    ("an unknown spec risk reads as low", TICKET,
     '    return {"risk": "high", "known": False}\n',
     '    return {"risk": "low", "known": False}\n',
     _T + "test_risk_absent_reads_high"),
    ("plan approval stops nothing", AUTOPILOT,
     '        return answer("approve", True, ',
     '        return answer("approve", False, ',
     _T + "test_next_never_returns_approve_without_stop"),
    ("T-0008 missing reads as fresh artifacts", AUTOPILOT,
     '        return {"state": UNAVAILABLE, "command": "", "reason": REFRESH_UNAVAILABLE}\n',
     '        return {"state": FRESH, "command": "", "reason": REFRESH_UNAVAILABLE}\n',
     _T + "test_refresh_unavailable_stops"),
    ("the INDEX fallback takes the first of several open tickets", AUTOPILOT,
     "            if len(candidates) > 1:\n",
     "            if False:\n",
     _T + "test_resume_several_open_tickets_stops"),
    ("the command drops an AUTONOMOUS_STOPS id", COMMAND,
     "- `git-destruction` - ",
     "- ",
     _T + "test_command_names_every_autonomous_stop"),
    ("a mode typo arms autopilot", AUTOPILOT,
     '    armed = mode == "plan"\n',
     '    armed = str(mode).strip().lower() == "plan"\n',
     _T + "test_mode_typo_is_off"),
    # ---- round 1 (T-0004-02ixAb), one per new stop
    ("BLOCK: a spent budget with no receipt still reviews (writes NEEDS_REPLAN)", AUTOPILOT,
     "    if not ok and (not isinstance(left, int) or left < 1):\n",
     "    if False:\n",
     _T + "test_next_budget_spent_without_a_receipt_stops"),
    ("an INCOMPLETE round is rerun unattended", AUTOPILOT,
     '    if latest.get("verdict") != "CLEAN" and not ok:\n',
     "    if False:\n",
     _T + "test_next_incomplete_round_stops"),
    ("BLOCK: the command lets a review phase fix and rerun", COMMAND,
     "never fix and rerun inside the phase",
     "fix and rerun inside the phase",
     _T + "test_command_ends_the_review_phase_at_the_verdict"),
    ("a pre-T-0026 approval stop loses its header-only reason", AUTOPILOT,
     "                return was\n",
     "                return None\n",
     _T + "test_next_legacy_receipt_header_edit_names_the_header_edit"),
    ("no INDEX row reads as an approved direction", AUTOPILOT,
     "    if status is None:\n",
     "    if False:\n",
     _T + "test_next_direction_approval_unknown_stops"),
    ("open questions do not stop", AUTOPILOT,
     "    if questions:\n",
     "    if False:\n",
     _T + "test_next_open_questions_stop"),
    ("any unknown artifact is refreshed", AUTOPILOT,
     '    return (artifact.get("status") == UNKNOWN and artifact.get("refreshable") is True\n'
     "            and ORPHANED_ANCHOR in reason)\n",
     '    return artifact.get("status") == UNKNOWN\n',
     _T + "test_refresh_unknown_other_cause_stops"),
    ("one settled artifact carries an unsettled one", AUTOPILOT,
     "            or not all(_settles(a) for a in pending):\n",
     "            or not any(_settles(a) for a in pending):\n",
     _T + "test_refresh_one_unsettled_artifact_stops_the_rest"),
    ("an answer-level unknown is refreshed through a stale artifact", AUTOPILOT,
     '    overall_unknown = status == UNKNOWN and not any(a.get("status") == UNKNOWN '
     "for a in pending)\n",
     "    overall_unknown = False\n",
     _T + "test_refresh_overall_unknown_over_stale_artifacts_stops"),
    ("a refresh check that raised reads as fresh", AUTOPILOT,
     '        return {"state": UNSETTLED, "command": "",\n'
     '                "reason": f"the refresh check could not run',
     '        return {"state": FRESH, "command": "",\n'
     '                "reason": f"the refresh check could not run',
     _T + "test_refresh_check_that_raises_stops"),
    ("the handoff's ticket folder is not checked", AUTOPILOT,
     "    if not os.path.isdir(crew_ticket.ticket_dir(top, arg)):\n",
     "    if False:\n",
     _T + "test_resume_handoff_ticket_without_a_folder_falls_through"),
    ("a ticket other than the active one is driven", AUTOPILOT,
     '    if where == "active-ticket" and active != ticket:\n',
     "    if False:\n",
     _T + "test_resume_handoff_disagreeing_with_the_active_pointer_stops"),
    ("the driven ticket is never activated", AUTOPILOT,
     '"activate": where != "active-ticket"}',
     '"activate": False}',
     _T + "test_resume_from_handoff_line"),
    ("the command never activates the ticket", COMMAND,
     "`activate=1` (no pointer is set)",
     "(no pointer is set)",
     _T + "test_command_activates_the_ticket_only_without_a_pointer"),
    ("stale-after-review writes crew state", AUTOPILOT,
     "        return answer(\"stale-after-review\", True, ",
     "        os.close(os.open(os.path.join(crew_ticket.state_dir(top), \"x\"), "
     "os.O_CREAT | os.O_WRONLY))\n"
     "        return answer(\"stale-after-review\", True, ",
     _T + "test_next_stale_after_review_stops_without_writing"),
    # ---- round-2 fixes: human-stop bypasses found after round 1
    ("a blank or unknown INDEX status reads as an approved direction", AUTOPILOT,
     "    if status not in DIRECTION_APPROVED:\n",
     "    if False:\n",
     _T + "test_next_index_status_that_does_not_say_approved_stops"),
    ("an INDEX done row is re-driven", AUTOPILOT,
     "    if status in INDEX_DONE:\n",
     "    if False:\n",
     _T + "test_next_index_status_done_stops_as_closed"),
    ("an open question starting with `none` reads as answered", AUTOPILOT,
     '_ANSWERED = re.compile(r"^(?:(?:none|n/a)(?:$|\\s*[-:,(\\u2013\\u2014])|\\[x\\]|~~|-$)")\n',
     '_ANSWERED = re.compile(r"^(?:none|n/a|\\[x\\]|~~|-$)")\n',
     _T + "test_next_open_question_that_only_looks_answered_stops"),
    ("a sub-heading ends the open questions section", AUTOPILOT,
     "            if depth and level > depth:\n                continue\n",
     "            if False:\n                continue\n",
     _T + "test_next_open_question_that_only_looks_answered_stops"),
    ("next drives a ticket the scope guard does not judge by", AUTOPILOT,
     "    if broken or active != ticket:\n",
     "    if broken:\n",
     _T + "test_next_stops_when_another_ticket_is_active"),
    ("next drives when no pointer and INDEX names another ticket", AUTOPILOT,
     "    if broken or active != ticket:\n",
     "    if broken or (where == \"active-ticket\" and active != ticket):\n",
     _T + "test_next_stops_when_the_scope_guard_would_judge_another_ticket"),
    ("a crash in next prints no stop", AUTOPILOT,
     "        except Exception as exc:  # pylint: disable=broad-except\n"
     "            # A crash cannot tell the phase",
     "        except crew_ticket.TicketError as exc:  # pylint: disable=broad-except\n"
     "            # A crash cannot tell the phase",
     _T + "test_cli_that_raises_prints_a_stop"),
    ("a crash in resume prints no stop", AUTOPILOT,
     "        except Exception as exc:  # pylint: disable=broad-except\n"
     "            # A crash cannot tell which ticket",
     "        except crew_ticket.TicketError as exc:  # pylint: disable=broad-except\n"
     "            # A crash cannot tell which ticket",
     _T + "test_cli_that_raises_prints_a_stop"),
    ("the command lets autopilot accept or post a review", COMMAND,
     "are the human's. Go back",
     "are autopilot's. Go back",
     _T + "test_command_leaves_accept_and_pr_review_to_the_human"),
    ("the command reads a crash or no output as permission", COMMAND,
     "No output, a traceback or a non-zero exit is a stop.",
     "",
     _T + "test_command_reads_no_answer_as_a_stop"),
)

STATUS_MUTATIONS = (
    ("route reads an unknown word as a ticket to run", AUTOPILOT,
     '        return {"sub": "", "stop": True, "reason": UNKNOWN_SUB}\n',
     '        sub = "run"\n',
     _S + "test_route_unknown_word_refuses"),
    ("route runs a subcommand whose ticket has not landed", AUTOPILOT,
     "    if sub not in AVAILABLE:\n",
     "    if False:\n",
     _S + "test_route_unavailable_names_its_ticket"),
    # Retargeted in round 3: `_review`'s UNKNOWN-state branch now answers a
    # corrupt ledger before `rounds_left` is read, so this default is reached
    # only by a readable state with no count (sabotage.py found it green).
    ("status reads a ledger's missing rounds_left as the budget", AUTOPILOT,
     '    left = ledger.get("rounds_left")\n',
     '    left = ledger.get("rounds_left", review_ledger.BUDGET)\n',
     _S + "test_status_ledger_without_a_rounds_count_is_unknown"),
    # T-0077: a ledger on another Windows drive than the repo.
    ("status crashes on an evidence path with no relative form", AUTOPILOT,
     "    except ValueError:\n        return path.replace(\"\\\\\", \"/\")\n",
     "    except KeyError:\n        return path.replace(\"\\\\\", \"/\")\n",
     _S + "test_status_ledger_on_another_drive_is_still_reported"),
    ("status reads an unmapped phase as waiting on autopilot", AUTOPILOT,
     "    who = WAITING.get(phase, UNKNOWN)\n",
     '    who = WAITING.get(phase, "autopilot")\n',
     _S + "test_status_unmapped_phase_is_unknown"),
    ("status calls a writer", AUTOPILOT,
     "    conf = settings(top)\n    if ticket:\n",
     "    conf = settings(top)\n    if ticket:\n        crew_ticket.activate(top, ticket)\n",
     _S + "test_status_writes_nothing"),
    ("status prints past its 12-line cap", AUTOPILOT,
     "    if len(lines) > STATUS_MAX_LINES:\n",
     "    if False:\n",
     _S + "test_status_text_caps_at_12_lines"),
    ("route takes any word after a subcommand as the ticket", AUTOPILOT,
     "    if len(rest) > 1 or (rest and not (_INDEX_ID.fullmatch(rest[0])\n",
     "    if len(rest) > 1 and (rest and not (_INDEX_ID.fullmatch(rest[0])\n",
     _S + "test_route_args_refuses_what_is_not_a_ticket"),
    ("the command hands route a positional argument", COMMAND,
     "route --root . --args '$ARGUMENTS'\n",
     'route --root . --first "$1"\n',
     _S + "test_command_passes_its_arguments_whole"),
    # Round 1's FIX and NIT lines, one per new guard branch.
    ("status calls a handoff usable that names no ticket", AUTOPILOT,
     '    if parsed.get("kind") != "ticket" or not parsed.get("arg"):\n',
     "    if False:\n",
     _S + "test_status_resume_line_not_usable_where_resume_falls_through"),
    ("status calls a handoff usable whose ticket has no folder", AUTOPILOT,
     '    if not _existing_ticket(top, parsed["arg"]):\n',
     "    if False:\n",
     _S + "test_status_resume_line_not_usable_where_resume_falls_through"),
    ("a pointer stop tells the owner to type the phase command", AUTOPILOT,
     "    if guard:\n        return _repoint(",
     "    if False:\n        return _repoint(",
     _S + "test_status_ticket_mismatch_waits_on_repointing"),
    ("a broken pointer reads as autopilot activating", AUTOPILOT,
     "    if broken:\n        return (\"owner - fixes the broken",
     "    if False:\n        return (\"owner - fixes the broken",
     _S + "test_status_broken_pointer_waits_on_the_owner_fixing_it"),
    ("an unset pointer tells the owner to re-point", AUTOPILOT,
     '    if where != "active-ticket":\n        return f"autopilot - run',
     '    if False:\n        return f"autopilot - run',
     _S + "test_status_unset_pointer_waits_on_autopilot_activating"),
    ("a phase check that raised reads as the owner typing a command", AUTOPILOT,
     '        return "unknown (could not tell which check stopped the phase)"\n',
     "        guard = False\n",
     _S + "test_status_waiting_is_unknown_when_the_phase_check_raises"),
    ("route reads run --goal as a ticket", AUTOPILOT,
     '    if words[:1] == ["run"] and rest[:1] == [GOAL_FLAG]:\n',
     "    if False:\n",
     _S + "test_route_args_run_goal_arrives_with_its_ticket"),
    ("the route CLI reads a dash-led value as an option", AUTOPILOT,
     "            if 0 <= at < len(argv) - 1:\n",
     "            if False:\n",
     _S + "test_route_cli_takes_a_token_that_starts_with_a_dash"),
    ("route --first is not the one-token interface", AUTOPILOT,
     '    elif args.action == "route" and args.first is not None:\n',
     "    elif False:\n",
     _S + "test_route_cli_takes_a_token_that_starts_with_a_dash"),
    ("status's own output is never capped", AUTOPILOT,
     "    if len(lines) > STATUS_MAX_LINES:\n",
     "    if False:\n",
     _S + "test_status_at_most_12_lines"),
    ("the command lets a crashed router fall into run", COMMAND,
     "Anything but a `sub=` line - no output,\n",
     "No output,\n",
     _S + "test_command_stops_when_route_prints_no_answer"),
    ("the command drives route's empty ticket after resume picked one", COMMAND,
     "arguments; from `resume` on, `<ticket>` is the `ticket=` resume printed.\n",
     "arguments.\n",
     _S + "test_command_takes_the_ticket_resume_printed"),
    ("the command hands the shell expandable arguments", COMMAND,
     "If the arguments hold a quote, `$`, a backtick or a backslash, stop without\n",
     "Consider this without\n",
     _S + "test_command_never_hands_the_shell_an_expandable_argument"),
    ("the command double-quotes the arguments", COMMAND,
     "route --root . --args '$ARGUMENTS'\n",
     'route --root . --args "$ARGUMENTS"\n',
     _S + "test_command_never_hands_the_shell_an_expandable_argument"),
    # Round 2's FIX and NIT lines (successor Step 5), one per new guard branch.
    ("status's resume line ignores the active pointer", AUTOPILOT,
     '    if _takes(bare, parsed.get("arg"), "handoff"):\n',
     "    if bool(_handoff_ticket(top)[0]):\n",
     _S + "test_status_resume_line_not_usable_on_a_pointer_mismatch"),
    ("status's resume line counts a fall-through to the same ticket as taking it", AUTOPILOT,
     '            and source in (None, bare.get("source")))\n',
     "            and True)\n",
     _S + "test_status_resume_line_not_usable_when_resume_took_the_ticket_from_elsewhere"),
    ("a resume_target that raised reads as a verdict on the resume line", AUTOPILOT,
     "    if bare is None:\n",
     "    if False:\n",
     _S + "test_status_resume_line_unknown_when_resume_target_raises"),
    ("stop=0 always tells the owner to type the bare command", AUTOPILOT,
     '        if _takes(bare, result["ticket"]):\n',
     "        if True:\n",
     _S + "test_status_continue_names_this_ticket_when_bare_autopilot_would_not"),
    ("a pointer stop offers to drive a closed active ticket", AUTOPILOT,
     "    if closed:\n",
     "    if False:\n",
     _S + "test_status_repoint_never_offers_a_closed_ticket"),
    ("an active ticket whose phase could not be read is offered as open", AUTOPILOT,
     "    if closed is None:\n",
     "    if False:\n",
     _S + "test_status_repoint_says_unknown_when_the_active_phase_raises"),
    # Round 3's FIX and NIT lines (T-0018-router--3YKWjw), one per new guard branch.
    ("status prints a rounds count for a ledger whose state is UNKNOWN", AUTOPILOT,
     "    if state == review_ledger.UNKNOWN:\n",
     "    if False:\n",
     _S + "test_status_ledger_that_says_unknown_prints_no_rounds_count"),
    ("status prints a rounds count for a ledger state review_ledger never writes", AUTOPILOT,
     "    if state not in LEDGER_STATES:\n",
     "    if False:\n",
     _S + "test_status_ledger_state_review_ledger_never_writes_is_unknown"),
    ("status reads a handoff it could not read as absent", AUTOPILOT,
     "    except (OSError, ValueError):\n        return None, HANDOFF_UNREADABLE\n",
     "    except (OSError, ValueError):\n        return None, HANDOFF_ABSENT\n",
     _S + "test_status_resume_line_unknown_when_the_handoff_cannot_be_read"),
    ("resume falls through past an unreadable handoff calling it absent", AUTOPILOT,
     '        return None, "", None, why\n',
     '        return None, "", None, HANDOFF_ABSENT\n',
     _S + "test_resume_falls_through_saying_the_handoff_could_not_be_read"),
    ("a closed active ticket without direction.md is offered (INDEX)", AUTOPILOT,
     "    if _index_status(top, ticket) in INDEX_DONE:\n        return True\n",
     "    if False:\n        return True\n",
     _S + "test_status_repoint_never_offers_a_closed_ticket_without_a_direction"),
    ("a closed active ticket without direction.md is offered (spec header)", AUTOPILOT,
     "    return spec is not None and _header_status(\n",
     "    return False and _header_status(\n",
     _S + "test_status_repoint_never_offers_a_closed_ticket_without_a_direction"),
    # The route and status mutations below name the textual -B check, not
    # test_status_as_the_command_runs_it_writes_no_bytecode: since round 4 the
    # script sets sys.dont_write_bytecode under __main__, so dropping -B from one
    # command line writes no bytecode and that behavioural test stays green (it
    # read STILL GREEN on 60f4593e). The in-script guard has its own mutation,
    # "the direct CLI writes bytecode", below.
    ("the command's route invocation writes bytecode", COMMAND,
     "python3 -B ${CLAUDE_PLUGIN_ROOT}/hooks/scripts/crew_autopilot.py route ",
     "python3 ${CLAUDE_PLUGIN_ROOT}/hooks/scripts/crew_autopilot.py route ",
     _S + "test_every_autopilot_invocation_in_command_skips_bytecode"),
    ("the command's status invocation writes bytecode", COMMAND,
     "python3 -B ${CLAUDE_PLUGIN_ROOT}/hooks/scripts/crew_autopilot.py status ",
     "python3 ${CLAUDE_PLUGIN_ROOT}/hooks/scripts/crew_autopilot.py status ",
     _S + "test_every_autopilot_invocation_in_command_skips_bytecode"),
    ("the command's next invocation writes bytecode", COMMAND,
     "python3 -B ${CLAUDE_PLUGIN_ROOT}/hooks/scripts/crew_autopilot.py next ",
     "python3 ${CLAUDE_PLUGIN_ROOT}/hooks/scripts/crew_autopilot.py next ",
     _S + "test_every_autopilot_invocation_in_command_skips_bytecode"),
    # Round 4's FIX lines (T-0018-router--TR98fj, successor Step 6), one per new branch.
    ("an unreadable active spec reads as an open ticket to offer", AUTOPILOT,
     "    if spec is None and os.path.lexists(",
     "    if spec is None and False and os.path.lexists(",
     _S + "test_status_repoint_unreadable_active_spec_is_could_not_tell"),
    ("a ticket named like a subcommand is suggested without `run`", AUTOPILOT,
     "    if ticket in SUBCOMMANDS:\n        return f\"{AUTOPILOT} run {ticket}\"\n",
     "    if False:\n        return f\"{AUTOPILOT} run {ticket}\"\n",
     _S + "test_status_suggests_run_for_a_ticket_named_like_a_subcommand"),
    ("the direct CLI writes bytecode", AUTOPILOT,
     "    sys.dont_write_bytecode = True\n",
     "    pass\n",
     _S + "test_status_direct_cli_writes_no_bytecode"),
    # Round 5's FIX lines (T-0018 review round 5, successor Step 7), one per new branch.
    ("a dangling HANDOFF.md symlink reads as absent", AUTOPILOT,
     "        if os.path.lexists(path) or (",
     "        if False or (",
     _S + "test_status_resume_line_unknown_when_the_handoff_cannot_be_read"),
    ("a dangling .work symlink reads the handoff as absent", AUTOPILOT,
     "(os.path.lexists(work) and not os.path.isdir(work))",
     "False",
     _S + "test_read_handoff_unknown_when_work_is_a_dangling_symlink"),
    ("status's resume line trusts resume_target's earlier read of the handoff", AUTOPILOT,
     "    # `_handoff_ticket`'s checks in its order, in fixed text, on THIS read's\n",
     ('    if _takes(bare, parsed.get("arg"), "handoff"):\n'
      '        return f"{rendered} (usable)"\n'),
     _S + "test_status_resume_line_checks_the_handoff_it_read_not_the_one_resume_read"),
    ("status --json prints past the line cap", AUTOPILOT,
     'indent=None if args.action == "status" else 2',
     "indent=2",
     _S + "test_status_json_at_most_12_lines"),
)

AUTOPILOT_MUTATIONS += STATUS_MUTATIONS

# ---- T-0010: the approval and questions policies. One per refusing branch;
# each names the test that must go red. Registered in sabotage.py beside
# AUTOPILOT_MUTATIONS; test_crew_autopilot_policy.py holds every anchor to
# exactly one match.
GUARD = os.path.join(SCRIPTS, "scope_guard.py")
_P = "tests/test_crew_autopilot_policy.py::"
_CT = "tests/test_crew_ticket.py::"
_SG = "tests/test_scope_guard.py::"
_R = "tests/test_crew_route.py::"
README = os.path.join(CREW, "README.md")

POLICY_MUTATIONS = (
    ("approval: risk approves a med spec", AUTOPILOT,
     '    elif risk["known"] and risk["risk"] == "low":\n',
     '    elif risk["risk"] in ("low", "med"):\n',
     _P + "test_approval_risk_allows_only_low[med-False]"),
    ("approval: an unknown risk is approved under risk", AUTOPILOT,
     '    elif risk["known"] and risk["risk"] == "low":\n',
     '    elif risk["risk"] == "low" or not risk["known"]:\n',
     _P + "test_approval_risk_unknown_denies[status: spec]"),
    ("a header naming risk twice is trusted", AUTOPILOT,
     '    if len(re.findall(r"\\brisk:", crew_ticket.header_line(text), re.IGNORECASE)) > 1:\n',
     "    if False:\n",
     _P + "test_approval_header_naming_risk_twice_is_unknown"
     "[cut risk: low paths   status: spec   risk: high]"),
    ("approval: the allowCliApproval check is skipped", AUTOPILOT,
     "    elif not allowed:\n",
     "    elif False:\n",
     _P + "test_approval_requires_allow_cli_approval[False-risk]"),
    ("approval: the human policy approves", AUTOPILOT,
     "    elif policy == HUMAN:\n",
     "    elif False:\n",
     _P + "test_approval_human_never_allows[low]"),
    ("approval: an unreadable review ledger still self-approves", AUTOPILOT,
     "    elif ledger == review_ledger.UNKNOWN:\n",
     "    elif False:\n",
     _P + "test_approval_refuses_when_the_review_ledger_is_unreadable"),
    # ---- T-0010 review round 1 (T-0010-solo--VfNkU3): each FIX and its neighbour
    ("FIX: a NEEDS_REPLAN ledger vetoes self-approving the successor plan", AUTOPILOT,
     "    elif ledger == review_ledger.UNKNOWN:\n",
     "    elif ledger in (review_ledger.NEEDS_REPLAN, review_ledger.UNKNOWN):\n",
     _P + "test_approval_self_allows_a_successor_plan_under_needs_replan[high]"),
    ("FIX: a taken: line must name the policy in force today", AUTOPILOT,
     "        if policy not in (SELF, RISK):\n",
     '        if policy != decision["policy"]:\n',
     _P + "test_questions_file_taken_under_an_earlier_policy_that_took_stays_valid"
     "[risk-self-high]"),
    ("questions-check: a taken: line may name a policy that never takes", AUTOPILOT,
     "        if policy not in (SELF, RISK):\n",
     "        if False:\n",
     _P + "test_questions_file_taken_naming_a_policy_that_never_takes_invalid[human]"),
    ("FIX: the guard reads a bash line continuation as a separator", GUARD,
     '    bash = _BASH_CONTINUATION_RE.sub("", command)\n',
     "    bash = command\n",
     _SG + "test_autopilot_approve_across_a_line_continuation_is_refused"
     "[before-approve-self-module]"),
    ("the guard reads a PowerShell line continuation as a separator", GUARD,
     '    return command, bash, _PS_CONTINUATION_RE.sub(" ", command)\n',
     "    return command, bash, command\n",
     _SG + "test_an_approval_split_across_a_line_continuation_is_refused[ps-crew-ticket-module]"),
    ("FIX: the command stops at approve before the policy runs", COMMAND,
     "- `stop=1` with `phase=approve` or `phase=open-questions` - not yet a stop",
     "- `stop=1` - a stop",
     _P + "test_command_sends_a_stop_at_approve_or_open_questions_to_the_policy_first"),
    ("a policy value that is not a policy reads as self", AUTOPILOT,
     '    return HUMAN, (f"autopilot.{key} is',
     '    return SELF, (f"autopilot.{key} is',
     _P + "test_approval_bad_value_reads_human[Self]"),
    ("questions: an unknown risk is taken under risk", AUTOPILOT,
     '    if policy == RISK and risk["known"] and risk["risk"] == "low":\n',
     '    if policy == RISK and (risk["risk"] == "low" or not risk["known"]):\n',
     _P + "test_questions_risk_takes_only_low[status: spec-stop]"),
    ("questions: the human policy takes the recommendation", AUTOPILOT,
     "    if policy == SELF:\n",
     "    if policy in (SELF, HUMAN):\n",
     _P + "test_questions_human_stops[low]"),
    ("approve runs with autopilot unarmed", AUTOPILOT,
     '    if not settings(top)["armed"]:\n',
     "    if False:\n",
     _P + "test_autopilot_approve_refuses_unarmed"),
    ("approve ignores a policy refusal", AUTOPILOT,
     '    if not got["allow"]:\n',
     "    if False:\n",
     _P + "test_autopilot_approve_refused_prints_reason[human-low]"),
    ("next offers the autopilot route when the policy refuses", AUTOPILOT,
     '    if got["allow"]:\n',
     "    if True:\n",
     _P + "test_next_approve_phase_names_the_human_when_the_policy_refuses"),
    ("questions-check: the recommendation need not be first", AUTOPILOT,
     "    if not options or RECOMMENDED not in options[0][1] or len(marked) != 1:\n",
     "    if not options:\n",
     _P + "test_questions_file_recommendation_not_first_invalid"),
    ("questions-check: one option is enough", AUTOPILOT,
     "    if not 2 <= len(options) <= 4:\n",
     "    if not 1 <= len(options) <= 4:\n",
     _P + "test_questions_file_one_option_invalid"),
    ("questions-check: an option needs no cost", AUTOPILOT,
     "                 if not any(_COST_RE.match(line) for line in lines)]\n",
     "                 if False]\n",
     _P + "test_questions_file_option_without_cost_invalid"),
    ("questions-check: a question needs no research", AUTOPILOT,
     "    if not any(_RESEARCH_RE.match(line) for line in preamble):\n",
     "    if False:\n",
     _P + "test_questions_file_without_research_invalid"),
    ("questions-check: taken while the policy says stop", AUTOPILOT,
     '        if decision["action"] != TAKE:\n',
     "        if False:\n",
     _P + "test_questions_file_taken_while_the_policy_stops_invalid[human-low]"),
    ("questions-check: taken a non-recommended option", AUTOPILOT,
     "        if not options or oid != options[0][0]:\n",
     "        if not options:\n",
     _P + "test_questions_file_taken_non_recommended_invalid"),
    ("the library writes an autopilot receipt the policy refuses", TICKET,
     "        if refusal is not None:\n",
     "        if False:\n",
     _P + "test_the_library_refuses_an_autopilot_receipt_the_policy_denies"),
    ("accepted keeps an autopilot receipt the policy no longer allows", TICKET,
     '    if isinstance(decision, dict) and decision.get("allow") is True:\n',
     "    if True:\n",
     _CT + "test_autopilot_receipt_demoted_when_the_policy_no_longer_allows[human]"),
    ("accepted keeps an autopilot receipt without allowCliApproval", TICKET,
     '    if not cli_approval_allowed(top):\n        return "scope.allowCliApproval',
     '    if False:\n        return "scope.allowCliApproval',
     _CT + "test_autopilot_receipt_needs_allow_cli_even_when_the_policy_says_yes"),
    ("accepted reads a policy it cannot import as a yes", TICKET,
     "    except Exception as exc:  # pylint: disable=broad-except\n"
     '        return (f"whether autopilot.approval',
     "    except Exception as exc:  # pylint: disable=broad-except\n"
     '        return None and (f"whether autopilot.approval',
     _CT + "test_autopilot_receipt_demoted_when_policy_module_missing"),
    ("the guard allows autopilot approve whatever the policy says", GUARD,
     '    if isinstance(decision, dict) and decision.get("allow") is True:\n',
     "    if True:\n",
     _SG + "test_autopilot_approve_is_refused_when_the_policy_says_no[human-low-True-module]"),
    ("the guard never looks at autopilot approve", GUARD,
     "        return _autopilot_refusal(written, top)\n",
     "        return None\n",
     _SG + "test_autopilot_approve_is_refused_when_the_policy_says_no[human-low-True-module]"),
    ("the guard allows a chained autopilot approve", GUARD,
     "    bare = _AUTOPILOT_BARE_RE.fullmatch(command)\n",
     "    bare = _AUTOPILOT_BARE_RE.match(command)\n",
     _SG + "test_autopilot_approve_that_is_not_the_bare_command_is_refused"
     "[python3 hooks/scripts/crew_autopilot.py approve --root . --ticket T-1; rm x-module]"),
    ("the guard reads a policy crash as a yes", GUARD,
     "    except Exception as exc:  # pylint: disable=broad-except\n"
     '        return (f"could not tell whether autopilot.approval',
     "    except Exception as exc:  # pylint: disable=broad-except\n"
     '        return None and (f"could not tell whether autopilot.approval',
     _SG + "test_a_policy_that_cannot_be_told_is_refused"),
    ("autopilot approves through the owner's group confirm", TICKET,
     "    if via == AUTOPILOT and expect is not None:\n",
     "    if False:\n",
     _CT + "test_autopilot_approve_with_a_group_confirm_is_refused[matching]"),
    ("the owner-only gate refuses the owner's own group confirm", TICKET,
     "    if via == AUTOPILOT and expect is not None:\n",
     "    if expect is not None:\n",
     _CT + "test_owner_group_confirm_still_records_beside_the_autopilot_gate"),
    ("the command drops `human` always stops", COMMAND,
     "`human` always stops",
     "`human` usually stops",
     _P + "test_command_routes_approval_through_policy"),
    # ---- amendment 2026-09-27 (plan Step 6): the approve exception to T-0018's
    # read-only module. approve is the only writer; route and status are T-0018's.
    ("a read-only subcommand writes", AUTOPILOT,
     '    crew_json = _read_json(os.path.join(top, ".crew", "crew.json"))\n',
     '    os.makedirs(os.path.join(top, ".work"), exist_ok=True)\n'
     '    open(os.path.join(top, ".work", "settings-ran"), "a").close()\n'
     '    crew_json = _read_json(os.path.join(top, ".crew", "crew.json"))\n',
     _P + "test_approve_is_the_only_writing_subcommand"),
    ("approve writes beside the receipt", AUTOPILOT,
     "        top, ticket, by=f\"autopilot:{got['policy']}\", via=crew_ticket.AUTOPILOT)\n",
     "        top, ticket, by=f\"autopilot:{got['policy']}\", via=crew_ticket.AUTOPILOT)\n"
     '    open(os.path.join(crew_ticket.ticket_dir(top, ticket), "approved"), "w").close()\n',
     _P + "test_approve_is_the_only_writing_subcommand"),
    ("a refused approve still writes", AUTOPILOT,
     "        return 2, f\"refused: {got['reason']}; {human}\"\n",
     '        crew_ticket.approve(top, ticket, by="refused", via=crew_ticket.CLI)\n'
     "        return 2, f\"refused: {got['reason']}; {human}\"\n",
     _P + "test_approve_refused_writes_nothing"),
    ("status reads the policy", AUTOPILOT,
     '    return f"owner - types {command}" if command else "owner - see the phase reason"\n',
     '    if phase == "approve":\n'
     "        return f\"owner - {_approval_hint(top, result['ticket'])}\"\n"
     '    return f"owner - types {command}" if command else "owner - see the phase reason"\n',
     _S + "test_route_and_status_unaffected_by_approval_policy[self]"),
    ("approve becomes a command subcommand", AUTOPILOT,
     'SUBCOMMANDS = ("status", "run", "assign", "goal", "focus")\n',
     'SUBCOMMANDS = ("status", "run", "assign", "goal", "focus", "approve")\n',
     _R + "test_policy_subcommands_are_not_command_subcommands"),
    ("the command says nothing approves", COMMAND,
     "Nothing here accepts a review or skips a phase, and nothing approves except\n"
     "section 3's `approve`, under the approval policy; it writes `approval.json`, "
     "`scope-tickets.json`\n",
     "Nothing here approves, accepts a review, or skips a phase.\n",
     _P + "test_command_states_the_approve_exception"),
    # ---- T-0010 review round 3 (T-0010-solo--V7Q7fm): the BLOCK, both FIXes,
    # and each one's neighbour
    ("BLOCK: the module docstring says approve writes only approval.json", AUTOPILOT,
     "`<git-common-dir>/crew/`: `approval.json`; `scope-tickets.json`, the scope\n"
     "ramp's list, on a ticket's first approval; and, when the review ledger is\n",
     "`<git-common-dir>/crew/`: `approval.json` and nothing else; when the review ledger is\n",
     _P + "test_every_statement_of_the_exception_names_what_approve_writes"),
    ("BLOCK: the command drops the ledger's successor continuation", COMMAND,
     "on a ticket's first approval, and a distinct successor plan's NEEDS_REPLAN -> IN_REVIEW "
     "ledger move.\n",
     "on a ticket's first approval.\n",
     _P + "test_every_statement_of_the_exception_names_what_approve_writes"),
    ("BLOCK: README says approve writes only the approval receipt", README,
     "— except `approve`, and only when `autopilot.approval` allows it",
     "— except `approve`, which writes only the approval receipt, and only when "
     "`autopilot.approval` allows it",
     _P + "test_no_statement_of_the_exception_says_approve_writes_only_the_receipt"),
    ("approve of a successor plan leaves the ledger NEEDS_REPLAN", TICKET,
     "    if ledger.get(\"state\") == review_ledger.NEEDS_REPLAN:\n",
     "    if False:\n",
     _P + "test_approve_of_a_successor_plan_writes_the_receipt_and_moves_the_ledger"),
    ("FIX: status for a named ticket reads the approval policy", AUTOPILOT,
     '"disagreement": "", "next": next_phase(top, ticket, policy=False)}',
     '"disagreement": "", "next": next_phase(top, ticket)}',
     _S + "test_status_at_approve_reads_the_same_under_an_allowing_policy[self-T-1]"),
    ("status with no ticket reads the approval policy", AUTOPILOT,
     "        pick = bare = resume_target(top, policy=False)\n",
     "        pick = bare = resume_target(top)\n",
     _S + "test_status_at_approve_reads_the_same_under_an_allowing_policy[self-None]"),
    ("status at open questions reads the questions policy", AUTOPILOT,
     "(_question_hint(top, ticket) if policy else POLICY_FREE_QUESTIONS)",
     "_question_hint(top, ticket)",
     _S + "test_status_at_open_questions_reads_the_same_under_every_questions_policy[T-1]"),
    ("FIX: README's phase table sends every unaccepted approval to the human", README,
     "stop — **you** type `/crew:approve <id>`, unless `autopilot.approval` allows",
     "stop — **you** type `/crew:approve <id>`, unless nothing allows",
     _P + "test_readme_phase_table_names_the_policy_route_at_approve"),
    # Successor after round 4: round 4's three FIXes, each red on its named test.
    ("FIX: an unreadable config reads the default policies", AUTOPILOT,
     '    if state == "corrupt":\n        return ".crew/config.json exists but could not',
     '    if state == "no such state":\n        return ".crew/config.json exists but could not',
     _P + "test_settings_unreadable_config_reads_policies_unknown[{bad]"),
    ("FIX: a non-object autopilot block reads the defaults", AUTOPILOT,
     "    if block is not None and not isinstance(block, dict):\n",
     "    if False:\n",
     _P + "test_question_policy_stops_when_autopilot_not_an_object"),
    ("FIX: an unknown approval policy reaches the risk branch", AUTOPILOT,
     "    if policy == UNKNOWN:\n        why = (f\"could not tell autopilot.approval",
     "    if False:\n        why = (f\"could not tell autopilot.approval",
     _P + "test_approval_policy_refuses_when_autopilot_not_an_object"),
    ("FIX: the settings text drops the policies", AUTOPILOT,
     '                                approval=result["approval"], questions=result["questions"])]',
     "                                )]",
     _P + "test_settings_cli_text_prints_both_policies[self-human]"),
    ("FIX: _one_line is defined twice", AUTOPILOT,
     "def _line(**fields):\n",
     "def _one_line(value):\n    return value\n\n\ndef _line(**fields):\n",
     "tests/test_crew_autopilot.py::test_module_defines_each_function_once"),
)
