"""The crew 1.0 web-testing (lane A) mutations, appended to `sabotage.py`'s
MUTATIONS. Kept apart for the reason the other `sabotage_*.py` files give:
`sabotage.py` sits near `.pylintrc`'s max-module-lines. Run that file, not
this one.

Each was also run by hand against the tracked file, restored from a scratch
copy with `cp` and confirmed with `diff`. The auth-leak and visual mutations
were additionally run against `_test/run-tests.sh` and `_test/webtest-guard.ps1`
(through `test_webtest_guard_pwsh.py`), and both drivers went red.

The "round 1" block below is one mutation per Codex round-1 finding (lane A,
webtest-a-r1): each puts the reported defect back, and its target test is the
regression test written for that finding. The skip-scan, exclusion and
storageState ones were also run against both drivers by hand.
"""
import os

CREW = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_SCRIPTS = os.path.join(CREW, "hooks", "scripts")
GUARD = os.path.join(_SCRIPTS, "webtest_guard.py")
RULES = os.path.join(_SCRIPTS, "webtest_rules.py")
SCAFFOLD = os.path.join(_SCRIPTS, "webtest_scaffold.py")
PROMPT = os.path.join(_SCRIPTS, "review_prompt.py")
PATCH = os.path.join(_SCRIPTS, "review_patch.py")
RUN = os.path.join(_SCRIPTS, "review_run.py")
MIGRATE = os.path.join(_SCRIPTS, "crew_migrate.py")
_T = "tests/test_webtest_guard.py::"
_S = "tests/test_webtest_scaffold.py::"
_EXCLUDED_BY = ("    return any(path == rpath and (want is None or want in text or want in "
                "(title or \"\"))\n")

WEBTEST_MUTATIONS = (
    ("webtest: .fixme( is no longer a skip", GUARD,
     "SKIP_NAMES = (\"skip\", \"fixme\")\n",
     "SKIP_NAMES = (\"skip\",)\n",
     _T + "test_skips_blocks_a_skip_added_since_the_base"),
    ("webtest: an exclusion's text qualifier is ignored", GUARD,
     _EXCLUDED_BY,
     "    return any(path == rpath and (want is None or True)\n",
     _T + "test_skips_blocks_when_the_exclusion_names_something_else"),
    ("webtest: an exclusion anywhere in the spec counts", GUARD,
     "    for line in _section(text, \"Exclusions\"):\n",
     "    for line in text.splitlines():\n",
     _T + "test_skips_exclusion_outside_the_exclusions_section_does_not_count"),
    ("webtest: untracked spec files are not scanned", GUARD,
     "    out += [(None, rel.strip()) for rel in untracked.splitlines() if rel.strip()]\n",
     "    out += []\n",
     _T + "test_skips_blocks_a_skip_in_a_new_untracked_spec_file"),
    ("webtest: a git failure in skips reads as a pass", GUARD,
     "    if skips is None or not head:\n        return EXIT_UNKNOWN,",
     "    if skips is None or not head:\n        return EXIT_OK,",
     _T + "test_skips_outside_a_repository_is_unknown_not_a_pass"),
    ("webtest: a tracked .auth segment is not a leak", GUARD,
     "             if p and (\".auth\" in p.split(\"/\") or p in named)]\n",
     "             if p and p in named]\n",
     _T + "test_auth_leak_blocks_a_tracked_auth_file"),
    ("webtest: auth-leak's could-not-tell reads as a pass", GUARD,
     "        return EXIT_UNKNOWN, [\"webtest auth-leak: UNKNOWN",
     "        return EXIT_OK, [\"webtest auth-leak: UNKNOWN",
     _T + "test_auth_leak_outside_a_repository_is_unknown_not_a_pass"),
    ("webtest: visual off the pinned image reads as PASS", GUARD,
     "    return EXIT_SKIP, [f\"webtest visual: UNVERIFIED",
     "    return EXIT_OK, [f\"webtest visual: UNVERIFIED",
     _T + "test_visual_off_the_pinned_image_is_skipped_as_unverified"),
    ("webtest: a real visual run's 77 passes through as SKIP", GUARD,
     "    code = EXIT_OK if rc == 0 else EXIT_FINDING\n",
     "    code = rc\n",
     _T + "test_visual_inside_the_pinned_image_runs_and_reports_its_exit"),
    ("webtest: the review prompt hands skips over as excluded", PROMPT,
     "    tag = \"EXCLUDED\" if row.get(\"excluded\") else \"FINDING\"\n",
     "    tag = \"EXCLUDED\"\n",
     _T + "test_review_prompt_hands_open_skips_to_the_reviewer_as_findings"),
    ("webtest: review.json carries excluded rows as open", RUN,
     "    return [r for r in rows if isinstance(r, dict) and not r.get(\"excluded\")]\n",
     "    return [r for r in rows if isinstance(r, dict)]\n",
     _T + "test_review_json_carries_only_the_open_skip_rows"),
    ("webtest: the review manifest drops the artefact listing", PATCH,
     "        manifest[\"webtest\"] = listing\n",
     "        pass\n",
     _T + "test_review_patch_manifest_lists_the_web_artifacts"),
    ("webtest scaffold: an existing MCP server is overwritten", SCAFFOLD,
     "    added = [n for n in servers if n not in existing]\n",
     "    added = list(servers)\n",
     _S + "test_existing_files_and_servers_are_never_overwritten"),
    ("webtest scaffold: the dry run writes", SCAFFOLD,
     "        if args.apply:\n            _write(root, rel, text)\n",
     "        _write(root, rel, text)\n",
     _S + "test_dry_run_is_the_default_and_writes_nothing"),
    ("webtest scaffold: init-agents' .mcp.json rewrite is kept", SCAFFOLD,
     "    if before is not None and after != before:\n",
     "    if False:\n",
     _S + "test_init_agents_rewriting_mcp_json_is_undone_keeping_its_new_server"),
    ("webtest scaffold: agents regenerate over a complete set", SCAFFOLD,
     "    if not missing:\n        return",
     "    if False:\n        return",
     _S + "test_agents_are_skipped_when_all_three_exist"),
    ("migrate: pm.authority autonomous is dropped silently", MIGRATE,
     "    if isinstance(pm, dict) and pm.get(\"authority\") == \"autonomous\":\n",
     "    if False:\n",
     "tests/test_migrate.py::test_autonomous_pm_authority_is_noted_in_report_and_crew_json"),
    ("migrate: the autopilot note never reaches the report", MIGRATE,
     "        plan[\"notes\"].extend(crew.get(\"notes\", []))\n",
     "",
     "tests/test_migrate.py::test_autonomous_pm_authority_is_noted_in_report_and_crew_json"),

    # ---- round 1 (webtest-a-r1), one per finding
    ("r1 review_run:148: a stale findings.json is trusted, not re-run", RUN,
     "    code, lines = webtest_guard.check_skips(root, ticket, bundle_sha256=None if reasons "
     "else bundle)\n",
     "    code, lines = webtest_guard.EXIT_OK, [\"\"]\n",
     _T + "test_review_a_skip_added_after_a_clean_check_is_found_not_clean"),
    ("r1 review_run:148: a tree changed after the bundle still vouches", RUN,
     "        if current and current.get(\"bundle_sha256\") != bundle:\n",
     "        if False:\n",
     _T + "test_review_a_tree_changed_after_the_bundle_is_incomplete"),
    ("r1 review_run:166: open skips never touch the verdict", RUN,
     "        if result[\"verdict\"] == review_verdict.CLEAN:\n"
     "            result[\"verdict\"] = review_verdict.FINDINGS\n",
     "        if False:\n            result[\"verdict\"] = review_verdict.FINDINGS\n",
     _T + "test_review_an_open_skip_overrides_a_clean_reviewer"),
    ("r1 guard:142: prose mentioning skip: is an exemption", GUARD,
     "_EXCLUSION_RE = re.compile(r\"\"\"^[-*+]\\s+skip:",
     "_EXCLUSION_RE = re.compile(r\"\"\"^.*?\\bskip:",
     _T + "test_skips_prose_or_a_subsection_under_exclusions_is_not_an_exemption"),
    ("r1 guard:142: a subsection under Exclusions counts", GUARD,
     "                if _HEADING_RE.match(rest):\n                    break\n",
     "                if _HEADING_RE.match(rest) and rest.startswith(\"## \"):\n"
     "                    break\n",
     _T + "test_skips_prose_or_a_subsection_under_exclusions_is_not_an_exemption"),
    ("r1 guard:153: a rename into a spec keeps its old skips as baseline", GUARD,
     "        if old is not None and (_is_spec(old) or not _is_spec(new)):\n",
     "        if old is not None:\n",
     _T + "test_skips_blocks_a_rename_that_turns_a_skipping_helper_into_a_spec"),
    ("r1 guard:159: only spec files are scanned", GUARD,
     "        if not (_is_spec(new) or _in_test_dir(new) or new in reachable):\n",
     "        if not _is_spec(new):\n",
     _T + "test_skips_blocks_a_skip_added_in_a_helper_under_a_test_dir"),
    ("r1 guard:159: helpers a spec imports are not followed", GUARD,
     "            dep = _resolve_import(files, rel, match.group(1))\n",
     "            dep = None\n",
     _T + "test_skips_blocks_a_skip_in_a_helper_a_spec_imports_from_anywhere"),
    ("r1 guard:79: computed test['skip'] is not a skip", GUARD,
     "        elif (kind == \"p\" and value == \"[\" and nxt[0] == \"str\" and nxt[1] in SKIP_NAMES\n",
     "        elif (False\n",
     _T + "test_skips_blocks_computed_aliased_and_multiline_forms"),
    ("r1 guard:79: an annotation must sit on one line", GUARD,
     "              and after[0] == \"str\" and after[1] in ANNOTATION_TYPES):\n",
     "              and after[0] == \"str\" and after[1] in ANNOTATION_TYPES and after[2] == _line):\n",
     _T + "test_skips_blocks_computed_aliased_and_multiline_forms"),
    ("r1 guard:79: comments are scanned as code", GUARD,
     "        elif text.startswith(\"//\", i):\n",
     "        elif False:\n",
     _T + "test_skips_allows_skip_text_in_comments_strings_and_regexes"),
    ("r1 guard:147: a title exclusion ignores the call's title", GUARD,
     _EXCLUDED_BY,
     "    return any(path == rpath and (want is None or want in text)\n",
     _T + "test_skips_a_title_exclusion_matches_a_call_split_across_lines"),
    ("r1 guard:223: a const-bound storageState is not resolved", GUARD,
     "            if None not in bound and len(set(bound)) == 1:\n",
     "            if False:\n",
     _T + "test_auth_leak_resolves_const_shorthand_and_windows_storage_state"),
    ("r1 guard:223: a Windows-form storageState is not normalised", GUARD,
     r'    path = re.sub(r"/+", "/", path.replace("\\", "/"))' + "\n",
     "    path = path\n",
     _T + "test_auth_leak_resolves_const_shorthand_and_windows_storage_state"),
    ("r1 guard:223: an unresolvable storageState passes", GUARD,
     "    if unresolved and not declared:\n",
     "    if False:\n",
     _T + "test_auth_leak_fails_closed_on_a_storage_state_it_cannot_resolve"),
    ("r1 guard:254: no container marker is needed", GUARD,
     "    if not markers:\n        return _unverified(",
     "    if False:\n        return _unverified(",
     _T + "test_visual_the_pinned_env_without_container_evidence_is_unverified"),
    ("r1 guard:254: the image's browsers are not matched to the pin", GUARD,
     "    if not os.path.isdir(os.path.join(BROWSERS_DIR, chromium)):\n",
     "    if False:\n",
     _T + "test_visual_the_pinned_env_without_container_evidence_is_unverified"),
    ("r1 rules:41: the skip rule watches only spec/test ts/js", RULES,
     "SPEC_PATHS = tuple(f\"**/*{ext}\" for ext in webtest_guard.JS_EXTS)\n",
     "SPEC_PATHS = (\"**/*.spec.ts\", \"**/*.spec.js\", \"**/*.test.ts\", \"**/*.test.js\")\n",
     _T + "test_rules_the_skip_rule_watches_every_file_the_guard_reads"),
    ("r1 rules:43: the auth rule ignores storageState targets", RULES,
     "        {\"paths\": auth_paths(root), \"reach\": \"local\",\n",
     "        {\"paths\": list(AUTH_PATHS[:3]) + [\"**/.auth/**\"], \"reach\": \"local\",\n",
     _T + "test_rules_the_auth_rule_watches_storage_state_files"),
    ("r1 review_prompt:197: the overflow file is truncated to the inline limit", PROMPT,
     "        _write_file(overflow, \"\\n\".join(every) + \"\\n\")\n",
     "        _write_file(overflow, \"\\n\".join(every[:WEBTEST_FINDINGS_MAX]) + \"\\n\")\n",
     _T + "test_review_prompt_hands_over_every_row_through_a_file_past_the_inline_limit"),
    ("r1 review_prompt:197: rows past the limit are dropped inline", PROMPT,
     "    else:\n        out += every\n",
     "    else:\n        out += every[:WEBTEST_FINDINGS_MAX]\n",
     _T + "test_review_prompt_without_an_out_dir_puts_every_row_inline"),
    ("r1 review_prompt:197: the overflow file needs no READ", RUN,
     "        parts.append(review_prompt.WEBTEST_FINDINGS_FILE)\n",
     "        pass\n",
     _T + "test_review_the_overflow_file_needs_its_own_read"),
    ("r1 scaffold:208: an existing config is not checked", SCAFFOLD,
     "            gaps = config_gaps(_read(os.path.join(root, existing)) or \"\")\n",
     "            gaps = []\n",
     _S + "test_a_minimal_existing_config_is_reported_missing_projects_not_success"),
    ("r1 scaffold:244: the planner alone marks the agents installed", SCAFFOLD,
     "for a in AGENT_FILES if not os.path.exists",
     "for a in AGENT_FILES[:1] if not os.path.exists",
     _S + "test_only_the_planner_present_still_runs_init_agents"),
    ("r1 scaffold:244: agents init-agents left missing still succeed", SCAFFOLD,
     "    if still:\n",
     "    if False:\n",
     _S + "test_agents_init_agents_did_not_write_are_reported_and_fail"),
    ("r1 scaffold:250: init-agents runs unpinned", SCAFFOLD,
     "INIT_AGENTS = (\"npx\", \"-y\", f\"--package=@playwright/test@{webtest_guard.PINNED_PLAYWRIGHT}\",\n"
     "               \"playwright\", \"init-agents\")\n",
     "INIT_AGENTS = (\"npx\", \"playwright\", \"init-agents\")\n",
     _S + "test_init_agents_is_pinned_to_the_verified_playwright"),
    ("r1 scaffold:250: a customised agent is not restored", SCAFFOLD,
     "    out += _restore_agents(root, kept)\n",
     "    out += []\n",
     _S + "test_a_customised_agent_survives_init_agents"),
)
