"""The L-0574 mutations: `review_checks.py` and `review_run.py`'s pre-review
gate. Same tuple shape as `sabotage.py`'s MUTATIONS -- (label, target, find,
replace, test) -- and appended to it there. Run `sabotage.py`, not this file.

Each is a way the pre-review checks could read an unknown as a pass, let a
new finding through, or spend a round they promised not to.
"""
import os

CREW = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHECKS = os.path.join(CREW, "hooks", "scripts", "review_checks.py")
RUN = os.path.join(CREW, "hooks", "scripts", "review_run.py")
INSTALL_MAP = os.path.join(os.path.dirname(os.path.dirname(CREW)), ".crew", "codemap",
                           "install-scripts.md")
_C = "tests/test_review_checks.py::"
_R = "tests/test_review_run_prereview.py::"
_L = "tests/test_review_run_launch.py::"

PREREVIEW_MUTATIONS = (
    ("a check that could not run reports pass", CHECKS,
     "        result.update(status=COULD_NOT, detail=_detail(exc))\n",
     "        result.update(status=PASS, detail=_detail(exc))\n",
     _C + "test_could_not_check_cases"),
    ("the base count is ignored, every finding is new", CHECKS,
     '        added = n - counts["base"][key]\n',
     "        added = n\n",
     _C + "test_existing_finding_moved_is_not_new"),
    ("a parse abort is not treated as unchecked", CHECKS,
     "                if abort:\n                    unparsed.add(rel)\n",
     "                if False:\n                    unparsed.add(rel)\n",
     _C + "test_parse_abort_either_side"),
    ("shellcheck's error exit is accepted as a run", CHECKS,
     '    rows, odd = _rows(proc, (0, 1), "shellcheck", extract)\n',
     '    rows, odd = _rows(proc, (0, 1, 4), "shellcheck", extract)\n',
     _C + "test_could_not_check_cases"),
    ("the linter config is dropped from the checked trees", CHECKS,
     "            with_base = _materialise(root, selected, _config_blobs(root, manifest), tmp)\n",
     "            with_base = _materialise(root, selected, {}, tmp)\n",
     _C + "test_path_dependent_config_applies"),
    ("a missing record reads as None", CHECKS,
     '        return {"result": NOT_RECORDED, "reason": f"no {name} in the scratch directory"}\n',
     "        return None\n",
     _C + "test_a_missing_or_torn_record_is_not_recorded_never_none"),
    ("exit 1 with no findings is accepted as clean", CHECKS,
     "    if (proc.returncode == 1) != bool(rows):\n",
     "    if False:\n",
     _C + "test_could_not_check_cases"),
    ("an unreadable base drops the linter config silently", CHECKS,
     '    if _git(root, "rev-parse", "--verify", "--quiet", f"{base}^{{commit}}").returncode != 0:\n',
     "    if False:\n",
     _C + "test_could_not_check_cases"),
    ("a record of the wrong shape is copied into review.json", CHECKS,
     "    if not (payload.get(\"result\") in (PASS, FAIL, COULD_NOT, NOT_CONFIGURED)\n",
     "    if False and not (payload.get(\"result\") in (PASS, FAIL, COULD_NOT, NOT_CONFIGURED)\n",
     _C + "test_a_record_of_the_wrong_shape_is_not_recorded"),
    ("a line number inside a message makes a moved finding new", CHECKS,
     "        text = pattern.sub(replacement, text)\n",
     "        text = text\n",
     _C + "test_line_numbers_inside_a_message_do_not_make_a_finding_new"),
    ("every digit is normalised, so a changed value cancels against the base", CHECKS,
     "        text = pattern.sub(replacement, text)\n    return text\n",
     '        text = pattern.sub(replacement, text)\n    return re.sub(r"\\d+", "N", text)\n',
     _C + "test_digits_that_are_not_positions_still_tell_findings_apart"),
    ("a parse failure in one file hides a new finding in another", CHECKS,
     "    if new:\n        detail = ",
     "    if new and not aborted:\n        detail = ",
     _C + "test_a_parse_failure_does_not_hide_a_new_finding_elsewhere"),
    ("--allow-unverified passes a new finding hidden by a parse failure", CHECKS,
     "    if new:\n        detail = ",
     "    if new and not aborted:\n        detail = ",
     _R + "test_allow_unverified_never_passes_a_new_finding_beside_a_parse_failure"),
    ("a row with no message is accepted with an empty one", CHECKS,
     "    if not isinstance(message, str):\n",
     "    if False:\n",
     _C + "test_a_row_with_no_message_is_could_not_check"),
    ("an unreadable .py is reported as nothing", CHECKS,
     '                          "--extend-select", "E902"]\n',
     "                          ]\n",
     _C + "test_real_ruff_unreadable_file_is_could_not_check"),
    ("a [bracketed] PowerShell name matches nothing", CHECKS,
     "        $params = @{ Path = [System.Management.Automation.WildcardPattern]::Escape($path) }\n",
     "        $params = @{ Path = $path }\n",
     _C + "test_real_pssa_reads_awkward_names_and_utf16"),
    ("--allow-unverified overrides a new finding", RUN,
     "    if verdict == review_checks.COULD_NOT and args.allow_unverified:\n",
     "    if args.allow_unverified:\n",
     _R + "test_new_finding_is_not_overridable"),
    ("the pre-review refusal is dropped and a round is reserved", RUN,
     "        refused = prereview_gate(args)\n",
     "        prereview_gate(args)\n        refused = None\n",
     _R + "test_new_finding_refuses_before_reserve"),
    ("an expired or stood-down incident stands the checks down", RUN,
     '    if incident["active"]:\n        crew_incident.log_skip(args.root, "prereview-checks"',
     '    if incident["present"]:\n        crew_incident.log_skip(args.root, "prereview-checks"',
     _R + "test_only_an_active_incident_stands_down"),
    ("a config renamed away is reloaded from the base", CHECKS,
     "        if rel in at_base and rel not in renamed_away:\n",
     "        if rel in at_base:\n",
     _C + "test_a_config_renamed_away_is_gone_from_the_bundle"),
    ("a _note under preReview is accepted", CHECKS,
     'BLOCK_KEYS = {"linters"}',
     'BLOCK_KEYS = {"linters", "_note"}',
     _C + "test_a_note_in_the_block_is_an_unknown_key"),
    ("a record whose result contradicts its checks is accepted", CHECKS,
     '            payload["result"] != overall(payload["checks"], configured) or \\\n',
     '            False or \\\n',
     _C + "test_a_record_that_contradicts_itself_is_not_recorded"),
    ("a check row of the wrong shape is accepted", CHECKS,
     "            and all(_is_check_row(c) for c in payload[\"checks\"])\n",
     "            and all(isinstance(c, dict) for c in payload[\"checks\"])\n",
     _C + "test_a_record_that_contradicts_itself_is_not_recorded"),
    # review round 4 (owner grant 2026-10-02), each fix and the neighbour it was checked against
    ("a verify map that is not an object reads as unconfigured", CHECKS,
     "    if not isinstance(data, dict):\n        # Valid JSON",
     "    if False:\n        # Valid JSON",
     _C + "test_a_verify_map_that_is_not_an_object_is_could_not_check"),
    ("a bad row throws away the rows already read", CHECKS,
     '            yield _BadRow(where, f"{tool} reported a row it could not read "\n',
     '            raise CouldNotCheck(f"{tool} reported a row it could not read "\n',
     _C + "test_a_bad_row_does_not_discard_a_known_new_finding"),
    ("a bad base row leaves its file checked against a short base", CHECKS,
     '                    if row.where is not None and row.where[0] == "base":\n',
     "                    if False:\n",
     _C + "test_a_bad_base_row_leaves_that_file_unchecked"),
    ("a status that disagrees with its rows throws the rows away", CHECKS,
     '        yield _BadRow(None, f"{tool} exited {proc.returncode} but reported {len(rows)} "\n',
     '        raise CouldNotCheck(f"{tool} exited {proc.returncode} but reported {len(rows)} "\n',
     _C + "test_a_status_that_disagrees_with_its_rows_keeps_the_rows"),
    ("the bundle hash is read again after the linters ran", RUN,
     "        results, configured, bundle = review_checks.run_checks_bound(\n"
     "            args.root, args.manifest, _trusted(args.manifest, args.scratch))\n",
     "        results, configured, _ = review_checks.run_checks_bound(\n"
     "            args.root, args.manifest, _trusted(args.manifest, args.scratch))\n"
     "        with open(args.manifest, encoding=\"utf-8\") as fh:\n"
     "            bundle = json.load(fh).get(\"bundle_sha256\")\n",
     _R + "test_the_record_is_bound_to_the_manifest_the_checks_read"),
    ("a timeout kills only the direct child", CHECKS,
     "        else:\n            os.killpg(proc.pid, signal.SIGKILL)\n    except OSError:\n",
     "        else:\n            pass\n    except OSError:\n",
     _C + "test_the_timeout_holds_when_a_child_keeps_the_output_open"),
    ("a record with a flag its result cannot carry is accepted", CHECKS,
     "            not _flags_fit(payload):\n",
     "            False:\n",
     _C + "test_a_record_that_contradicts_itself_is_not_recorded"),
    ("a check row whose status disagrees with its findings is accepted", CHECKS,
     '    if (row.get("status") == FAIL) != bool(row["new"]) or (\n',
     '    if False and (\n',
     _C + "test_a_record_that_contradicts_itself_is_not_recorded"),
    # review round 5 (owner grant 2026-10-02), each fix and its neighbour
    ("the verify map is read from the live tree, not the bundle's base", CHECKS,
     "    if mode is not None:\n        return _git_blob(root, f\"{manifest['base']}:{rel}\")\n",
     "    if False:\n        return _git_blob(root, f\"{manifest['base']}:{rel}\")\n",
     _C + "test_the_config_is_the_bundles_not_the_live_trees"),
    ("a verify map the bundle changes is read from the base instead", CHECKS,
     "        if entry.get(\"path\") == rel:\n            if entry.get(\"status\") == \"D\":\n",
     "        if False:\n            if entry.get(\"status\") == \"D\":\n",
     _C + "test_a_config_change_the_bundle_carries_is_the_one_used"),
    ("an unreadable manifest reads as nothing configured", CHECKS,
     "        if manifest_problem is not None:\n            raise manifest_problem\n",
     "        if manifest_problem is not None:\n            return [], False\n",
     _C + "test_an_unreadable_manifest_is_could_not_check_even_unconfigured"),
    ("a manifest with no bundle hash is accepted", CHECKS,
     "        if not _bundle_hash(manifest):\n",
     "        if False:\n",
     _C + "test_a_manifest_without_a_bundle_hash_is_could_not_check"),
    ("a record matches a missing bundle hash", CHECKS,
     "    if not isinstance(bundle_sha256, str) or not bundle_sha256:\n",
     "    if False:\n",
     _C + "test_recorded_never_matches_a_missing_bundle_hash"),
    ("a symlink's target text is a base for the file that replaces it", CHECKS,
     "                and entry.get(\"old_mode\") not in SKIPPED_MODES:\n",
     "                and True:\n",
     _C + "test_a_symlink_turned_regular_file_has_no_base"),
    ("a submodule turned regular file is skipped", CHECKS,
     "        if entry.get(\"status\") == \"D\":\n            continue\n        if entry.get(\"new_mode\")",
     "        if entry.get(\"status\") == \"D\" or entry.get(\"submodule\"):\n            continue\n"
     "        if entry.get(\"new_mode\")",
     _C + "test_a_submodule_turned_regular_file_is_linted"),
    ("a symlinked linter config is handed over as its target text", CHECKS,
     "                if entry.get(\"new_mode\") in SKIPPED_MODES:\n"
     "                    raise CouldNotCheck(f\"the linter config",
     "                if False:\n"
     "                    raise CouldNotCheck(f\"the linter config",
     _C + "test_a_linter_config_that_is_a_symlink_is_could_not_check"),
    ("a Windows timeout ends the linter but not its job", CHECKS,
     "        if job is not None:\n            job.terminate()\n        else:\n            os.killpg(",
     "        if False:\n            job.terminate()\n        else:\n            os.killpg(",
     _C + "test_the_windows_timeout_kills_the_whole_job"),
    ("a linter is resolved with the current directory searched", CHECKS,
     "    exe = resolve_executable(argv[0])\n",
     "    exe = shutil.which(argv[0])\n",
     _C + "test_a_linter_is_never_found_in_the_current_directory"),
    # round-7 class sweep (owner decision 2026-10-02): the round-6 findings and the classes
    ("git is run by bare name", CHECKS,
     '    git = resolve_executable("git")\n',
     '    git = "git"\n',
     _C + "test_git_is_never_taken_from_the_current_directory"),
    ("the review runner finds a provider with shutil.which", RUN,
     "        exe = review_checks.resolve_executable(args.provider)\n",
     "        exe = shutil.which(args.provider)\n",
     _C + "test_class_a_every_executable_comes_from_the_resolver"),
    ("the review runner's taskkill is a bare name", RUN,
     '        done = subprocess.run([killer, "/T", "/F", "/PID", str(proc.pid)],\n',
     '        done = subprocess.run(["taskkill", "/T", "/F", "/PID", str(proc.pid)],\n',
     _C + "test_class_a_every_executable_comes_from_the_resolver"),
    ("a symlinked untracked verify map reads as none configured", CHECKS,
     "    except FileNotFoundError:\n        return None\n"
     "    except OSError as exc:  # NotRegularFile included",
     "    except (FileNotFoundError, NotRegularFile):\n        return None\n"
     "    except OSError as exc:  # NotRegularFile included",
     _C + "test_an_untracked_symlinked_verify_map_is_could_not_check"),
    ("read_regular is a plain open that follows links and blocks on a FIFO", CHECKS,
     "def read_regular(path, base):\n",
     "def read_regular(path, base):\n    with open(path, \"rb\") as fh:\n        return fh.read()\n",
     _C + "test_a_fifo_is_could_not_check_and_never_blocks"),
    ("the review runner reads a file with a plain open", RUN,
     "    return review_checks.read_regular(path, base).decode(\"utf-8\", errors=\"replace\").replace(\n",
     "    with open(path, encoding=\"utf-8\", errors=\"replace\") as fh:\n"
     "        return fh.read()\n"
     "    return review_checks.read_regular(path, base).decode(\"utf-8\", errors=\"replace\").replace(\n",
     _C + "test_class_b_every_file_read_goes_through_read_regular"),
    ("an explicit null is read as the default", CHECKS,
     "            if key in spec and not (isinstance(spec[key], list) and spec[key]\n",
     "            if spec.get(key) is not None and not (isinstance(spec[key], list) and spec[key]\n",
     _C + "test_an_explicit_null_is_could_not_check"),
    ("psscriptanalyzer accepts args it never passes", CHECKS,
     '             "psscriptanalyzer": _COMMON_KEYS | {"rules"}}\n',
     '             "psscriptanalyzer": _COMMON_KEYS | {"rules", "args"}}\n',
     _C + "test_psscriptanalyzer_args_are_rejected"),
    ("two runs stage their records under one name", CHECKS,
     '    path = os.path.join(scratch, f"prereview.run-{secrets.token_hex(8)}.json")\n',
     '    path = os.path.join(scratch, "prereview.run-shared.json")\n',
     _C + "test_two_runs_sharing_a_scratch_keep_their_own_records"),
    ("the record is never bound to the reserved round", RUN,
     "    _bind_record(args, number)\n",
     "",
     _R + "test_two_runs_sharing_a_scratch_do_not_swap_records"),
    # review round 7 (owner granted round 8, 2026-10-02): each fix and its neighbour
    ("a directory on the way to a file is followed through a symlink", CHECKS,
     "                step = os.open(part, _DIR_FLAGS, dir_fd=fd)\n",
     "                step = os.open(part, os.O_RDONLY | os.O_DIRECTORY, dir_fd=fd)\n",
     _C + "test_an_untracked_map_behind_a_symlinked_crew_directory_is_could_not_check"),
    ("the bundle parts are checked from their own folder only", RUN,
     '    return os.path.dirname(folder) if folder.endswith(".parts") else folder\n',
     "    return folder\n",
     _R + "test_a_symlinked_parts_directory_is_never_read_as_the_bundle"),
    ("a scratch file is checked from its own folder only", RUN,
     "    return scratch if inside else os.path.dirname(path)\n",
     "    return os.path.dirname(path)\n",
     _R + "test_a_path_inside_scratch_is_checked_from_scratch"),
    ("psscriptanalyzer's file list is one name per line", CHECKS,
     "                       (listing, json.dumps([os.path.join(tmp, f) for f in files])),\n",
     '                       (listing, "\\n".join(os.path.join(tmp, f) for f in files)),\n',
     _C + "test_real_pssa_lints_a_name_with_a_newline"),
    ("a rule name with a newline is accepted", CHECKS,
     '            elif key == "rules" and key in spec and any(_CONTROL.search(v) for v in spec[key]):\n',
     "            elif False:\n",
     _C + "test_a_rule_name_with_a_newline_is_rejected"),
    ("an unexpected exit throws away the rows it printed", CHECKS,
     '    return rows, ([_BadRow(None, odd, "exit")] if odd else [])\n',
     "    if odd:\n        raise CouldNotCheck(odd)\n    return rows, []\n",
     _C + "test_an_unexpected_exit_keeps_the_rows_it_printed"),
    ("a missing actionlint kind is read as a default", CHECKS,
     '        kind = _text(row, "kind", "actionlint")\n',
     '        kind = row.get("kind") or "?"\n',
     _C + "test_a_row_missing_a_field_is_could_not_check_never_a_default"),
    ("a missing ruff code is read as a syntax error", CHECKS,
     '        if row["code"] is None:\n',
     '        if not row.get("code"):\n',
     _C + "test_a_row_missing_a_field_is_could_not_check_never_a_default"),
    ("any psscriptanalyzer severity is accepted", CHECKS,
     "        if severity not in PSSA_SEVERITIES:\n",
     "        if False:\n",
     _C + "test_a_row_missing_a_field_is_could_not_check_never_a_default"),
    ("two tickets share a round's record name", CHECKS,
     '    return os.path.join(scratch, f"prereview-{ticket}-r{number}.json")\n',
     '    return os.path.join(scratch, f"prereview-r{number}.json")\n',
     _C + "test_two_tickets_sharing_a_scratch_keep_their_own_round_records"),
    ("a ticket that is a path names the record", CHECKS,
     "    if not isinstance(ticket, str) or not _TICKET_NAME.match(ticket):\n",
     "    if not isinstance(ticket, str) or not ticket:\n",
     _C + "test_a_ticket_that_is_not_a_plain_name_is_never_a_record_path"),
    ("a printed field keeps its newlines", CHECKS,
     "    return _CONTROL.sub(lambda m:",
     "    return str(text)\n    return _CONTROL.sub(lambda m:",
     _C + "test_a_newline_in_any_field_never_forges_a_status_line"),
    # review round 8 (owner decision 2026-10-02: fix all four, last round)
    ("any N:N: pair in a message reads as a position", CHECKS,
     '    (re.compile(r"\\b(SC\\d{4}:(?:error|warning|info|style):)\\d+:\\d+(?=:)"), r"\\1N:N"),\n',
     '    (re.compile(r"(?<![\\w.])\\d+:\\d+(?=:)"), "N:N"),\n',
     _C + "test_a_value_shaped_like_a_position_still_tells_findings_apart"),
    ("a job Windows will not make is run without one", CHECKS,
     '            raise CouldNotCheck(f"could not make a job object for {argv[0]}: {exc}") from exc\n',
     "            job = None\n",
     _C + "test_a_job_that_cannot_be_made_is_could_not_check"),
    ("a clean exit leaves the linter's job running", CHECKS,
     '    if job is not None:\n        try:\n            job.terminate()\n',
     '    if False:\n        try:\n            job.terminate()\n',
     _C + "test_a_linter_that_exits_cleanly_still_has_its_job_ended"),
    ("a job that cannot end after a clean exit escapes as OSError", CHECKS,
     '        except OSError as exc:\n            raise CouldNotCheck(f"could not end what {argv[0]} left',
     '        except KeyError as exc:\n            raise CouldNotCheck(f"could not end what {argv[0]} left',
     _C + "test_a_job_that_cannot_end_after_a_clean_exit_is_could_not_check"),
    ("the reviewer's job is not ended on a timeout", RUN,
     '                job.terminate()\n                tree_ended = True\n',
     '                tree_ended = True\n',
     _R + "test_a_provider_whose_leader_exited_has_its_job_ended_on_timeout"),
    ("review_run's stderr writer keeps newlines", RUN,
     '    sys.stderr.write(review_checks.one_line(body) + "\\n")\n',
     '    sys.stderr.write(body + "\\n")\n',
     _R + "test_a_scratch_path_with_a_newline_never_forges_a_status_line"),
    ("review_run's stdout writer keeps newlines", RUN,
     '    sys.stdout.write(review_checks.one_line(text) + "\\n")\n',
     '    sys.stdout.write(text + "\\n")\n',
     _R + "test_the_writers_keep_one_line"),
    ("the self-check note is printed as it came", RUN,
     "    note = _one(note) if note else note\n",
     "",
     _R + "test_a_self_check_note_with_a_newline_prints_on_one_line"),
    ("install-scripts' paths are left to citation counts", INSTALL_MAP,
     "paths: plugin/crew/**, scripts/**\n",
     "",
     "tests/test_review_contracts.py::test_the_install_scripts_rule_loads_for_the_install_scripts"),
    # review round 9 (owner grant 2026-10-02: final round 10)
    ("one linter's exception discards every result", CHECKS,
     "    return [_isolated(root, spec, entries, manifest) for spec in linters], True\n",
     "    return [check_one(root, spec, entries, manifest) for spec in linters], True\n",
     _C + "test_a_later_linter_that_raises_never_discards_an_earlier_new_finding"),
    ("a duplicate key in linter output keeps the last copy", CHECKS,
     "        return strict_json(text)\n",
     "        return json.loads(text)\n",
     _C + "test_duplicate_keys_in_linter_output_are_could_not_check"),
    ("a duplicate key in the verify map keeps the last copy", CHECKS,
     '        data = strict_json(raw.decode("utf-8"))\n',
     '        data = json.loads(raw.decode("utf-8"))\n',
     _C + "test_a_verify_map_with_a_duplicate_key_is_could_not_check"),
    ('a lone surrogate is printed raw', CHECKS,
     '_CONTROL = re.compile("[\\x00-\\x1f\\x7f-\\x9f\\u061c\\u200e\\u200f\\u202a-\\u202e\\u2028\\'
     'u2029"\n'
     '                      "\\u2066-\\u2069\\ud800-\\udfff]")\n',
     '_CONTROL = re.compile("[\\x00-\\x1f\\x7f-\\x9f\\u061c\\u200e\\u200f\\u202a-\\u202e\\u2028\\'
     'u2029"\n'
     '                      "\\u2066-\\u2069]")\n',
     _C + "test_a_lone_surrogate_prints_escaped"),
    ("a crash in the CLI leaves through exit 1", CHECKS,
     "    try:\n        return _main(argv)\n",
     "    return _main(argv)\n    try:\n        return _main(argv)\n",
     _C + "test_any_crash_in_the_cli_is_could_not_check"),
    ('the group is signalled after the reap (S5b)', CHECKS,
     'os.WEXITED | os.WNOWAIT | os.WNOHANG',
     'os.WEXITED | os.WNOHANG',
     _C + "test_a_reaped_linter_s_group_is_never_signalled"),
    # L-0605 (review round 10 follow-ups and ADR 0005)
    ('a clean PowerShell file prints [null] (L-0605 S1a)', CHECKS,
     'ConvertTo-Json -InputObject $rows.ToArray()',
     'ConvertTo-Json -InputObject @($null)',
     _C + "test_real_pssa_clean_files_pass"),
    ('a null PSSA row is dropped as no finding (S1b)', CHECKS,
     'raise CouldNotCheck("psscriptanalyzer output is not a list")\n        return rows\n',
     'raise CouldNotCheck("psscriptanalyzer output is not a list")\n'
     '        return [r for r in rows if r is not None]\n',
     _C + "test_pssa_output_that_is_not_a_list_of_rows_is_never_pass"),
    ('a Windows timeout with no taskkill falls to killpg (S2)', RUN,
     '                try:\n                    proc.kill()  # TerminateProcess by the handle Popen holds\n',
     '                try:\n                    os.killpg(proc.pid, signal.SIGKILL)\n',
     _L + "test_windows_timeout_without_taskkill_never_calls_killpg"),
    ('a failing taskkill escapes the timeout path (S2b)', RUN,
     '    except (OSError, subprocess.TimeoutExpired) as exc:\n        notes.append(f"taskkill failed',
     '    except KeyError as exc:\n        notes.append(f"taskkill failed',
     _L + "test_windows_timeout_when_taskkill_fails_kills_the_leader"),
    ('a taskkill exit 0 is read as the whole tree ended (S2c)', RUN,
     '                if not tree_ended:\n                    _windows_taskkill(proc, notes)\n',
     '                if not tree_ended:\n                    tree_ended = _windows_taskkill(proc, notes) is None\n',
     _L + "test_windows_timeout_with_taskkill_uses_it"),
    ('a job that cannot end is trusted (S2d)', RUN,
     '            except OSError as exc:\n                notes.append(f"job termination failed',
     '            except KeyError as exc:\n                notes.append(f"job termination failed',
     _L + "test_windows_timeout_when_the_job_cannot_end_says_escaped"),
    ('an unreadable --output escapes after the reservation (S3)', RUN,
     '                except OSError as exc:\n                    reasons.append(f"the reviewer\'s output',
     '                except KeyError as exc:\n                    reasons.append(f"the reviewer\'s output',
     _R + "test_claude_output_that_is_not_a_regular_file_is_incomplete"),
    ('an unreadable manifest at finish escapes (S3b)', RUN,
     '        manifest = json.loads(_read(args.manifest, _trusted(args.manifest, args.scratch)))\n'
     '    except (OSError, ValueError) as exc:',
     '        manifest = json.loads(_read(args.manifest, _trusted(args.manifest, args.scratch)))\n'
     '    except KeyError as exc:',
     _R + "test_an_unreadable_manifest_at_finish_is_incomplete"),
    ('a NUL in a manifest part path passes the check (S3d)', RUN,
     '            if any(isinstance(v, str) and "\\0" in v for v in (path, name)):\n',
     '            if False:\n',
     _R + "test_an_unreadable_manifest_at_finish_is_incomplete"),
    ('a part path the OS refuses escapes bundle_problems (S3e)', RUN,
     '        except (OSError, KeyError, TypeError, ValueError) as exc:\n'
     '            problems.append(f"bundle part',
     '        except (OSError, KeyError, TypeError) as exc:\n'
     '            problems.append(f"bundle part',
     _R + "test_a_part_path_the_os_refuses_is_a_bundle_problem"),
    ('a malformed manifest object is used as is (S3c)', RUN,
     '    problem = _manifest_problem(manifest)\n',
     '    problem = None\n',
     _R + "test_an_unreadable_manifest_at_finish_is_incomplete"),
    ('bidi controls print raw (S4)', CHECKS,
     '_CONTROL = re.compile("[\\x00-\\x1f\\x7f-\\x9f\\u061c\\u200e\\u200f\\u202a-\\u202e\\u2028\\'
     'u2029"\n'
     '                      "\\u2066-\\u2069\\ud800-\\udfff]")\n',
     '_CONTROL = re.compile("[\\x00-\\x1f\\x7f-\\x9f\\u2028\\u2029"\n                      "\\ud800-\\udfff]")\n',
     _C + "test_one_line_escapes_every_bidi_control"),
    ("a clean linter's leftover survives (S5a)", CHECKS,
     '    # cannot be reused.\n    try:\n        os.killpg(proc.pid, signal.SIGKILL)\n',
     '    # cannot be reused.\n    try:\n        pass\n',
     _C + "test_a_clean_linter_s_detached_leftover_is_ended"),
    ('a failed output read is ignored (S5c)', CHECKS,
     '            except OSError:\n                selector.unregister(key.fileobj)\n                raise\n',
     '            except OSError:\n                selector.unregister(key.fileobj)\n                continue\n',
     _C + "test_a_failed_output_read_is_could_not_check"),
    ('the drain waits without a deadline (S5d)', CHECKS,
     'selector.select(timeout=max(0.0, until - time.monotonic()))',
     'selector.select()',
     _C + "test_a_leftover_that_left_the_group_cannot_hang_the_check"),
    ('the reap gets its own fresh deadline (S5e)', CHECKS,
     'proc.wait(timeout=max(0.0, post - time.monotonic()))',
     'proc.wait(timeout=_REAP_SECONDS)',
     _C + "test_the_post_kill_drain_and_reap_share_one_deadline"),
    ('a refused group kill reads as nothing left (S5f)', CHECKS,
     '    except ProcessLookupError:\n        refused = None  # the group held only the zombie',
     '    except OSError:\n        refused = None  # the group held only the zombie',
     _C + "test_a_leftover_that_cannot_be_signalled_is_could_not_check"),
    ('a selector error skips the cleanup (S5g)', CHECKS,
     '        try:\n'
     '            selector = selectors.DefaultSelector()\n'
     '            selector.register(proc.stdout, selectors.EVENT_READ, "out")\n'
     '            selector.register(proc.stderr, selectors.EVENT_READ, "err")\n'
     '        except (OSError, ValueError) as exc:',
     '        selector = selectors.DefaultSelector()\n'
     '        selector.register(proc.stdout, selectors.EVENT_READ, "out")\n'
     '        selector.register(proc.stderr, selectors.EVENT_READ, "err")\n'
     '        try:\n'
     '            pass\n'
     '        except (OSError, ValueError) as exc:',
     _C + "test_a_selector_error_still_ends_and_reaps_the_linter"),
)
