"""`crew_instructions.py rules` says when it generates from a code map whose
anchor needs re-check (T-0501, aws-ops follow-up report item 14).

The report: `rules` wrote 8 `.claude/rules/*.md` from `.crew/codemap/` while
the session-start hook was reporting 4 of those subsystems' anchors as needing
re-check, and neither `rules` nor `rules --check` gave any warning; migrate's
step list did not mention it either.

Three invariants these tests hold:

- the same classifier as session-start: the advisory lines come from
  `crew_context.anchor_state`, the function behind SessionStart's
  "Anchors to re-check" line, so the two surfaces name the same notes;
- the generated bytes never change: the anchor state is printed, never
  rendered into the rule, so `rule_digest` stays a pure function of the note
  and `rules --check` keeps its fixpoint;
- the exit codes never change: an anchor line is advisory in both modes, and
  1 still means drift and nothing else.

Sabotage (`sabotage_context.py`'s CONTEXT_MUTATIONS, and one by hand):

- `WARN_STATES` narrowed to `("unresolvable",)` reds
  test_rules_names_a_note_whose_cited_path_changed_since_its_anchor;
- the no-HEAD branch returning `[], 0` reds
  test_no_git_head_is_could_not_tell_not_silence;
- `scripts/check_instructions.py`'s prefix filter dropped reds
  `scripts/_test/instruction-budgets.py`'s edited-behind case.

    python3 -m pytest plugin/crew/tests/test_rules_anchor_advice.py -q
"""
import importlib.util
import os
import re
import shutil

import pytest

import context  # noqa: F401  pylint: disable=unused-import
import crew_context
import crew_instructions as ci
from context_fixtures import git, make_repo

CREW = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO = os.path.dirname(os.path.dirname(CREW))
MIGRATE = os.path.join(CREW, "commands", "migrate.md")
ONBOARD = os.path.join(CREW, "commands", "onboard.md")
CHECKER_PATH = os.path.join(REPO, "scripts", "check_instructions.py")
PREFIXES = ("anchor behind:", "anchor unresolvable:", "anchors: could not tell")
DRIFT_PREFIXES = ("stale:", "missing:", "orphan:", "hand-written")


@pytest.fixture(autouse=True)
def _no_git_above(tmp_path, monkeypatch):
    """git must never find a repository above the fixture once its own
    `.git` is gone."""
    monkeypatch.setenv("GIT_CEILING_DIRECTORIES", str(tmp_path))


def _read(path):
    with open(path, encoding="utf-8") as handle:
        return handle.read()


def _run(argv, capsys):
    code = ci.main(argv)
    return code, capsys.readouterr().out.splitlines()


def _behind(root, name="alpha"):
    core = root / "src" / name / "core.py"
    core.write_text(core.read_text(encoding="utf-8") + "y = 2\n", encoding="utf-8")
    git(root, "add", "-A")
    git(root, "commit", "-q", "-m", "move " + name)


def _head(root):
    return crew_context.git_out(str(root), "rev-parse", "--short=8", "HEAD")


def _note(root, name):
    return root / ".crew" / "codemap" / f"{name}.md"


def _anchor_of(root, name):
    match = re.search(r"^anchor: repo@(\S+)$", _note(root, name).read_text(encoding="utf-8"),
                      re.MULTILINE)
    return match.group(1) if match else ""


def _set_anchor(root, name, sha):
    """Rewrite the note's anchor line to `sha`, or delete it when `sha` is None."""
    path = _note(root, name)
    lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
    out = []
    for line in lines:
        if line.startswith("anchor: "):
            if sha is None:
                continue
            line = f"anchor: repo@{sha}\n"
        out.append(line)
    path.write_text("".join(out), encoding="utf-8")


def _behind_line(root, name):
    sha = _anchor_of(root, name)
    return (f"anchor behind: {name} - anchor {sha}; re-check with git diff --name-only "
            f"{sha}..HEAD -- <cited paths>, or refresh with /crew:onboard --refresh {name}")


def _advisory(lines):
    return [line for line in lines if line.startswith("anchor")]


def _no_advisory_reads_as_drift(lines):
    for line in _advisory(lines):
        assert line.startswith(PREFIXES), line
        assert not line.startswith(DRIFT_PREFIXES), line


def test_rules_says_nothing_about_anchors_when_every_note_is_current(tmp_path, capsys):
    root = make_repo(tmp_path)

    code, lines = _run(["rules", "--root", str(root)], capsys)

    assert code == 0
    assert lines == ["wrote " + os.path.join(".claude", "rules", "alpha.md"),
                     "wrote " + os.path.join(".claude", "rules", "beta.md")]


def test_rules_names_a_note_whose_cited_path_changed_since_its_anchor(tmp_path, capsys):
    root = make_repo(tmp_path)
    _behind(root)

    code, lines = _run(["rules", "--root", str(root)], capsys)

    assert code == 0
    assert _advisory(lines) == [_behind_line(root, "alpha")]
    _no_advisory_reads_as_drift(lines)


def test_rules_check_prints_the_same_anchor_lines_and_still_exits_0(tmp_path, capsys):
    root = make_repo(tmp_path)
    _run(["rules", "--root", str(root)], capsys)
    _behind(root)

    code, lines = _run(["rules", "--root", str(root), "--check"], capsys)

    assert code == 0
    assert lines == [_behind_line(root, "alpha"),
                     "rules: up to date - rules match the code map; "
                     "1 code map(s) need re-check (anchor lines above)"]


def test_rules_prints_drift_before_anchor_lines_and_exits_1_on_drift_only(tmp_path, capsys):
    root = make_repo(tmp_path)
    _run(["rules", "--root", str(root)], capsys)
    _behind(root)
    beta = _note(root, "beta")
    beta.write_text(beta.read_text(encoding="utf-8") + "- a new landmine.\n", encoding="utf-8")

    code, lines = _run(["rules", "--root", str(root), "--check"], capsys)

    assert code == 1
    assert lines == ["stale: " + os.path.join(".claude", "rules", "beta.md"),
                     _behind_line(root, "alpha")]


def test_the_generated_rule_never_carries_the_anchor_state(tmp_path, capsys):
    root = make_repo(tmp_path)
    _run(["rules", "--root", str(root)], capsys)
    rule = root / ".claude" / "rules" / "alpha.md"
    before = rule.read_bytes()
    _behind(root)

    problems, written = ci.rules(str(root))

    assert (problems, written) == ([], [])
    assert rule.read_bytes() == before
    assert "behind" not in rule.read_text(encoding="utf-8").replace("if it is behind HEAD", "")


def test_an_unresolvable_anchor_is_its_own_line(tmp_path, capsys):
    root = make_repo(tmp_path)
    _set_anchor(root, "beta", "d" * 40)

    code, lines = _run(["rules", "--root", str(root)], capsys)

    assert code == 0
    assert _advisory(lines) == [f"anchor unresolvable: beta - anchor {'d' * 40} names no "
                                "commit here; refresh with /crew:onboard --refresh beta"]
    _no_advisory_reads_as_drift(lines)


def test_a_note_with_no_anchor_line_is_unresolvable_not_silent(tmp_path, capsys):
    root = make_repo(tmp_path)
    _set_anchor(root, "beta", None)

    code, lines = _run(["rules", "--root", str(root)], capsys)

    assert code == 0
    assert _advisory(lines) == ["anchor unresolvable: beta - no anchor recorded; "
                                "refresh with /crew:onboard --refresh beta"]


def test_no_git_head_is_could_not_tell_not_silence(tmp_path, capsys):
    root = make_repo(tmp_path)
    shutil.rmtree(root / ".git")

    code, lines = _run(["rules", "--root", str(root)], capsys)
    check_code, check_lines = _run(["rules", "--root", str(root), "--check"], capsys)

    assert code == 0
    assert (root / ".claude" / "rules" / "alpha.md").is_file()
    advisory = _advisory(lines)
    assert len(advisory) == 1
    assert advisory[0].startswith("anchors: could not tell - no git HEAD under ")
    assert advisory[0].endswith("; 2 rule(s) come from code maps whose anchors were not checked")
    assert check_code == 0
    assert check_lines[-1] == ("rules: up to date - rules match the code map; "
                               "anchors not checked (no git HEAD)")


def test_rules_and_session_start_classify_the_same_notes(tmp_path, capsys):
    files = {name: ([f"src/{name}/core.py", f"src/{name}/util.py", f"src/{name}/io.py"],
                    [f"{name.upper()}-LANDMINE a trap"])
             for name in ("alpha", "beta", "gamma")}
    root = make_repo(tmp_path, subsystems=files)
    _behind(root, "alpha")
    _set_anchor(root, "beta", "d" * 40)

    _, lines = _run(["rules", "--root", str(root)], capsys)

    named = [line.split(":", 1)[1].split(" - ", 1)[0].strip() for line in _advisory(lines)]
    head = _head(root)
    rendered = {os.path.basename(path)[:-3] for path in ci.expected_rules(str(root))}
    session_start = [s["name"] for s in crew_context.subsystems(str(root))
                     if s["name"] in rendered
                     and crew_context.anchor_state(str(root), s, head) in ("behind", "unresolvable")]
    assert named == session_start == ["alpha", "beta"]


def test_a_note_with_no_rule_is_not_reported(tmp_path, capsys):
    root = make_repo(tmp_path)
    _note(root, "delta").write_text(
        "anchor: repo@" + "d" * 40 + "\n# delta\n\n## Landmines\n\n- no path cited here.\n",
        encoding="utf-8")

    _, lines = _run(["rules", "--root", str(root)], capsys)

    assert not any("delta" in line for line in _advisory(lines))
    delta = [s for s in crew_context.subsystems(str(root)) if s["name"] == "delta"][0]
    assert crew_context.anchor_state(str(root), delta, _head(root)) == "unresolvable"


@pytest.mark.parametrize("what", ["agents", "codex"])
def test_agents_and_codex_print_no_anchor_lines(tmp_path, capsys, what):
    root = make_repo(tmp_path)
    _behind(root)

    _, lines = _run([what, "--root", str(root)], capsys)

    assert not _advisory(lines)


def test_migrate_and_onboard_explain_the_anchor_lines():
    migrate = _read(MIGRATE)
    preview, apply = migrate.split("## Step 2", 1)
    onboard = _read(ONBOARD)
    step6 = onboard.split("## 6. Generate the path-scoped rules", 1)[1]
    step6 = step6.split("## Then make the knowledge executable", 1)[0]

    assert "anchor behind:" in preview
    assert "anchor behind:" in apply
    assert "anchor behind:" in step6
    assert "/crew:onboard --refresh" in migrate
    assert "--refresh" in step6


def test_check_instructions_skips_exactly_the_prefixes_rules_prints():
    spec = importlib.util.spec_from_file_location("check_instructions_for_parity", CHECKER_PATH)
    checker = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(checker)

    assert checker.ANCHOR_ADVISORY_PREFIXES == ci.ANCHOR_ADVISORY_PREFIXES == PREFIXES
