"""Embed each crew diagram in the README nearest its anchors, and check the
embeds still match their sources. T-0035.

    python3 crew_diagrams.py embed --root .     write the sections (exit 1: refused, nothing written)
    python3 crew_diagrams.py check --root .     exit 0 current, 1 drift/problem/unknown

The `.mmd` under `docs.diagramsDir` (default `docs/diagrams`, read flat, as
`diagram_doc.py` and `render.sh` read it) stays the one source. Each README a
diagram reaches gets ONE generated section between

    <!-- crew-diagrams:begin -->
    <!-- crew-diagrams:end -->

holding a `## Diagrams` heading and, per diagram, a `###` title, its
`%% Purpose:` text, the fenced ```mermaid block (the source minus its `%%`
lines -- the same title, purpose and body `diagram_doc.py` puts on the
diagrams page) and a link to the source. GitHub renders the block for a
human; an agent reads the same text. On a repo whose `origin` is on
bitbucket.org, which renders no mermaid fence, the block becomes the
rendered `<diagramsDir>/out/<name>.svg` as an image with the source in a
`<details>`, and a warning names an SVG path git ignores (it would never
reach the remote).

Which README: `%% Embed: none` (no README), `%% Embed: <path>[, <path>]`
(each must be an existing file named README.md), else, for each
`%% Anchors:` path, the nearest README.md at or above it, below the repo
root. Never the repo-root README, never a SKILL.md (only README.md files
qualify), never one inside the diagrams dir, never one another generator
owns (a `<!-- generated by` line in its first two lines: `docs/qa/README.md`
from qa_doc.py would overwrite the section) -- those are `skipped`. No README
is created. A diagram reaching none is on the diagrams page only.

`check` states, never collapsing could-not-tell into current:
  drift    a README's section differs from what `embed` would write now (a
           hand edit, a source changed and not re-embedded, a diagram that no
           longer targets it). `embed` settles it.
  problem  markers that are not exactly one begin before one end, or an
           `%% Embed:` naming no README. Needs judgement; `embed` refuses
           and writes nothing.
  unknown  the diagrams dir, the crew config, a source or a README could not
           be read.
  pending  a README a diagram targets that has no section yet. Not a
           failure: adopting is one `embed` run, and failing it would refuse
           `/crew:done` in every repo with diagrams the day this shipped.

Writes compute the whole new text first, then go through a temp file and
`os.replace` (root CLAUDE.md: never truncate before the payload exists). A
README's newline style (CRLF or LF) is kept. Standard library only.
"""
import argparse
import json
import os
import re
import subprocess
import sys

import crew_common
from crew_common import read_text
from crew_freshness import (
    DIAGRAMS_DIR_DEFAULT,
    _DIAGRAM_EXTS,
    _diagrams_dir,
    contained_path,
)

BEGIN = "<!-- crew-diagrams:begin -->"
END = "<!-- crew-diagrams:end -->"
NOTE = ("<!-- generated by crew_diagrams.py embed from {dir}: edit the .mmd sources there, "
        "then run it again; text between these markers is replaced -->")
README = "README.md"
EMBED_COMMAND = "python3 ${CLAUDE_PLUGIN_ROOT}/hooks/scripts/crew_diagrams.py embed --root ."

FRESH = "fresh"
STALE = "stale"
UNKNOWN = "unknown"

# Read exactly as diagram_doc.read_source reads them (a test pins the two).
_PROVENANCE = re.compile(r"^%%\s*(anchor:|Anchors:|Generated from|Re-drawn|Note\s)", re.I)
_EMBED = re.compile(r"^%%\s*Embed:\s*(.*)$", re.I)
_OTHER_GENERATOR = re.compile(r"<!--\s*generated by\b", re.I)


class MarkerError(ValueError):
    """Markers that are not exactly one begin followed by one end."""


def read_source(path):
    """{"file", "name", "title", "purpose", "anchors", "embed", "body"} of one
    source. Raises OSError / UnicodeDecodeError when it cannot be read."""
    with open(path, encoding="utf-8") as fh:
        lines = fh.read().splitlines()
    comments = [ln.strip() for ln in lines if ln.strip().startswith("%%")]
    body = "\n".join(ln for ln in lines if not ln.strip().startswith("%%")).strip()
    anchors, embed = [], None
    for ln in comments:
        m = re.match(r"^%%\s*Anchors:\s*(.*)", ln)
        if m:
            anchors = [a.strip().strip("`") for a in m.group(1).split(",") if a.strip()]
        m = _EMBED.match(ln)
        if m:
            embed = [p.strip().strip("`") for p in m.group(1).split(",") if p.strip()]
    purpose = [re.sub(r"^%%\s*Purpose:\s*", "", ln) for ln in comments
               if re.match(r"^%%\s*Purpose:", ln)]
    if not purpose:
        purpose = [ln[2:].strip() for ln in comments
                   if not _PROVENANCE.match(ln) and not _EMBED.match(ln) and ln[2:].strip()][:3]
    name = os.path.splitext(os.path.basename(path))[0]
    return {"file": os.path.basename(path), "name": name,
            "title": name.replace("-", " ").capitalize(), "purpose": purpose,
            "anchors": anchors, "embed": embed, "body": body}


def _read_config(top):
    """(config, None) or (None, reason) for a config that exists and does not
    parse -- its diagrams dir cannot then be told (crew_refresh_check's rule)."""
    for name in ("crew.json", "config.json"):
        path = crew_common.repo_config_file(top, name)
        if not os.path.lexists(path):
            continue
        text = read_text(path)
        if text is None:
            return None, f".crew/{name} could not be read"
        try:
            data = json.loads(text)
        except ValueError:
            return None, f".crew/{name} is not valid JSON"
        if not isinstance(data, dict):
            return None, f".crew/{name} is not a JSON object"
        return data, None
    return {}, None


def _rel(top, path):
    return os.path.relpath(path, top).replace("\\", "/")


def _inside(top, rel):
    """`rel` as a clean repo-relative path, or None when it leaves the repo."""
    if not rel or os.path.isabs(rel) or rel.startswith(("/", "\\")):
        return None
    norm = os.path.normpath(rel).replace("\\", "/")
    if norm == ".." or norm.startswith("../"):
        return None
    full = os.path.realpath(os.path.join(top, norm))
    try:
        if os.path.commonpath([top, full]) != top:
            return None
    except ValueError:
        return None
    return norm


def _owned_by_another_generator(text):
    return any(_OTHER_GENERATOR.search(ln) and "crew_diagrams.py" not in ln
               for ln in text.splitlines()[:2])


def region(text):
    """(start, end) offsets of the one section -- `end` past END and its
    newline -- or None when there are no markers. MarkerError otherwise."""
    begins = [m.start() for m in re.finditer(re.escape(BEGIN), text)]
    ends = [m.start() for m in re.finditer(re.escape(END), text)]
    if not begins and not ends:
        return None
    if len(begins) != 1 or len(ends) != 1 or ends[0] < begins[0]:
        raise MarkerError(f"{len(begins)} begin and {len(ends)} end marker(s)"
                          + (", end before begin" if begins and ends and ends[0] < begins[0]
                             else "") + "; expected exactly one begin, then one end")
    stop = ends[0] + len(END)
    for nl in ("\r\n", "\n"):
        if text.startswith(nl, stop):
            stop += len(nl)
            break
    return begins[0], stop


def outside_markers(text):
    """The README with its generated section removed and trailing whitespace
    stripped, or None when its markers are malformed. Two copies whose
    outside text is equal differ only inside the section (the shape a future
    completion-audit allowance compares)."""
    try:
        span = region(text)
    except MarkerError:
        return None
    if span is not None:
        text = text[:span[0]] + text[span[1]:]
    return text.rstrip()


def _origin_is_bitbucket(top):
    """True when `origin` is on bitbucket.org. No git, no repo or no origin is
    False: that only picks the fenced form, which every other host renders."""
    url = crew_common.git_out(top, "remote", "get-url", "origin")
    return bool(url) and re.search(r"(^|[@/.])bitbucket\.org([:/]|$)", url.strip()) is not None


def _git_ignored(top, rel):
    try:
        done = subprocess.run(["git", "check-ignore", "-q", "--no-index", rel], cwd=top,
                              capture_output=True, stdin=subprocess.DEVNULL, timeout=30,
                              check=False)
    except (OSError, subprocess.SubprocessError):
        return None
    return {0: True, 1: False}.get(done.returncode)


def _block(diagram, readme_dir, diagrams_rel, bitbucket):
    link = os.path.relpath(os.path.join(diagrams_rel, diagram["file"]),
                           readme_dir or ".").replace("\\", "/")
    fence = ["```mermaid", diagram["body"], "```"]
    parts = [f"### {diagram['title']}", "",
             " ".join(diagram["purpose"]) or "_No `%% Purpose:` line in the source yet._", ""]
    if bitbucket:
        svg = os.path.relpath(os.path.join(diagrams_rel, "out", diagram["name"] + ".svg"),
                              readme_dir or ".").replace("\\", "/")
        parts += [f"![{diagram['title']}]({svg})", "", "<details><summary>Mermaid source</summary>",
                  "", *fence, "", "</details>"]
    else:
        parts += fence
    parts += ["", f"Source: [`{diagrams_rel}/{diagram['file']}`]({link})"]
    return "\n".join(parts)


def _section(diagrams, readme, diagrams_rel, bitbucket):
    readme_dir = os.path.dirname(readme)
    blocks = {d["name"]: _block(d, readme_dir, diagrams_rel, bitbucket) for d in diagrams}
    text = "\n".join([BEGIN, NOTE.format(dir=diagrams_rel), "## Diagrams", "",
                      "\n\n".join(blocks[d["name"]] for d in diagrams), END]) + "\n"
    return text, blocks


def _nearest_readme(top, anchor, diagrams_rel):
    start = anchor if os.path.isdir(os.path.join(top, anchor)) else os.path.dirname(anchor)
    d = start
    while d not in ("", "."):
        if os.path.isfile(os.path.join(top, d, README)):
            if d == diagrams_rel or d.startswith(diagrams_rel + "/"):
                return None
            return f"{d}/{README}"
        d = os.path.dirname(d)
    return None


def plan(top):
    """Everything `embed` would write and `check` judges, writing nothing."""
    top = os.path.realpath(top)
    out = {"diagrams_dir": None, "targets": {}, "writes": {}, "drift": [], "pending": [],
           "problems": [], "unknown": [], "skipped": [], "warnings": []}
    cfg, why = _read_config(top)
    if cfg is None:
        out["unknown"].append(f"config unreadable: {why}, so the diagrams dir cannot be told")
        return out
    dirpath = contained_path(top, _diagrams_dir(cfg), DIAGRAMS_DIR_DEFAULT)
    diagrams_rel = _rel(top, dirpath)
    out["diagrams_dir"] = diagrams_rel
    try:
        names = sorted(os.listdir(dirpath))
    except FileNotFoundError:
        names = []
    except OSError as exc:
        out["unknown"].append(f"{diagrams_rel} could not be listed "
                              f"({exc.strerror or type(exc).__name__})")
        return out
    diagrams = []
    for name in names:
        if os.path.splitext(name)[1].lower() not in _DIAGRAM_EXTS:
            continue
        path = os.path.join(dirpath, name)
        if not os.path.isfile(path):
            continue
        try:
            diagrams.append(read_source(path))
        except (OSError, UnicodeDecodeError) as exc:
            out["unknown"].append(f"{diagrams_rel}/{name} could not be read ({exc})")
    if out["unknown"]:
        return out

    targets = {}
    for d in diagrams:
        if d["embed"] is not None:
            if [p.lower() for p in d["embed"]] == ["none"]:
                continue
            chosen = []
            for raw in d["embed"]:
                rel = _inside(top, raw)
                if (rel is None or os.path.basename(rel) != README
                        or not os.path.isfile(os.path.join(top, rel))):
                    out["problems"].append(f"{diagrams_rel}/{d['file']}: `%% Embed: {raw}` names "
                                           "no existing README.md in this repo")
                    continue
                chosen.append(rel)
        else:
            chosen = [r for r in (_nearest_readme(top, rel, diagrams_rel)
                                  for rel in filter(None, (_inside(top, a) for a in d["anchors"])))
                      if r]
        for readme in dict.fromkeys(chosen):
            targets.setdefault(readme, []).append(d)

    # Every README holding markers is judged, targeted or not: a section no
    # diagram targets any more is drift, and embed removes it.
    marked = _marked_readmes(top, targets)
    bitbucket = _origin_is_bitbucket(top)
    for readme in sorted(set(targets) | marked):
        path = os.path.join(top, readme)
        try:
            with open(path, encoding="utf-8", newline="") as fh:
                text = fh.read()
        except (OSError, UnicodeDecodeError) as exc:
            out["unknown"].append(f"{readme} could not be read ({exc})")
            continue
        if readme in targets and _owned_by_another_generator(text):
            out["skipped"].append(f"{readme}: another generator owns it "
                                  f"({', '.join(d['name'] for d in targets.pop(readme))})")
            continue
        try:
            span = region(text)
        except MarkerError as exc:
            out["problems"].append(f"{readme}: {exc}")
            continue
        wanted = targets.get(readme, [])
        if wanted:
            out["targets"][readme] = [d["name"] for d in wanted]
        nl = "\r\n" if "\r\n" in text else "\n"
        if wanted:
            section, blocks = _section(wanted, readme, diagrams_rel, bitbucket)
            section = section.replace("\n", nl)
        else:
            section, blocks = "", {}
        if span is None:
            if not wanted:
                continue
            out["pending"].append({"readme": readme, "diagrams": [d["name"] for d in wanted]})
            head = text if not text or text.endswith(("\n", "\r\n")) else text + nl
            new = head + nl + section
        else:
            current = text[span[0]:span[1]]
            if current == section:
                continue
            before, after = text[:span[0]], text[span[1]:]
            # Removing the last section takes the blank line the append added.
            new = before + section + after if section else before.rstrip("\r\n") + nl + after
            plain = current.replace("\r\n", "\n")
            stale = [n for n, b in blocks.items() if b not in plain]
            reason = ("a section no diagram targets any more" if not wanted else
                      "differs from its sources" if stale else
                      "holds text no diagram generates (a hand edit, or a removed diagram)")
            out["drift"].append({"readme": readme, "diagrams": stale, "reason": reason})
        out["writes"][readme] = new
        if bitbucket:
            for d in wanted:
                svg = f"{diagrams_rel}/out/{d['name']}.svg"
                if _git_ignored(top, svg):
                    out["warnings"].append(f"{svg} is ignored by git, so the image {readme} "
                                           "links to never reaches Bitbucket")
    return out


def _marked_readmes(top, targets):
    """README.md files below the root holding a begin or end marker: the
    files git lists (tracked and untracked, not ignored) in a repository,
    otherwise a walk that skips dot-dirs and node_modules. Either way an
    orphaned section -- one no diagram targets any more -- is found."""
    found = set(targets)
    listing = crew_common.git_out(top, "ls-files", "-z", "--cached", "--others",
                                  "--exclude-standard", "--", f"*{README}", README)
    if listing is not None:
        rels = [r for r in listing.split("\0") if r]
    else:
        rels = []
        for here, dirs, files in os.walk(top):
            dirs[:] = sorted(d for d in dirs if not d.startswith(".") and d != "node_modules")
            if README in files:
                rels.append(_rel(top, os.path.join(here, README)))
    for rel in rels:
        if os.path.basename(rel) != README or rel == README:
            continue
        text = read_text(os.path.join(top, rel))
        if text is not None and ("crew-diagrams:begin" in text or "crew-diagrams:end" in text):
            found.add(rel)
    return found


def check(top):
    """`plan` plus an overall `status`: unknown, else stale on any drift or
    problem, else fresh. Pending READMEs do not fail it."""
    out = plan(top)
    out["status"] = (UNKNOWN if out["unknown"] else
                     STALE if out["drift"] or out["problems"] else FRESH)
    return out


def _write(path, text):
    tmp = path + ".crew-diagrams.tmp"
    with open(tmp, "w", encoding="utf-8", newline="") as fh:
        fh.write(text)
    os.replace(tmp, path)


def _report(result, stream):
    for item in result["unknown"]:
        stream.write(f"UNKNOWN {item}\n")
    for item in result["problems"]:
        stream.write(f"PROBLEM {item}\n")
    for item in result["drift"]:
        named = f" ({', '.join(item['diagrams'])})" if item["diagrams"] else ""
        stream.write(f"DRIFT {item['readme']}: {item['reason']}{named}\n")


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("action", choices=("embed", "check"))
    parser.add_argument("--root", default=".")
    args = parser.parse_args(argv)
    top = crew_common.git_out(args.root, "rev-parse", "--show-toplevel")
    top = top.strip() if top else os.path.abspath(args.root)
    result = check(top)
    for item in result["warnings"]:
        sys.stderr.write(f"warning: {item}\n")
    for item in result["skipped"]:
        sys.stdout.write(f"skipped {item}\n")
    if args.action == "check":
        _report(result, sys.stdout)
        for item in result["pending"]:
            sys.stdout.write(f"pending {item['readme']}: not embedded yet "
                             f"({', '.join(item['diagrams'])}); run embed\n")
        sys.stdout.write(f"crew-diagrams check: {result['status']}\n")
        return 0 if result["status"] == FRESH else 1
    if result["unknown"] or result["problems"]:
        _report({**result, "drift": []}, sys.stderr)
        sys.stderr.write("crew-diagrams embed: refused, nothing written\n")
        return 1
    for readme, text in sorted(result["writes"].items()):
        _write(os.path.join(os.path.realpath(top), readme), text)
        sys.stdout.write(f"wrote {readme}\n")
    if not result["writes"]:
        sys.stdout.write("crew-diagrams embed: every section already current\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
