"""Write the companion page for a repo's diagrams: every diagram embedded in
Markdown beside what it shows, where it came from, and whether it is readable.

  docs/diagrams/README.md    one section per .mmd: purpose, the diagram as a
                             fenced mermaid block, its anchors, its check
  docs/diagrams/index.html   the same page as HTML (Mermaid from a CDN; offline
                             the source text shows instead)

A box stays short; its detail lives in the source as `%% Note <node id>: text`
lines, which the page prints as a "Box details" table under the diagram, so a
readable drawing loses nothing.

The purpose comes from the source's `%% Purpose:` lines (any `%%` comment that
is not provenance, when there are none). The readability verdict comes from
diagram_check.py on `out/<name>.svg` when render.sh has produced it, and is
"not rendered" otherwise -- never a guessed PASS.

DRY RUN BY DEFAULT. `--write` writes both files and never overwrites one that
lacks the GENERATED marker: a hand-written README.md is refused (exit 1).

Usage: diagram_doc.py [--dir docs/diagrams] [--write]
Exit: 0 printed or written; 1 a file was refused; 2 usage.
"""
import argparse
import html
import os
import re
import sys

import diagram_check

GENERATED = "generated by crew diagram_doc.py"
MERMAID_CDN = "https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js"
_PROVENANCE = re.compile(r"^%%\s*(anchor:|Anchors:|Generated from|Re-drawn|Note\s)", re.I)
_NOTE = re.compile(r"^%%\s*Note\s+([\w>-]+)\s*:\s*(.*)$")


def plain(text):
    """A Mermaid label as plain text: formatting tags dropped (a line break becomes a space),
    Mermaid's #quot; / #35; entities and HTML entities decoded."""
    text = re.sub(r"<br\s*/?>", " ", text, flags=re.I)
    # Only the formatting tags a Mermaid label uses. Anything else that looks
    # like a tag (`<repo>`, `</svg>`) is text the note is about, and is kept.
    text = re.sub(r"</?(?:b|i|u|em|strong|code|span|small|sub|sup|p|div)(?:\s[^>]*)?>", "", text, flags=re.I)
    text = re.sub(r"#(quot|amp|lt|gt|\d+);", lambda m: html.unescape(
        f"&#{m.group(1)};" if m.group(1).isdigit() else f"&{m.group(1)};"), text)
    return re.sub(r"\s+", " ", html.unescape(text)).strip().strip('"')


def read_notes(path):
    """[(node id, text)] from `%% Note <id>: text` lines, in source order; a
    note continued on the next `%%` line with no new `Note` is joined to it."""
    notes = []
    with open(path, encoding="utf-8") as fh:
        for raw in fh:
            line = raw.strip()
            m = _NOTE.match(line)
            if m:
                notes.append([m.group(1), m.group(2).strip()])
            elif notes and line.startswith("%%") and line[2:].startswith("   "):
                notes[-1][1] += " " + line[2:].strip()
    return [(n, plain(t)) for n, t in notes]


def read_source(path):
    """(title, purpose lines, anchors, mermaid body) of one .mmd file."""
    with open(path, encoding="utf-8") as fh:
        lines = fh.read().splitlines()
    comments = [ln for ln in lines if ln.strip().startswith("%%")]
    body = "\n".join(ln for ln in lines if not ln.strip().startswith("%%")).strip()
    anchors = []
    for ln in comments:
        m = re.match(r"^%%\s*Anchors:\s*(.*)", ln.strip())
        if m:
            anchors = [a.strip().strip("`") for a in m.group(1).split(",") if a.strip()]
    purpose = [re.sub(r"^%%\s*Purpose:\s*", "", ln.strip()) for ln in comments
               if re.match(r"^%%\s*Purpose:", ln.strip())]
    if not purpose:
        purpose = [ln.strip()[2:].strip() for ln in comments
                   if not _PROVENANCE.match(ln.strip()) and ln.strip()[2:].strip()][:3]
    name = os.path.splitext(os.path.basename(path))[0]
    return name.replace("-", " ").capitalize(), purpose, anchors, body


def verdict(directory, name):
    svg = os.path.join(directory, "out", name + ".svg")
    if not os.path.isfile(svg):
        return "not rendered (run render.sh, then this again)"
    with open(svg, encoding="utf-8") as fh:
        r = diagram_check.measure(fh.read())
    if r["status"] == diagram_check.PASS:
        return f"PASS: {r['nodes']} nodes, no crossings, nothing drawn through a node"
    if r["status"] == diagram_check.FAIL:
        parts = [f"{len(r[k])} {label}" for k, label in
                 (("crossings", "crossing(s)"), ("through", "edge(s) through a node"),
                  ("overlaps", "label overlap(s)")) if r[k]]
        if r.get("why"):
            parts.append(r["why"])
        return "FAIL: " + "; ".join(parts)
    return f"{r['status']}: {r.get('why', '')}"


def collect(directory):
    out = []
    for name in sorted(os.listdir(directory)):
        if name.endswith((".mmd", ".mermaid")):
            title, purpose, anchors, body = read_source(os.path.join(directory, name))
            out.append({"file": name, "title": title, "purpose": purpose, "anchors": anchors,
                        "notes": read_notes(os.path.join(directory, name)),
                        "body": body, "check": verdict(directory, os.path.splitext(name)[0])})
    return out


def render_markdown(items):
    parts = [f"<!-- {GENERATED}; edit the .mmd sources, not this file -->", "# Diagrams", "",
             "Every diagram in this directory, with what it shows and whether it is readable. The "
             "`.mmd` files are the source; `out/` holds renders. Regenerate with "
             "`diagram_doc.py --write` after `render.sh`.", "",
             "| Diagram | Readability |", "|---|---|"]
    parts += [f"| [{i['title']}](#{_anchor(i['title'])}) | {i['check'].split(':')[0]} |" for i in items]
    for i in items:
        parts += ["", f"## {i['title']}", ""]
        parts += [" ".join(i["purpose"]) or "_No `%% Purpose:` line in the source yet._", ""]
        parts += ["```mermaid", i["body"], "```", ""]
        if i["notes"]:
            parts += ["| Box | Details |", "|---|---|"]
            parts += [f"| `{n}` | {t.replace('|', '/')} |" for n, t in i["notes"]]
            parts.append("")
        parts.append(f"- **Source:** `{i['file']}`")
        if i["anchors"]:
            parts.append("- **Drawn from:** " + ", ".join(f"`{a}`" for a in i["anchors"][:8]))
        parts.append(f"- **Readability:** {i['check']}")
    return "\n".join(parts) + "\n"


def _anchor(title):
    return re.sub(r"[^a-z0-9 -]", "", title.lower()).replace(" ", "-")


def render_html(items):
    toc = "".join(f'<tr><td><a href="#{_anchor(i["title"])}">{html.escape(i["title"])}</a></td>'
                  f'<td>{html.escape(i["check"].split(":")[0])}</td></tr>' for i in items)
    sections = []
    for i in items:
        anchors = ", ".join(f"<code>{html.escape(a)}</code>" for a in i["anchors"][:8])
        sections.append(
            f'<section id="{_anchor(i["title"])}"><h2>{html.escape(i["title"])}</h2>'
            f'<p>{html.escape(" ".join(i["purpose"])) or "<em>No purpose line in the source yet.</em>"}</p>'
            f'<pre class="mermaid">{html.escape(i["body"])}</pre>'
            + (('<table><thead><tr><th>Box</th><th>Details</th></tr></thead><tbody>'
                + "".join(f"<tr><td><code>{html.escape(n)}</code></td><td>{html.escape(t)}</td></tr>"
                          for n, t in i["notes"]) + "</tbody></table>") if i["notes"] else "")
            + f'<ul><li><strong>Source:</strong> <code>{html.escape(i["file"])}</code></li>'
            + (f"<li><strong>Drawn from:</strong> {anchors}</li>" if anchors else "")
            + f'<li><strong>Readability:</strong> {html.escape(i["check"])}</li></ul></section>')
    return f"""<!doctype html>
<!-- {GENERATED}; edit the .mmd sources, not this file -->
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Diagrams</title>
<style>
:root {{ --bg:#ffffff; --fg:#1d1d1f; --muted:#5f6368; --line:#d9dce1; --head:#f3f4f6; }}
@media (prefers-color-scheme: dark) {{
  :root {{ --bg:#16181c; --fg:#e8eaed; --muted:#9aa0a6; --line:#3c4043; --head:#202328; }}
}}
body {{ background:var(--bg); color:var(--fg); font:15px/1.55 system-ui, sans-serif;
       max-width:1100px; margin:0 auto; padding:24px 16px; }}
h2 {{ margin-top:40px; }} p, li {{ color:var(--muted); }} a {{ color:inherit; }}
table {{ border-collapse:collapse; width:100%; font-size:.9rem; }}
th, td {{ border:1px solid var(--line); padding:6px 8px; text-align:left; }} th {{ background:var(--head); }}
pre {{ overflow-x:auto; }} pre.mermaid {{ background:transparent; text-align:center; }}
</style></head><body>
<h1>Diagrams</h1>
<p>Every diagram here, with what it shows and whether it is readable.</p>
<table><thead><tr><th>Diagram</th><th>Readability</th></tr></thead><tbody>{toc}</tbody></table>
{chr(10).join(sections)}
<script src="{MERMAID_CDN}"></script>
<script>if (window.mermaid) {{ mermaid.initialize({{ startOnLoad: true, securityLevel: "strict",
  theme: matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "default" }}); }}</script>
</body></html>
"""


def write(directory, files):
    written, refused = [], []
    for name, text in files.items():
        path = os.path.join(directory, name)
        if os.path.isfile(path):
            with open(path, encoding="utf-8") as fh:
                if GENERATED not in fh.read():
                    refused.append(name)
                    continue
        tmp = path + ".tmp"
        with open(tmp, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        os.replace(tmp, path)
        written.append(name)
    return written, refused


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--dir", default=os.path.join("docs", "diagrams"))
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args(argv)
    if not os.path.isdir(args.dir):
        parser.error(f"--dir {args.dir!r} is not a directory")
    items = collect(args.dir)
    files = {"README.md": render_markdown(items), "index.html": render_html(items)}
    if not args.write:
        for name, text in files.items():
            print(f"would write {os.path.join(args.dir, name)} ({len(items)} diagram(s), "
                  f"{len(text.splitlines())} lines)")
        print("dry run: nothing written; re-run with --write")
        return 0
    written, refused = write(args.dir, files)
    for name in written:
        print(f"wrote {os.path.join(args.dir, name)}")
    for name in refused:
        print(f"REFUSED {os.path.join(args.dir, name)}: not marked '{GENERATED}'", file=sys.stderr)
    return 1 if refused else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
